//+------------------------------------------------------------------+
//|                                                    EMA_ATR_EA.mq5 |
//|                                    Generated by Senior MQL5 Dev  |
//|                                      Strategy: EMA Cross with ATR |
//+------------------------------------------------------------------+
#property copyright "Senior MQL5 Developer"
#property link      ""
#property version   "1.00"
#property description "EA based on EMA20 > EMA50 and distance exceeding ATR ratio."
#property strict

#include <Trade\Trade.mqh>
#include <Trade\PositionInfo.mqh>

//--- Input Parameters
input group "=== General Parameters ==="
input double InpLotSize          = 0.01;                    // Lot Size
input int    InpStopLoss         = 300;                     // Stop Loss (points)
input int    InpTakeProfit       = 600;                     // Take Profit (points)
input ulong  InpMagicNumber      = 24032025;                // Magic Number
input int    InpSlippage         = 10;                      // Slippage (points)
input int    InpMaxSpread        = 30;                      // Maximum spread allowed (points)
input int    InpMaxPositions     = 1;                       // Maximum open positions

input group "=== Indicator Parameters ==="
input int    InpPeriodFastEMA    = 20;                      // Fast EMA Period
input int    InpPeriodSlowEMA    = 50;                      // Slow EMA Period
input int    InpATRPeriod        = 14;                      // ATR Period
input double InpATRRatio         = 0.5;                     // Minimum distance ratio to ATR

input group "=== Trade Management ==="
input bool   InpUseBreakEven     = true;                    // Enable Break Even
input int    InpBreakEvenTrigger = 150;                     // Break Even trigger (points profit)
input int    InpBreakEvenLock    = 0;                       // Break Even lock profit (points)
input bool   InpUseTrailingStop  = true;                    // Enable Trailing Stop
input int    InpTrailingStart    = 200;                     // Trailing Start (points profit)
input int    InpTrailingDistance = 200;                     // Trailing Distance (points)

//--- Global Variables
CTrade         trade;
CPositionInfo  posInfo;
MqlDateTime    lastBarTime;
int            handleEMA_fast = INVALID_HANDLE;
int            handleEMA_slow = INVALID_HANDLE;
int            handleATR      = INVALID_HANDLE;
bool           isFirstRun = true;

//+------------------------------------------------------------------+
//| Expert initialization function                                   |
//+------------------------------------------------------------------+
int OnInit()
  {
   //--- Set magic number and slippage for CTrade
   trade.SetExpertMagicNumber(InpMagicNumber);
   trade.SetDeviationInPoints(InpSlippage);
   trade.SetTypeFillingBySymbol(_Symbol);

   //--- Create indicator handles
   handleEMA_fast = iMA(_Symbol, PERIOD_CURRENT, InpPeriodFastEMA, 0, MODE_EMA, PRICE_CLOSE);
   handleEMA_slow = iMA(_Symbol, PERIOD_CURRENT, InpPeriodSlowEMA, 0, MODE_EMA, PRICE_CLOSE);
   handleATR      = iATR(_Symbol, PERIOD_CURRENT, InpATRPeriod);

   if(handleEMA_fast == INVALID_HANDLE || handleEMA_slow == INVALID_HANDLE || handleATR == INVALID_HANDLE)
     {
      Print("Failed to create indicator handles. Error: ", GetLastError());
      return(INIT_FAILED);
     }

   //--- Initialize last bar time
   datetime currentTime = iTime(_Symbol, PERIOD_CURRENT, 0);
   TimeToStruct(currentTime, lastBarTime);

   Print("EMA_ATR_EA initialized successfully.");
   return(INIT_SUCCEEDED);
  }

//+------------------------------------------------------------------+
//| Expert deinitialization function                                 |
//+------------------------------------------------------------------+
void OnDeinit(const int reason)
  {
   //--- Release indicator handles
   if(handleEMA_fast != INVALID_HANDLE)
      IndicatorRelease(handleEMA_fast);
   if(handleEMA_slow != INVALID_HANDLE)
      IndicatorRelease(handleEMA_slow);
   if(handleATR != INVALID_HANDLE)
      IndicatorRelease(handleATR);

   Print("EMA_ATR_EA deinitialized. Reason: ", reason);
  }

//+------------------------------------------------------------------+
//| Expert tick function                                             |
//+------------------------------------------------------------------+
void OnTick()
  {
   //--- Check if we have a new bar
   if(!IsNewBar())
      return;

   //--- Check spread before any trading decision
   if(!IsSpreadAllowed())
     {
      Print("Spread too high (", GetCurrentSpread(), " points). Max allowed: ", InpMaxSpread);
      return;
     }

   //--- Check number of open positions for this magic number
   int openPositions = CountPositions(InpMagicNumber);
   if(openPositions >= InpMaxPositions)
     {
      //--- Manage existing positions
      if(InpUseBreakEven)
         ManageBreakEven();
      if(InpUseTrailingStop)
         ManageTrailingStop();
      return; //--- Don't open new positions
     }

   //--- Evaluate entry signals
   int signal = GetSignal();

   //--- Execute trade based on signal
   if(signal > 0)
      OpenBuy();
   else if(signal < 0)
      OpenSell();

   //--- Manage existing positions after potential new entry
   if(InpUseBreakEven)
      ManageBreakEven();
   if(InpUseTrailingStop)
      ManageTrailingStop();
  }

//+------------------------------------------------------------------+
//| Check if new bar has formed                                      |
//+------------------------------------------------------------------+
bool IsNewBar()
  {
   datetime currentTime = iTime(_Symbol, PERIOD_CURRENT, 0);
   MqlDateTime currentBarTime;
   TimeToStruct(currentTime, currentBarTime);

   if(currentBarTime.year != lastBarTime.year ||
      currentBarTime.mon  != lastBarTime.mon  ||
      currentBarTime.day  != lastBarTime.day  ||
      currentBarTime.hour != lastBarTime.hour ||
      currentBarTime.min  != lastBarTime.min)
     {
      lastBarTime = currentBarTime;
      return true;
     }
   return false;
  }

//+------------------------------------------------------------------+
//| Check if current spread is within allowed limits                 |
//+------------------------------------------------------------------+
bool IsSpreadAllowed()
  {
   double spread = GetCurrentSpread();
   return (spread <= InpMaxSpread);
  }

//+------------------------------------------------------------------+
//| Get current spread in points                                     |
//+------------------------------------------------------------------+
double GetCurrentSpread()
  {
   double ask = SymbolInfoDouble(_Symbol, SYMBOL_ASK);
   double bid = SymbolInfoDouble(_Symbol, SYMBOL_BID);
   double point = SymbolInfoDouble(_Symbol, SYMBOL_POINT);
   if(point <= 0)
      return 0;
   return ((ask - bid) / point);
  }

//+------------------------------------------------------------------+
//| Count open positions by magic number                             |
//+------------------------------------------------------------------+
int CountPositions(ulong magic)
  {
   int count = 0;
   for(int i = PositionsTotal() - 1; i >= 0; i--)
     {
      if(posInfo.SelectByIndex(i))
        {
         if(posInfo.Magic() == magic && posInfo.Symbol() == _Symbol)
            count++;
        }
     }
   return count;
  }

//+------------------------------------------------------------------+
//| Get trading signal                                               |
//+------------------------------------------------------------------+
int GetSignal()
  {
   double emaFast[], emaSlow[], atr[];
   ArraySetAsSeries(emaFast, true);
   ArraySetAsSeries(emaSlow, true);
   ArraySetAsSeries(atr, true);

   //--- Get indicator values (need at least 2 bars)
   if(CopyBuffer(handleEMA_fast, 0, 0, 2, emaFast) < 2)
     {
      Print("Failed to copy fast EMA data. Error: ", GetLastError());
      return 0;
     }
   if(CopyBuffer(handleEMA_slow, 0, 0, 2, emaSlow) < 2)
     {
      Print("Failed to copy slow EMA data. Error: ", GetLastError());
      return 0;
     }
   if(CopyBuffer(handleATR, 0, 0, 2, atr) < 2)
     {
      Print("Failed to copy ATR data. Error: ", GetLastError());
      return 0;
     }

   //--- Check for valid data
   if(emaFast[0] <= 0 || emaSlow[0] <= 0 || atr[0] <= 0)
      return 0;

   double emaFastVal = emaFast[0];
   double emaSlowVal = emaSlow[0];
   double atrValue   = atr[0];

   //--- BUY signal: EMA20 > EMA50 and distance exceeds ATR ratio
   if(emaFastVal > emaSlowVal)
     {
      double distance = emaFastVal - emaSlowVal;
      double minDistance = atrValue * InpATRRatio;
      if(distance >= minDistance)
         return 1;
     }
   //--- SELL signal: EMA20 < EMA50 and distance exceeds ATR ratio
   else if(emaFastVal < emaSlowVal)
     {
      double distance = emaSlowVal - emaFastVal;
      double minDistance = atrValue * InpATRRatio;
      if(distance >= minDistance)
         return -1;
     }

   return 0;
  }

//+------------------------------------------------------------------+
//| Open Buy position                                                |
//+------------------------------------------------------------------+
void OpenBuy()
  {
   double price = SymbolInfoDouble(_Symbol, SYMBOL_ASK);
   double sl = 0;
   double tp = 0;

   if(InpStopLoss > 0)
      sl = price - InpStopLoss * _Point;
   if(InpTakeProfit > 0)
      tp = price + InpTakeProfit * _Point;

   double lotSize = NormalizeLot(InpLotSize);

   if(!trade.Buy(lotSize, _Symbol, price, sl, tp, "EMA_ATR_EA BUY"))
     {
      Print("Buy order failed. Error: ", trade.ResultRetcode(), " - ", trade.ResultRetcodeDescription());
     }
   else
     {
      Print("Buy order placed successfully. Price: ", price, ", SL: ", sl, ", TP: ", tp);
     }
  }

//+------------------------------------------------------------------+
//| Open Sell position                                               |
//+------------------------------------------------------------------+
void OpenSell()
  {
   double price = SymbolInfoDouble(_Symbol, SYMBOL_BID);
   double sl = 0;
   double tp = 0;

   if(InpStopLoss > 0)
      sl = price + InpStopLoss * _Point;
   if(InpTakeProfit > 0)
      tp = price - InpTakeProfit * _Point;

   double lotSize = NormalizeLot(InpLotSize);

   if(!trade.Sell(lotSize, _Symbol, price, sl, tp, "EMA_ATR_EA SELL"))
     {
      Print("Sell order failed. Error: ", trade.ResultRetcode(), " - ", trade.ResultRetcodeDescription());
     }
   else
     {
      Print("Sell order placed successfully. Price: ", price, ", SL: ", sl, ", TP: ", tp);
     }
  }

//+------------------------------------------------------------------+
//| Manage Break Even for open positions                             |
//+------------------------------------------------------------------+
void ManageBreakEven()
  {
   for(int i = PositionsTotal() - 1; i >= 0; i--)
     {
      if(posInfo.SelectByIndex(i))
        {
         if(posInfo.Magic() == InpMagicNumber && posInfo.Symbol() == _Symbol)
           {
            double currentSL = posInfo.StopLoss();
            double openPrice  = posInfo.PriceOpen();
            double point      = _Point;
            double beTrigger  = InpBreakEvenTrigger * point;
            double beLock     = InpBreakEvenLock * point;

            if(posInfo.PositionType() == POSITION_TYPE_BUY)
              {
               double currentPrice = SymbolInfoDouble(_Symbol, SYMBOL_BID);
               double profitPoints = (currentPrice - openPrice) / point;

               if(profitPoints >= InpBreakEvenTrigger && currentSL < openPrice + beLock)
                 {
                  double newSL = openPrice + beLock;
                  if(!trade.PositionModify(posInfo.Ticket(), newSL, posInfo.TakeProfit()))
                    {
                     Print("Failed to modify buy position for Break Even. Error: ", trade.ResultRetcode());
                    }
                  else
                    {
                     Print("Buy position ", posInfo.Ticket(), " Break Even applied. New SL: ", newSL);
                    }
                 }
              }
            else if(posInfo.PositionType() == POSITION_TYPE_SELL)
              {
               double currentPrice = SymbolInfoDouble(_Symbol, SYMBOL_ASK);
               double profitPoints = (openPrice - currentPrice) / point;

               if(profitPoints >= InpBreakEvenTrigger && currentSL > openPrice - beLock)
                 {
                  double newSL = openPrice - beLock;
                  if(!trade.PositionModify(posInfo.Ticket(), newSL, posInfo.TakeProfit()))
                    {
                     Print("Failed to modify sell position for Break Even. Error: ", trade.ResultRetcode());
                    }
                  else
                    {
                     Print("Sell position ", posInfo.Ticket(), " Break Even applied. New SL: ", newSL);
                    }
                 }
              }
           }
        }
     }
  }

//+------------------------------------------------------------------+
//| Manage Trailing Stop for open positions                          |
//+------------------------------------------------------------------+
void ManageTrailingStop()
  {
   for(int i = PositionsTotal() - 1; i >= 0; i--)
     {
      if(posInfo.SelectByIndex(i))
        {
         if(posInfo.Magic() == InpMagicNumber && posInfo.Symbol() == _Symbol)
           {
            double currentSL = posInfo.StopLoss();
            double point      = _Point;
            double trailStart = InpTrailingStart * point;
            double trailDist  = InpTrailingDistance * point;

            if(posInfo.PositionType() == POSITION_TYPE_BUY)
              {
               double currentPrice = SymbolInfoDouble(_Symbol, SYMBOL_BID);
               double profitPoints = (currentPrice - posInfo.PriceOpen()) / point;

               if(profitPoints >= InpTrailingStart)
                 {
                  double newSL = currentPrice - trailDist;
                  if(newSL > currentSL + point)
                    {
                     if(!trade.PositionModify(posInfo.Ticket(), newSL, posInfo.TakeProfit()))
                       {
                        Print("Failed to modify buy position for Trailing Stop. Error: ", trade.ResultRetcode());
                       }
                     else
                       {
                        Print("Buy position ", posInfo.Ticket(), " Trailing Stop applied. New SL: ", newSL);
                       }
                    }
                 }
              }
            else if(posInfo.PositionType() == POSITION_TYPE_SELL)
              {
               double currentPrice = SymbolInfoDouble(_Symbol, SYMBOL_ASK);
               double profitPoints = (posInfo.PriceOpen() - currentPrice) / point;

               if(profitPoints >= InpTrailingStart)
                 {
                  double newSL = currentPrice + trailDist;
                  if(newSL < currentSL - point)
                    {
                     if(!trade.PositionModify(posInfo.Ticket(), newSL, posInfo.TakeProfit()))
                       {
                        Print("Failed to modify sell position for Trailing Stop. Error: ", trade.ResultRetcode());
                       }
                     else
                       {
                        Print("Sell position ", posInfo.Ticket(), " Trailing Stop applied. New SL: ", newSL);
                       }
                    }
                 }
              }
           }
        }
     }
  }

//+------------------------------------------------------------------+
//| Normalize lot size to broker's allowed values                    |
//+------------------------------------------------------------------+
double NormalizeLot(double lotSize)
  {
   double minLot  = SymbolInfoDouble(_Symbol, SYMBOL_VOLUME_MIN);
   double maxLot  = SymbolInfoDouble(_Symbol, SYMBOL_VOLUME_MAX);
   double lotStep = SymbolInfoDouble(_Symbol, SYMBOL_VOLUME_STEP);

   if(lotSize < minLot)
      lotSize = minLot;
   if(lotSize > maxLot)
      lotSize = maxLot;

   if(lotStep > 0)
      lotSize = MathFloor(lotSize / lotStep) * lotStep;

   lotSize = NormalizeDouble(lotSize, 2);

   return lotSize;
  }
//+------------------------------------------------------------------+