//+------------------------------------------------------------------+
//|                                                  SAR_EA.mq5     |
//|                               Generated by Senior MQL5 Developer|
//+------------------------------------------------------------------+
#property copyright "Senior MQL5 Developer"
#property link      ""
#property version   "1.00"

#include <Trade\Trade.mqh>

//--- Input Parameters
input double   InpLotSize        = 0.01;    // Lot Size
input int      InpStopLoss       = 300;     // Stop Loss (points)
input int      InpTakeProfit     = 600;     // Take Profit (points)
input ulong    InpMagicNumber    = 123456;  // Magic Number
input int      InpSlippage       = 10;      // Slippage (points)
input int      InpMaxSpread      = 30;      // Max Spread (points)
input int      InpMaxPositions   = 1;       // Max Positions

//--- Break Even & Trailing Inputs
input bool     InpUseBreakEven   = true;    // Use Break Even
input int      InpBreakEvenStart = 150;     // Break Even Start (points)
input bool     InpUseTrailing    = true;    // Use Trailing Stop
input int      InpTrailingStart  = 200;     // Trailing Start (points)

//--- Parabolic SAR Parameters
input double   InpSarStep        = 0.02;    // SAR Step
input double   InpSarMaximum     = 0.2;     // SAR Maximum

//--- Global Variables
CTrade  trade;
int     SarHandle = INVALID_HANDLE;
double  SarBuffer[];
MqlRates CurrentBar[];
datetime LastBarTime = 0;

//+------------------------------------------------------------------+
//| Expert initialization function                                   |
//+------------------------------------------------------------------+
int OnInit()
  {
   //--- Set magic number, deviation and type of order filling
   trade.SetExpertMagicNumber(InpMagicNumber);
   trade.SetDeviationInPoints(InpSlippage);
   trade.SetTypeFillingBySymbol(_Symbol);

   //--- Create Parabolic SAR indicator handle
   SarHandle = iSAR(_Symbol, PERIOD_CURRENT, InpSarStep, InpSarMaximum);
   if(SarHandle == INVALID_HANDLE)
     {
      Print("Failed to create SAR indicator handle. Error: ", GetLastError());
      return(INIT_FAILED);
     }

   //--- Initialize arrays
   ArraySetAsSeries(SarBuffer, true);
   ArraySetAsSeries(CurrentBar, true);

   //--- Reset last bar time
   LastBarTime = 0;

   Print("SAR EA initialized successfully on ", _Symbol);
   return(INIT_SUCCEEDED);
  }

//+------------------------------------------------------------------+
//| Expert deinitialization function                                 |
//+------------------------------------------------------------------+
void OnDeinit(const int reason)
  {
   //--- Release indicator handle
   if(SarHandle != INVALID_HANDLE)
     {
      IndicatorRelease(SarHandle);
      SarHandle = INVALID_HANDLE;
     }

   Print("SAR EA deinitialized. Reason: ", reason);
  }

//+------------------------------------------------------------------+
//| Expert tick function                                             |
//+------------------------------------------------------------------+
void OnTick()
  {
   //--- Check for new bar
   if(!IsNewBar())
      return;

   //--- Check maximum spread
   if(!CheckSpread())
      return;

   //--- Check existing positions
   if(CountPositions() >= InpMaxPositions)
     {
      //--- Still manage positions even if max reached
      ManagePositions();
      return;
     }

   //--- Get current SAR values
   if(!GetSarValues())
      return;

   //--- Get current bar data
   if(CopyRates(_Symbol, PERIOD_CURRENT, 0, 3, CurrentBar) < 3)
     {
      Print("Failed to get current bar data. Error: ", GetLastError());
      return;
     }

   //--- Check trading signals
   int signal = CheckSignal();
   if(signal == 0)
     {
      //--- Still manage positions
      ManagePositions();
      return;
     }

   //--- Execute trades
   if(signal > 0)
      ExecuteBuy();
   else if(signal < 0)
      ExecuteSell();

   //--- Manage open positions
   ManagePositions();
  }

//+------------------------------------------------------------------+
//| Check if new bar has formed                                      |
//+------------------------------------------------------------------+
bool IsNewBar()
  {
   datetime currentBarTime = iTime(_Symbol, PERIOD_CURRENT, 0);
   if(currentBarTime != LastBarTime)
     {
      LastBarTime = currentBarTime;
      return true;
     }
   return false;
  }

//+------------------------------------------------------------------+
//| Check maximum spread                                             |
//+------------------------------------------------------------------+
bool CheckSpread()
  {
   long spread = SymbolInfoInteger(_Symbol, SYMBOL_SPREAD);
   double point = SymbolInfoDouble(_Symbol, SYMBOL_POINT);
   
   //--- For XAU (Gold) with 2 decimal places, point = 0.01
   //--- Spread in points = spread * point / point = spread (raw value)
   //--- Actually SYMBOL_SPREAD returns spread in points already
   int spreadPoints = (int)spread;

   if(spreadPoints > InpMaxSpread)
     {
      Print("Spread too high: ", spreadPoints, " points. Max allowed: ", InpMaxSpread);
      return false;
     }
   return true;
  }

//+------------------------------------------------------------------+
//| Count open positions with current magic number                   |
//+------------------------------------------------------------------+
int CountPositions()
  {
   int count = 0;
   for(int i = PositionsTotal() - 1; i >= 0; i--)
     {
      ulong ticket = PositionGetTicket(i);
      if(ticket > 0)
        {
         if(PositionGetInteger(POSITION_MAGIC) == InpMagicNumber &&
            PositionGetString(POSITION_SYMBOL) == _Symbol)
            count++;
        }
     }
   return count;
  }

//+------------------------------------------------------------------+
//| Get SAR values                                                   |
//+------------------------------------------------------------------+
bool GetSarValues()
  {
   if(CopyBuffer(SarHandle, 0, 0, 3, SarBuffer) < 3)
     {
      Print("Failed to copy SAR buffer. Error: ", GetLastError());
      return false;
     }
   return true;
  }

//+------------------------------------------------------------------+
//| Check trading signal                                             |
//+------------------------------------------------------------------+
int CheckSignal()
  {
   double currentPrice = CurrentBar[0].close;
   double sarValue = SarBuffer[0];

   //--- SAR below price = BUY signal
   if(sarValue < currentPrice)
      return 1;

   //--- SAR above price = SELL signal
   if(sarValue > currentPrice)
      return -1;

   return 0;
  }

//+------------------------------------------------------------------+
//| Execute Buy order                                                |
//+------------------------------------------------------------------+
void ExecuteBuy()
  {
   double price = SymbolInfoDouble(_Symbol, SYMBOL_ASK);
   double sl = 0, tp = 0;

   //--- Calculate Stop Loss and Take Profit
   if(InpStopLoss > 0)
      sl = price - InpStopLoss * Point();
   if(InpTakeProfit > 0)
      tp = price + InpTakeProfit * Point();

   //--- Normalize prices
   price = NormalizeDouble(price, _Digits);
   sl = NormalizeDouble(sl, _Digits);
   tp = NormalizeDouble(tp, _Digits);

   //--- Execute buy order
   if(trade.Buy(InpLotSize, _Symbol, price, sl, tp, "SAR EA Buy"))
     {
      Print("Buy order opened successfully at price: ", price);
     }
   else
     {
      Print("Failed to open Buy order. Error: ", GetLastError());
     }
  }

//+------------------------------------------------------------------+
//| Execute Sell order                                               |
//+------------------------------------------------------------------+
void ExecuteSell()
  {
   double price = SymbolInfoDouble(_Symbol, SYMBOL_BID);
   double sl = 0, tp = 0;

   //--- Calculate Stop Loss and Take Profit
   if(InpStopLoss > 0)
      sl = price + InpStopLoss * Point();
   if(InpTakeProfit > 0)
      tp = price - InpTakeProfit * Point();

   //--- Normalize prices
   price = NormalizeDouble(price, _Digits);
   sl = NormalizeDouble(sl, _Digits);
   tp = NormalizeDouble(tp, _Digits);

   //--- Execute sell order
   if(trade.Sell(InpLotSize, _Symbol, price, sl, tp, "SAR EA Sell"))
     {
      Print("Sell order opened successfully at price: ", price);
     }
   else
     {
      Print("Failed to open Sell order. Error: ", GetLastError());
     }
  }

//+------------------------------------------------------------------+
//| Manage open positions (Break Even & Trailing)                    |
//+------------------------------------------------------------------+
void ManagePositions()
  {
   for(int i = PositionsTotal() - 1; i >= 0; i--)
     {
      ulong ticket = PositionGetTicket(i);
      if(ticket > 0)
        {
         if(PositionGetInteger(POSITION_MAGIC) == InpMagicNumber &&
            PositionGetString(POSITION_SYMBOL) == _Symbol)
           {
            //--- Get position details
            long positionType = PositionGetInteger(POSITION_TYPE);
            double currentPrice = PositionGetDouble(POSITION_PRICE_CURRENT);
            double openPrice = PositionGetDouble(POSITION_PRICE_OPEN);
            double currentSL = PositionGetDouble(POSITION_SL);
            double currentTP = PositionGetDouble(POSITION_TP);
            double point = Point();
            double newSL = 0;

            //--- For Buy positions
            if(positionType == POSITION_TYPE_BUY)
              {
               double profitPoints = (currentPrice - openPrice) / point;

               //--- Break Even
               if(InpUseBreakEven && profitPoints >= InpBreakEvenStart)
                 {
                  double breakEvenLevel = openPrice;
                  if(MathAbs(breakEvenLevel - currentSL) > point)
                    {
                     trade.PositionModify(ticket, breakEvenLevel, currentTP);
                    }
                 }

               //--- Trailing Stop
               if(InpUseTrailing && profitPoints >= InpTrailingStart)
                 {
                  newSL = currentPrice - InpTrailingStart * point;
                  if(newSL > currentSL && MathAbs(newSL - currentSL) > point)
                    {
                     trade.PositionModify(ticket, newSL, currentTP);
                    }
                 }
              }

            //--- For Sell positions
            if(positionType == POSITION_TYPE_SELL)
              {
               double profitPoints = (openPrice - currentPrice) / point;

               //--- Break Even
               if(InpUseBreakEven && profitPoints >= InpBreakEvenStart)
                 {
                  double breakEvenLevel = openPrice;
                  if(MathAbs(breakEvenLevel - currentSL) > point)
                    {
                     trade.PositionModify(ticket, breakEvenLevel, currentTP);
                    }
                 }

               //--- Trailing Stop
               if(InpUseTrailing && profitPoints >= InpTrailingStart)
                 {
                  newSL = currentPrice + InpTrailingStart * point;
                  if((newSL < currentSL || currentSL == 0) && MathAbs(newSL - currentSL) > point)
                    {
                     trade.PositionModify(ticket, newSL, currentTP);
                    }
                 }
              }
           }
        }
     }
  }
//+------------------------------------------------------------------+