//+------------------------------------------------------------------+
//|                                              EA_TrendScore.mq5  |
//|                                    Generated by Senior MQL5 Dev  |
//+------------------------------------------------------------------+
#property copyright "Senior MQL5 Developer"
#property version   "1.00"
#property strict

#include <Trade\Trade.mqh>

//--- Input Parameters
input double InpLotSize          = 0.01;    // Lot Size
input int    InpStopLoss         = 300;     // Stop Loss (points)
input int    InpTakeProfit       = 600;     // Take Profit (points)
input ulong  InpMagicNumber      = 123456;  // Magic Number
input int    InpSlippage         = 10;      // Slippage (points)

//--- Break Even & Trailing Stop
input bool   InpUseBreakEven     = true;    // Use Break Even
input int    InpBreakEvenTrigger = 150;     // Break Even Trigger (points)
input bool   InpUseTrailingStop  = true;    // Use Trailing Stop
input int    InpTrailingStart    = 200;     // Trailing Start (points)
input int    InpTrailingStep     = 50;      // Trailing Step (points)

//--- Filters
input int    InpMaxSpread        = 30;      // Max Spread (points)
input int    InpMaxOpenPositions = 1;       // Max Open Positions

//--- Scoring Thresholds
input int    InpScoreThreshold   = 70;      // Minimum score to trade (0-100)

//--- Indicators Parameters
input int    InpEmaFastPeriod    = 20;      // EMA Fast Period
input int    InpEmaSlowPeriod    = 50;      // EMA Slow Period
input int    InpMacdFastPeriod   = 12;      // MACD Fast Period
input int    InpMacdSlowPeriod   = 26;      // MACD Slow Period
input int    InpMacdSignalPeriod = 9;       // MACD Signal Period
input int    InpAdxPeriod        = 14;      // ADX Period
input double InpAdxThreshold     = 25.0;    // ADX Threshold

//--- Global Variables
CTrade trade;
int    handleEmaFast = INVALID_HANDLE;
int    handleEmaSlow = INVALID_HANDLE;
int    handleMacd    = INVALID_HANDLE;
int    handleAdx     = INVALID_HANDLE;
datetime lastBarTime = 0;

//+------------------------------------------------------------------+
//| Expert initialization function                                   |
//+------------------------------------------------------------------+
int OnInit()
{
   //--- Set magic number
   trade.SetExpertMagicNumber(InpMagicNumber);
   trade.SetDeviationInPoints(InpSlippage);

   //--- Initialize indicators
   handleEmaFast = iMA(_Symbol, PERIOD_CURRENT, InpEmaFastPeriod, 0, MODE_EMA, PRICE_CLOSE);
   handleEmaSlow = iMA(_Symbol, PERIOD_CURRENT, InpEmaSlowPeriod, 0, MODE_EMA, PRICE_CLOSE);
   handleMacd    = iMACD(_Symbol, PERIOD_CURRENT, InpMacdFastPeriod, InpMacdSlowPeriod, InpMacdSignalPeriod, PRICE_CLOSE);
   handleAdx     = iADX(_Symbol, PERIOD_CURRENT, InpAdxPeriod);

   if(handleEmaFast == INVALID_HANDLE || handleEmaSlow == INVALID_HANDLE ||
      handleMacd == INVALID_HANDLE || handleAdx == INVALID_HANDLE)
   {
      Print("Failed to create indicator handles");
      return INIT_FAILED;
   }

   lastBarTime = 0;
   return INIT_SUCCEEDED;
}

//+------------------------------------------------------------------+
//| Expert deinitialization function                                 |
//+------------------------------------------------------------------+
void OnDeinit(const int reason)
{
   if(handleEmaFast != INVALID_HANDLE) IndicatorRelease(handleEmaFast);
   if(handleEmaSlow != INVALID_HANDLE) IndicatorRelease(handleEmaSlow);
   if(handleMacd != INVALID_HANDLE)    IndicatorRelease(handleMacd);
   if(handleAdx != INVALID_HANDLE)     IndicatorRelease(handleAdx);
}

//+------------------------------------------------------------------+
//| Expert tick function                                             |
//+------------------------------------------------------------------+
void OnTick()
{
   //--- Check for new bar
   if(!IsNewBar())
      return;

   //--- Check spread
   if(!CheckSpread())
      return;

   //--- Check open positions
   if(CountOpenPositions() >= InpMaxOpenPositions)
      return;

   //--- Get signal
   int signal = GetSignal();

   //--- Execute trade
   if(signal > 0)
      OpenBuy();
   else if(signal < 0)
      OpenSell();

   //--- Manage open positions
   if(InpUseBreakEven || InpUseTrailingStop)
      ManagePositions();
}

//+------------------------------------------------------------------+
//| Check if new bar has formed                                      |
//+------------------------------------------------------------------+
bool IsNewBar()
{
   datetime currentBarTime = iTime(_Symbol, PERIOD_CURRENT, 0);
   if(currentBarTime != lastBarTime)
   {
      lastBarTime = currentBarTime;
      return true;
   }
   return false;
}

//+------------------------------------------------------------------+
//| Check spread                                                     |
//+------------------------------------------------------------------+
bool CheckSpread()
{
   long spread = SymbolInfoInteger(_Symbol, SYMBOL_SPREAD);
   if(spread > InpMaxSpread)
      return false;
   return true;
}

//+------------------------------------------------------------------+
//| Count open positions with current magic number                   |
//+------------------------------------------------------------------+
int CountOpenPositions()
{
   int count = 0;
   for(int i = PositionsTotal() - 1; i >= 0; i--)
   {
      ulong ticket = PositionGetTicket(i);
      if(ticket > 0)
      {
         if(PositionGetString(POSITION_SYMBOL) == _Symbol &&
            PositionGetInteger(POSITION_MAGIC) == InpMagicNumber)
            count++;
      }
   }
   return count;
}

//+------------------------------------------------------------------+
//| Get trading signal based on scoring system                       |
//+------------------------------------------------------------------+
int GetSignal()
{
   double emaFast[], emaSlow[], macdMain[], macdSignal[], adxMain[], adxPlus[], adxMinus[];

   ArraySetAsSeries(emaFast, true);
   ArraySetAsSeries(emaSlow, true);
   ArraySetAsSeries(macdMain, true);
   ArraySetAsSeries(macdSignal, true);
   ArraySetAsSeries(adxMain, true);
   ArraySetAsSeries(adxPlus, true);
   ArraySetAsSeries(adxMinus, true);

   if(CopyBuffer(handleEmaFast, 0, 0, 3, emaFast) < 3) return 0;
   if(CopyBuffer(handleEmaSlow, 0, 0, 3, emaSlow) < 3) return 0;
   if(CopyBuffer(handleMacd, 0, 0, 3, macdMain) < 3) return 0;
   if(CopyBuffer(handleMacd, 1, 0, 3, macdSignal) < 3) return 0;
   if(CopyBuffer(handleAdx, 0, 0, 3, adxMain) < 3) return 0;
   if(CopyBuffer(handleAdx, 1, 0, 3, adxPlus) < 3) return 0;
   if(CopyBuffer(handleAdx, 2, 0, 3, adxMinus) < 3) return 0;

   int score = 0;

   //--- EMA Scoring (0-30 points)
   if(emaFast[0] > emaSlow[0])
      score += 30;  // Bullish EMA
   else if(emaFast[0] < emaSlow[0])
      score -= 30;  // Bearish EMA

   //--- MACD Scoring (0-30 points)
   if(macdMain[0] > macdSignal[0] && macdMain[1] <= macdSignal[1])
      score += 30;  // Bullish MACD cross
   else if(macdMain[0] < macdSignal[0] && macdMain[1] >= macdSignal[1])
      score -= 30;  // Bearish MACD cross
   else if(macdMain[0] > macdSignal[0])
      score += 15;  // MACD above signal
   else if(macdMain[0] < macdSignal[0])
      score -= 15;  // MACD below signal

   //--- ADX Scoring (0-40 points)
   if(adxMain[0] > InpAdxThreshold)
   {
      if(adxPlus[0] > adxMinus[0])
         score += 40;  // Strong uptrend
      else if(adxMinus[0] > adxPlus[0])
         score -= 40;  // Strong downtrend
   }

   //--- Structure scoring (0-10 points)
   double close1 = iClose(_Symbol, PERIOD_CURRENT, 1);
   double close2 = iClose(_Symbol, PERIOD_CURRENT, 2);
   double high1 = iHigh(_Symbol, PERIOD_CURRENT, 1);
   double low1  = iLow(_Symbol, PERIOD_CURRENT, 1);

   if(close1 > close2 && close1 > (high1 + low1) / 2)
      score += 10;  // Bullish structure
   else if(close1 < close2 && close1 < (high1 + low1) / 2)
      score -= 10;  // Bearish structure

   //--- Check threshold
   if(score >= InpScoreThreshold)
      return 1;   // Buy signal
   else if(score <= -InpScoreThreshold)
      return -1;  // Sell signal

   return 0;  // No signal
}

//+------------------------------------------------------------------+
//| Open Buy position                                                |
//+------------------------------------------------------------------+
void OpenBuy()
{
   double price = SymbolInfoDouble(_Symbol, SYMBOL_ASK);
   double sl = (InpStopLoss > 0) ? price - InpStopLoss * _Point : 0;
   double tp = (InpTakeProfit > 0) ? price + InpTakeProfit * _Point : 0;

   if(!trade.Buy(InpLotSize, _Symbol, price, sl, tp, "EA TrendScore Buy"))
   {
      Print("Buy order failed. Error: ", trade.ResultRetcode());
   }
}

//+------------------------------------------------------------------+
//| Open Sell position                                               |
//+------------------------------------------------------------------+
void OpenSell()
{
   double price = SymbolInfoDouble(_Symbol, SYMBOL_BID);
   double sl = (InpStopLoss > 0) ? price + InpStopLoss * _Point : 0;
   double tp = (InpTakeProfit > 0) ? price - InpTakeProfit * _Point : 0;

   if(!trade.Sell(InpLotSize, _Symbol, price, sl, tp, "EA TrendScore Sell"))
   {
      Print("Sell order failed. Error: ", trade.ResultRetcode());
   }
}

//+------------------------------------------------------------------+
//| Manage positions (Break Even & Trailing Stop)                    |
//+------------------------------------------------------------------+
void ManagePositions()
{
   for(int i = PositionsTotal() - 1; i >= 0; i--)
   {
      ulong ticket = PositionGetTicket(i);
      if(ticket > 0)
      {
         if(PositionGetString(POSITION_SYMBOL) == _Symbol &&
            PositionGetInteger(POSITION_MAGIC) == InpMagicNumber)
         {
            double currentPrice = PositionGetDouble(POSITION_PRICE_CURRENT);
            double openPrice = PositionGetDouble(POSITION_PRICE_OPEN);
            double sl = PositionGetDouble(POSITION_SL);
            double tp = PositionGetDouble(POSITION_TP);
            double point = _Point;
            long positionType = PositionGetInteger(POSITION_TYPE);

            if(positionType == POSITION_TYPE_BUY)
            {
               double profitPoints = (currentPrice - openPrice) / point;

               //--- Break Even
               if(InpUseBreakEven && profitPoints >= InpBreakEvenTrigger)
               {
                  double newSl = openPrice;
                  if(newSl > sl)
                  {
                     trade.PositionModify(ticket, newSl, tp);
                  }
               }

               //--- Trailing Stop
               if(InpUseTrailingStop && profitPoints >= InpTrailingStart)
               {
                  double newSl = currentPrice - InpTrailingStep * point;
                  if(newSl > sl)
                  {
                     trade.PositionModify(ticket, newSl, tp);
                  }
               }
            }
            else if(positionType == POSITION_TYPE_SELL)
            {
               double profitPoints = (openPrice - currentPrice) / point;

               //--- Break Even
               if(InpUseBreakEven && profitPoints >= InpBreakEvenTrigger)
               {
                  double newSl = openPrice;
                  if(newSl < sl || sl == 0)
                  {
                     trade.PositionModify(ticket, newSl, tp);
                  }
               }

               //--- Trailing Stop
               if(InpUseTrailingStop && profitPoints >= InpTrailingStart)
               {
                  double newSl = currentPrice + InpTrailingStep * point;
                  if(newSl < sl || sl == 0)
                  {
                     trade.PositionModify(ticket, newSl, tp);
                  }
               }
            }
         }
      }
   }
}
//+------------------------------------------------------------------+