
//+------------------------------------------------------------------+
//|                                                VWAP_Trend_EA.mq5|
//|                                    Generated by Senior MQL5 Dev  |
//|                                        Strategy: VWAP Slope Crossover |
//+------------------------------------------------------------------+
#property copyright "Senior MQL5 Developer"
#property link      "https://www.mql5.com"
#property version   "1.01"
#property strict

#include <Trade\Trade.mqh>

//--- Input Parameters
input group "=== Order Settings ==="
input double   InpLotSize        = 0.01;         // Lot size
input int      InpStopLoss       = 300;          // Stop Loss (points)
input int      InpTakeProfit     = 600;          // Take Profit (points)
input ulong    InpMagicNumber    = 202411;       // Magic Number
input int      InpSlippage       = 10;           // Slippage (points)
input int      InpMaxSpread      = 30;           // Max Spread (points)
input int      InpMaxPositions   = 1;            // Max Open Positions

input group "=== VWAP Settings ==="
input int      InpVWAPPeriod     = 20;           // VWAP Period (bars)
input ENUM_TIMEFRAMES InpVWAPTimeframe = PERIOD_CURRENT; // VWAP Timeframe

input group "=== Trade Management ==="
input bool     InpUseBreakEven   = true;         // Enable Break Even
input int      InpBreakEvenTrigger = 150;        // Break Even Trigger (points)
input int      InpBreakEvenLock  = 0;            // Break Even Lock (points from entry)
input bool     InpUseTrailing    = true;         // Enable Trailing Stop
input int      InpTrailingStart  = 200;          // Trailing Start (points)
input int      InpTrailingStep   = 50;           // Trailing Step (points)

//--- Global Variables
CTrade  trade;
datetime lastBarTime = 0;
MqlRates rates[];
double vwapBuffer[];
double vwapPreviousBuffer[];
double vwapCalculated[];

//+------------------------------------------------------------------+
//| Expert initialization function                                   |
//+------------------------------------------------------------------+
int OnInit()
  {
   //--- Set magic number and slippage
   trade.SetExpertMagicNumber(InpMagicNumber);
   trade.SetDeviationInPoints(InpSlippage);
   trade.SetTypeFillingBySymbol(_Symbol);

   //--- Initialize arrays
   ArraySetAsSeries(rates, true);
   ArraySetAsSeries(vwapBuffer, true);
   ArraySetAsSeries(vwapPreviousBuffer, true);
   ArraySetAsSeries(vwapCalculated, true);

   Print("VWAP Trend EA initialized successfully (using built-in VWAP calculation)");
   return(INIT_SUCCEEDED);
  }
//+------------------------------------------------------------------+
//| Expert deinitialization function                                 |
//+------------------------------------------------------------------+
void OnDeinit(const int reason)
  {
   Print("VWAP Trend EA deinitialized");
  }
//+------------------------------------------------------------------+
//| Expert tick function                                             |
//+------------------------------------------------------------------+
void OnTick()
  {
   //--- Check for new bar
   if(!IsNewBar())
      return;

   //--- Check spread
   if(!CheckSpread())
      return;

   //--- Check existing positions
   if(CountOpenPositions() >= InpMaxPositions)
      return;

   //--- Calculate VWAP values
   double currentVWAP, previousVWAP;
   if(!CalculateVWAP(currentVWAP, previousVWAP))
      return;

   //--- Get current price
   double ask = SymbolInfoDouble(_Symbol, SYMBOL_ASK);
   double bid = SymbolInfoDouble(_Symbol, SYMBOL_BID);

   //--- Check trading signals
   bool buySignal = false;
   bool sellSignal = false;

   //--- BUY: Price above VWAP and VWAP sloping up
   if(ask > currentVWAP && currentVWAP > previousVWAP)
      buySignal = true;

   //--- SELL: Price below VWAP and VWAP sloping down
   if(bid < currentVWAP && currentVWAP < previousVWAP)
      sellSignal = true;

   //--- Execute trades
   if(buySignal)
      OpenBuy();
   else if(sellSignal)
      OpenSell();

   //--- Manage open positions
   ManagePositions();
  }
//+------------------------------------------------------------------+
//| Check for new bar                                                |
//+------------------------------------------------------------------+
bool IsNewBar()
  {
   datetime currentBarTime = iTime(_Symbol, PERIOD_CURRENT, 0);
   if(currentBarTime != lastBarTime)
     {
      lastBarTime = currentBarTime;
      return true;
     }
   return false;
  }
//+------------------------------------------------------------------+
//| Check spread                                                     |
//+------------------------------------------------------------------+
bool CheckSpread()
  {
   long spread = SymbolInfoInteger(_Symbol, SYMBOL_SPREAD);
   if(spread > InpMaxSpread)
     {
      Print("Spread too high: ", spread, " points (Max: ", InpMaxSpread, ")");
      return false;
     }
   return true;
  }
//+------------------------------------------------------------------+
//| Count open positions with current magic number                   |
//+------------------------------------------------------------------+
int CountOpenPositions()
  {
   int count = 0;
   for(int i = PositionsTotal() - 1; i >= 0; i--)
     {
      ulong ticket = PositionGetTicket(i);
      if(ticket > 0)
        {
         if(PositionGetInteger(POSITION_MAGIC) == InpMagicNumber)
            count++;
        }
     }
   return count;
  }
//+------------------------------------------------------------------+
//| Calculate VWAP values (built-in calculation)                     |
//+------------------------------------------------------------------+
bool CalculateVWAP(double &currentVWAP, double &previousVWAP)
  {
   //--- Copy required bars
   int barsNeeded = InpVWAPPeriod + 1;
   if(CopyRates(_Symbol, InpVWAPTimeframe, 0, barsNeeded, rates) < barsNeeded)
     {
      Print("Failed to copy rates. Error: ", GetLastError());
      return false;
     }

   //--- Resize VWAP calculation array
   ArrayResize(vwapCalculated, barsNeeded);
   ArraySetAsSeries(vwapCalculated, true);

   //--- Calculate VWAP for each bar
   for(int i = barsNeeded - 2; i >= 0; i--)
     {
      double sumPriceVolume = 0;
      double sumVolume = 0;

      //--- Calculate VWAP using rolling window
      int startIndex = i;
      int endIndex = MathMin(i + InpVWAPPeriod, barsNeeded - 1);

      for(int j = startIndex; j < endIndex; j++)
        {
         double typicalPrice = (rates[j].high + rates[j].low + rates[j].close) / 3.0;
         double volume = (double)rates[j].tick_volume;
         
         sumPriceVolume += typicalPrice * volume;
         sumVolume += volume;
        }

      if(sumVolume > 0)
         vwapCalculated[i] = sumPriceVolume / sumVolume;
      else
         vwapCalculated[i] = rates[i].close;
     }

   //--- Set current and previous VWAP values
   currentVWAP = vwapCalculated[0];
   previousVWAP = vwapCalculated[1];

   //--- Validate values
   if(currentVWAP == 0 || previousVWAP == 0 || 
      currentVWAP == EMPTY_VALUE || previousVWAP == EMPTY_VALUE)
      return false;

   return true;
  }
//+------------------------------------------------------------------+
//| Open Buy position                                                |
//+------------------------------------------------------------------+
void OpenBuy()
  {
   double price = SymbolInfoDouble(_Symbol, SYMBOL_ASK);
   double sl = InpStopLoss > 0 ? price - InpStopLoss * _Point : 0;
   double tp = InpTakeProfit > 0 ? price + InpTakeProfit * _Point : 0;

   //--- Normalize prices
   price = NormalizeDouble(price, _Digits);
   sl = NormalizeDouble(sl, _Digits);
   tp = NormalizeDouble(tp, _Digits);

   if(trade.Buy(InpLotSize, _Symbol, price, sl, tp, "VWAP Trend Buy"))
     {
      Print("Buy order opened successfully. Price: ", price, ", SL: ", sl, ", TP: ", tp);
     }
   else
     {
      Print("Failed to open Buy order. Error: ", trade.ResultRetcode(), " - ", trade.ResultRetcodeDescription());
     }
  }
//+------------------------------------------------------------------+
//| Open Sell position                                               |
//+------------------------------------------------------------------+
void OpenSell()
  {
   double price = SymbolInfoDouble(_Symbol, SYMBOL_BID);
   double sl = InpStopLoss > 0 ? price + InpStopLoss * _Point : 0;
   double tp = InpTakeProfit > 0 ? price - InpTakeProfit * _Point : 0;

   //--- Normalize prices
   price = NormalizeDouble(price, _Digits);
   sl = NormalizeDouble(sl, _Digits);
   tp = NormalizeDouble(tp, _Digits);

   if(trade.Sell(InpLotSize, _Symbol, price, sl, tp, "VWAP Trend Sell"))
     {
      Print("Sell order opened successfully. Price: ", price, ", SL: ", sl, ", TP: ", tp);
     }
   else
     {
      Print("Failed to open Sell order. Error: ", trade.ResultRetcode(), " - ", trade.ResultRetcodeDescription());
     }
  }
//+------------------------------------------------------------------+
//| Manage open positions (Break Even & Trailing)                    |
//+------------------------------------------------------------------+
void ManagePositions()
  {
   for(int i = PositionsTotal() - 1; i >= 0; i--)
     {
      ulong ticket = PositionGetTicket(i);
      if(ticket > 0)
        {
         if(PositionGetInteger(POSITION_MAGIC) == InpMagicNumber && PositionGetString(POSITION_SYMBOL) == _Symbol)
           {
            //--- Break Even management
            if(InpUseBreakEven)
               ApplyBreakEven(ticket);

            //--- Trailing Stop management
            if(InpUseTrailing)
               ApplyTrailingStop(ticket);
           }
        }
     }
  }
//+------------------------------------------------------------------+
//| Apply Break Even logic                                           |
//+------------------------------------------------------------------+
void ApplyBreakEven(ulong ticket)
  {
   if(!PositionSelectByTicket(ticket))
      return;

   double openPrice = PositionGetDouble(POSITION_PRICE_OPEN);
   double currentSL = PositionGetDouble(POSITION_SL);
   double currentPrice = PositionGetDouble(POSITION_PRICE_CURRENT);
   long positionType = PositionGetInteger(POSITION_TYPE);

   //--- Calculate profit in points
   double profitPoints = 0;

   if(positionType == POSITION_TYPE_BUY)
     {
      profitPoints = (currentPrice - openPrice) / _Point;
      //--- Apply Break Even
      if(profitPoints >= InpBreakEvenTrigger)
        {
         double newSL = openPrice + InpBreakEvenLock * _Point;
         newSL = NormalizeDouble(newSL, _Digits);
         if(newSL > currentSL)
           {
            if(trade.PositionModify(ticket, newSL, PositionGetDouble(POSITION_TP)))
               Print("Break Even applied for Buy position #", ticket);
           }
        }
     }
   else if(positionType == POSITION_TYPE_SELL)
     {
      profitPoints = (openPrice - currentPrice) / _Point;
      //--- Apply Break Even
      if(profitPoints >= InpBreakEvenTrigger)
        {
         double newSL = openPrice - InpBreakEvenLock * _Point;
         newSL = NormalizeDouble(newSL, _Digits);
         if(newSL < currentSL || currentSL == 0)
           {
            if(trade.PositionModify(ticket, newSL, PositionGetDouble(POSITION_TP)))
               Print("Break Even applied for Sell position #", ticket);
           }
        }
     }
  }
//+------------------------------------------------------------------+
//| Apply Trailing Stop logic                                        |
//+------------------------------------------------------------------+
void ApplyTrailingStop(ulong ticket)
  {
   if(!PositionSelectByTicket(ticket))
      return;

   double openPrice = PositionGetDouble(POSITION_PRICE_OPEN);
   double currentSL = PositionGetDouble(POSITION_SL);
   double currentPrice = PositionGetDouble(POSITION_PRICE_CURRENT);
   long positionType = PositionGetInteger(POSITION_TYPE);

   if(positionType == POSITION_TYPE_BUY)
     {
      double profitPoints = (currentPrice - openPrice) / _Point;
      if(profitPoints >= InpTrailingStart)
        {
         double newSL = currentPrice - InpTrailingStep * _Point;
         newSL = NormalizeDouble(newSL, _Digits);
         if(newSL > currentSL)
           {
            if(trade.PositionModify(ticket, newSL, PositionGetDouble(POSITION_TP)))
               Print("Trailing Stop applied for Buy position #", ticket);
           }
        }
     }
   else if(positionType == POSITION_TYPE_SELL)
     {
      double profitPoints = (openPrice - currentPrice) / _Point;
      if(profitPoints >= InpTrailingStart)
        {
         double newSL = currentPrice + InpTrailingStep * _Point;
         newSL = NormalizeDouble(newSL, _Digits);
         if(newSL < currentSL || currentSL == 0)
           {
            if(trade.PositionModify(ticket, newSL, PositionGetDouble(POSITION_TP)))
               Print("Trailing Stop applied for Sell position #", ticket);
           }
        }
     }
  }
//+------------------------------------------------------------------+