//+------------------------------------------------------------------+
//|                                          DonchianBreakoutEA.mq5 |
//|                                      Generated by Senior MQL5 Dev |
//|                                                                  |
//+------------------------------------------------------------------+
#property copyright "Senior MQL5 Dev"
#property link      ""
#property version   "1.00"

#include <Trade\Trade.mqh>

//+------------------------------------------------------------------+
//| Input Parameters                                                 |
//+------------------------------------------------------------------+
input double   InpLotSize        = 0.01;     // Lot size
input int      InpStopLoss       = 300;      // Stop Loss (points)
input int      InpTakeProfit     = 600;      // Take Profit (points)
input ulong    InpMagicNumber    = 123456;   // Magic Number
input int      InpSlippage       = 10;       // Slippage (points)
input bool     InpUseBreakEven   = true;     // Enable Break Even
input int      InpBreakEvenPoint = 150;      // Break Even activation (points)
input bool     InpUseTrailing    = true;     // Enable Trailing Stop
input int      InpTrailingPoint  = 200;      // Trailing Stop activation (points)
input int      InpMaxSpread      = 30;       // Maximum allowed spread (points)
input int      InpDonchianPeriod = 20;       // Donchian Channel period

//+------------------------------------------------------------------+
//| Global variables                                                 |
//+------------------------------------------------------------------+
CTrade trade;
ulong  magicNumber;
double lotSize;
int    stopLossPoints;
int    takeProfitPoints;
int    slippagePoints;
bool   useBreakEven;
int    breakEvenPoint;
bool   useTrailing;
int    trailingPoint;
int    maxSpread;
int    donchianPeriod;

datetime lastBarTime;
double   donchianUpper;
double   donchianLower;
double   donchianMidline;

//+------------------------------------------------------------------+
//| Expert initialization function                                   |
//+------------------------------------------------------------------+
int OnInit()
{
   // Initialize trading parameters
   magicNumber      = InpMagicNumber;
   lotSize          = InpLotSize;
   stopLossPoints   = InpStopLoss;
   takeProfitPoints = InpTakeProfit;
   slippagePoints   = InpSlippage;
   useBreakEven     = InpUseBreakEven;
   breakEvenPoint   = InpBreakEvenPoint;
   useTrailing      = InpUseTrailing;
   trailingPoint    = InpTrailingPoint;
   maxSpread        = InpMaxSpread;
   donchianPeriod   = InpDonchianPeriod;
   
   // Set magic number for trade operations
   trade.SetExpertMagicNumber(magicNumber);
   
   // Initialize last bar time
   lastBarTime = iTime(Symbol(), PERIOD_CURRENT, 0);
   
   Print("EA initialized. Symbol: ", Symbol(), " Donchian Period: ", donchianPeriod);
   Print("Spread limit: ", maxSpread, " points");
   
   return(INIT_SUCCEEDED);
}

//+------------------------------------------------------------------+
//| Expert deinitialization function                                 |
//+------------------------------------------------------------------+
void OnDeinit(const int reason)
{
   // Nothing to clean up
}

//+------------------------------------------------------------------+
//| Expert tick function                                             |
//+------------------------------------------------------------------+
void OnTick()
{
   // New bar check
   if(!IsNewBar())
      return;
      
   // Update Donchian Channel values
   if(!UpdateDonchianChannel())
      return;
      
   // Check spread limit
   if(!CheckSpread())
      return;
      
   // Check if position already exists
   if(PositionExists())
      return;
      
   // Check account conditions
   if(!CheckAccount())
      return;
      
   // Generate and execute signals
   GenerateSignal();
   
   // Manage existing positions
   if(useBreakEven || useTrailing)
      ManagePositions();
}

//+------------------------------------------------------------------+
//| Check for new bar                                                |
//+------------------------------------------------------------------+
bool IsNewBar()
{
   datetime currentBarTime = iTime(Symbol(), PERIOD_CURRENT, 0);
   if(currentBarTime != lastBarTime)
   {
      lastBarTime = currentBarTime;
      return true;
   }
   return false;
}

//+------------------------------------------------------------------+
//| Update Donchian Channel values                                   |
//+------------------------------------------------------------------+
bool UpdateDonchianChannel()
{
   // Get high and low for the Donchian period
   MqlRates rates[];
   ArraySetAsSeries(rates, true);
   
   if(CopyRates(Symbol(), PERIOD_CURRENT, 0, donchianPeriod + 1, rates) < donchianPeriod + 1)
   {
      Print("Error copying rates data");
      return false;
   }
      
   // Calculate highest high and lowest low
   double highestHigh = rates[0].high;
   double lowestLow   = rates[0].low;
   
   for(int i = 1; i < donchianPeriod; i++)
   {
      if(rates[i].high > highestHigh)
         highestHigh = rates[i].high;
      if(rates[i].low < lowestLow)
         lowestLow = rates[i].low;
   }
   
   donchianUpper  = highestHigh;
   donchianLower  = lowestLow;
   donchianMidline = (donchianUpper + donchianLower) / 2.0;
   
   return true;
}

//+------------------------------------------------------------------+
//| Check spread limit                                               |
//+------------------------------------------------------------------+
bool CheckSpread()
{
   // For XAUUSD, spread is typically in points (10 = 1.0 pip)
   // Get current spread in points
   int spread = (int)SymbolInfoInteger(Symbol(), SYMBOL_SPREAD);
   
   // Log spread for debugging (only every 10 bars to avoid spam)
   static int barCounter = 0;
   barCounter++;
   if(barCounter % 10 == 0)
      Print("Current spread: ", spread, " points (Limit: ", maxSpread, ")");
   
   if(spread > maxSpread)
   {
      Print("Spread too high: ", spread, " > ", maxSpread, " - Waiting for next bar");
      return false;
   }
   return true;
}

//+------------------------------------------------------------------+
//| Check if position exists                                         |
//+------------------------------------------------------------------+
bool PositionExists()
{
   int total = PositionsTotal();
   for(int i = 0; i < total; i++)
   {
      ulong ticket = PositionGetTicket(i);
      if(PositionSelectByTicket(ticket))
      {
         if(PositionGetInteger(POSITION_MAGIC) == (long)magicNumber)
            return true;
      }
   }
   return false;
}

//+------------------------------------------------------------------+
//| Check account conditions                                         |
//+------------------------------------------------------------------+
bool CheckAccount()
{
   // Check if account is trading allowed
   if(!AccountInfoInteger(ACCOUNT_TRADE_ALLOWED))
   {
      Print("Trading not allowed on account");
      return false;
   }
      
   // Check free margin
   double marginFree = AccountInfoDouble(ACCOUNT_MARGIN_FREE);
   double marginRequired = SymbolInfoDouble(Symbol(), SYMBOL_MARGIN_INITIAL) * lotSize;
   
   if(marginFree < marginRequired * 2.0) // 2x margin required for safety
   {
      Print("Not enough margin. Free: ", DoubleToString(marginFree, 2), 
            " Required: ", DoubleToString(marginRequired, 2));
      return false;
   }
   
   return true;
}

//+------------------------------------------------------------------+
//| Generate trading signals                                        |
//+------------------------------------------------------------------+
void GenerateSignal()
{
   // Get current bid/ask prices
   double bid = SymbolInfoDouble(Symbol(), SYMBOL_BID);
   double ask = SymbolInfoDouble(Symbol(), SYMBOL_ASK);
   double point = SymbolInfoDouble(Symbol(), SYMBOL_POINT);
   
   // Log Donchian levels
   Print("Donchian - Upper: ", DoubleToString(donchianUpper, _Digits), 
         " Midline: ", DoubleToString(donchianMidline, _Digits), 
         " Lower: ", DoubleToString(donchianLower, _Digits));
   Print("Price - Ask: ", DoubleToString(ask, _Digits), 
         " Bid: ", DoubleToString(bid, _Digits));
   
   // Calculate SL and TP in price terms
   double slPoints = stopLossPoints * point;
   double tpPoints = takeProfitPoints * point;
   
   // BUY condition: price above midline
   if(ask > donchianMidline)
   {
      Print("BUY Signal: Ask (", DoubleToString(ask, _Digits), 
            ") > Midline (", DoubleToString(donchianMidline, _Digits), ")");
      
      double sl = ask - slPoints;
      double tp = ask + tpPoints;
      
      // Ensure SL and TP are within valid range
      sl = NormalizeDouble(sl, _Digits);
      tp = NormalizeDouble(tp, _Digits);
      
      // Execute BUY order
      if(trade.Buy(lotSize, Symbol(), ask, sl, tp, "Donchian Breakout BUY"))
      {
         Print("BUY order opened successfully. Ticket: ", trade.ResultDeal());
         Print("Entry: ", DoubleToString(ask, _Digits), 
               " SL: ", DoubleToString(sl, _Digits), 
               " TP: ", DoubleToString(tp, _Digits));
      }
      else
      {
         Print("Error opening BUY order: ", trade.ResultRetcodeDescription(), 
               " (", trade.ResultRetcode(), ")");
      }
   }
   // SELL condition: price below midline
   else if(bid < donchianMidline)
   {
      Print("SELL Signal: Bid (", DoubleToString(bid, _Digits), 
            ") < Midline (", DoubleToString(donchianMidline, _Digits), ")");
      
      double sl = bid + slPoints;
      double tp = bid - tpPoints;
      
      // Ensure SL and TP are within valid range
      sl = NormalizeDouble(sl, _Digits);
      tp = NormalizeDouble(tp, _Digits);
      
      // Execute SELL order
      if(trade.Sell(lotSize, Symbol(), bid, sl, tp, "Donchian Breakout SELL"))
      {
         Print("SELL order opened successfully. Ticket: ", trade.ResultDeal());
         Print("Entry: ", DoubleToString(bid, _Digits), 
               " SL: ", DoubleToString(sl, _Digits), 
               " TP: ", DoubleToString(tp, _Digits));
      }
      else
      {
         Print("Error opening SELL order: ", trade.ResultRetcodeDescription(), 
               " (", trade.ResultRetcode(), ")");
      }
   }
   else
   {
      Print("No signal: Price is at midline level");
   }
}

//+------------------------------------------------------------------+
//| Manage existing positions                                        |
//+------------------------------------------------------------------+
void ManagePositions()
{
   int total = PositionsTotal();
   for(int i = 0; i < total; i++)
   {
      ulong ticket = PositionGetTicket(i);
      if(PositionSelectByTicket(ticket))
      {
         if(PositionGetInteger(POSITION_MAGIC) != (long)magicNumber)
            continue;
            
         double openPrice   = PositionGetDouble(POSITION_PRICE_OPEN);
         double currentSL   = PositionGetDouble(POSITION_SL);
         double currentTP   = PositionGetDouble(POSITION_TP);
         ENUM_POSITION_TYPE type = (ENUM_POSITION_TYPE)PositionGetInteger(POSITION_TYPE);
         
         double currentPrice = (type == POSITION_TYPE_BUY) ? SymbolInfoDouble(Symbol(), SYMBOL_BID) : SymbolInfoDouble(Symbol(), SYMBOL_ASK);
         double point = SymbolInfoDouble(Symbol(), SYMBOL_POINT);
         
         // Break Even logic
         if(useBreakEven)
         {
            if(type == POSITION_TYPE_BUY)
            {
               double profit = (currentPrice - openPrice) / point;
               if(profit >= breakEvenPoint && (currentSL < openPrice || currentSL == 0))
               {
                  if(trade.PositionModify(ticket, openPrice, currentTP))
                  {
                     Print("Break Even triggered for BUY position. Ticket: ", ticket);
                     Print("SL moved to: ", DoubleToString(openPrice, _Digits));
                  }
               }
            }
            else if(type == POSITION_TYPE_SELL)
            {
               double profit = (openPrice - currentPrice) / point;
               if(profit >= breakEvenPoint && (currentSL > openPrice || currentSL == 0))
               {
                  if(trade.PositionModify(ticket, openPrice, currentTP))
                  {
                     Print("Break Even triggered for SELL position. Ticket: ", ticket);
                     Print("SL moved to: ", DoubleToString(openPrice, _Digits));
                  }
               }
            }
         }
         
         // Trailing Stop logic
         if(useTrailing)
         {
            if(type == POSITION_TYPE_BUY)
            {
               double profit = (currentPrice - openPrice) / point;
               if(profit >= trailingPoint)
               {
                  double newSL = currentPrice - trailingPoint * point;
                  newSL = NormalizeDouble(newSL, _Digits);
                  
                  if(newSL > currentSL || currentSL == 0)
                  {
                     if(trade.PositionModify(ticket, newSL, currentTP))
                     {
                        Print("Trailing Stop updated for BUY position. Ticket: ", ticket);
                        Print("New SL: ", DoubleToString(newSL, _Digits));
                     }
                  }
               }
            }
            else if(type == POSITION_TYPE_SELL)
            {
               double profit = (openPrice - currentPrice) / point;
               if(profit >= trailingPoint)
               {
                  double newSL = currentPrice + trailingPoint * point;
                  newSL = NormalizeDouble(newSL, _Digits);
                  
                  if(newSL < currentSL || currentSL == 0)
                  {
                     if(trade.PositionModify(ticket, newSL, currentTP))
                     {
                        Print("Trailing Stop updated for SELL position. Ticket: ", ticket);
                        Print("New SL: ", DoubleToString(newSL, _Digits));
                     }
                  }
               }
            }
         }
      }
   }
}
//+------------------------------------------------------------------+