//+------------------------------------------------------------------+
//|                                                   EMA5_EMA20.mq5 |
//|                                    Generated by Senior MQL5 Dev |
//|                                             https://www.mql5.com |
//+------------------------------------------------------------------+
#property copyright "Senior MQL5 Developer"
#property link      "https://www.mql5.com"
#property version   "1.00"
#include <Trade\Trade.mqh>

//--- input parameters
input double InpLotSize = 0.01;                 // Lot size
input int    InpStopLoss = 300;                 // Stop Loss (points)
input int    InpTakeProfit = 600;               // Take Profit (points)
input ulong  InpMagicNumber = 123456;           // Magic Number
input int    InpSlippage = 10;                  // Slippage (points)
input bool   InpUseBreakEven = true;            // Use Break Even
input bool   InpUseTrailingStop = true;         // Use Trailing Stop
input int    InpBreakEvenTrigger = 150;         // Break Even trigger (points)
input int    InpTrailingStart = 200;            // Trailing start (points)
input int    InpTrailingStop = 200;             // Trailing distance (points)
input int    InpMaxSpread = 30;                 // Max spread (points)
input int    InpMaxOrders = 1;                  // Max open orders
input int    InpEmaFast = 21;                    // Fast EMA period
input int    InpEmaSlow = 55;                   // Slow EMA period

//--- global variables
CTrade trade;
int hEmaFast = INVALID_HANDLE;
int hEmaSlow = INVALID_HANDLE;
datetime lastBarTime = 0;
//+------------------------------------------------------------------+
//| Expert initialization function                                   |
//+------------------------------------------------------------------+
int OnInit()
{
   // Validate inputs
   if(InpLotSize <= 0)
   {
      Print("Lot size must be greater than 0");
      return INIT_PARAMETERS_INCORRECT;
   }
   if(InpStopLoss <= 0 || InpTakeProfit <= 0)
   {
      Print("Stop Loss and Take Profit must be greater than 0");
      return INIT_PARAMETERS_INCORRECT;
   }
   if(InpEmaFast <= 0 || InpEmaSlow <= 0 || InpEmaFast >= InpEmaSlow)
   {
      Print("Invalid EMA periods");
      return INIT_PARAMETERS_INCORRECT;
   }
   
   trade.SetExpertMagicNumber(InpMagicNumber);
   trade.SetDeviationInPoints(InpSlippage);
   
   // Create indicator handles
   hEmaFast = iMA(_Symbol, PERIOD_CURRENT, InpEmaFast, 0, MODE_EMA, PRICE_CLOSE);
   hEmaSlow = iMA(_Symbol, PERIOD_CURRENT, InpEmaSlow, 0, MODE_EMA, PRICE_CLOSE);
   
   if(hEmaFast == INVALID_HANDLE || hEmaSlow == INVALID_HANDLE)
   {
      Print("Failed to create EMA indicator handles. Error: ", GetLastError());
      return INIT_FAILED;
   }
   
   return INIT_SUCCEEDED;
}
//+------------------------------------------------------------------+
//| Expert deinitialization function                                 |
//+------------------------------------------------------------------+
void OnDeinit(const int reason)
{
   if(hEmaFast != INVALID_HANDLE)
      IndicatorRelease(hEmaFast);
   if(hEmaSlow != INVALID_HANDLE)
      IndicatorRelease(hEmaSlow);
}
//+------------------------------------------------------------------+
//| Expert tick function                                             |
//+------------------------------------------------------------------+
void OnTick()
{
   // Manage open positions (break even and trailing) on every tick
   ManageOpenPositions();
   
   // Check spread
   if(!IsSpreadAcceptable())
      return;
   
   // Check number of open positions
   if(CountOpenPositions() >= InpMaxOrders)
      return;
   
   // New bar check
   if(!IsNewBar())
      return;
   
   // Get signals
   bool buySignal = false, sellSignal = false;
   if(!GetSignal(buySignal, sellSignal))
      return;
   
   // Open positions based on signal
   if(buySignal)
      OpenBuy();
   else if(sellSignal)
      OpenSell();
}
//+------------------------------------------------------------------+
//| Check if current spread is within allowed limit                   |
//+------------------------------------------------------------------+
bool IsSpreadAcceptable()
{
   long spread = SymbolInfoInteger(_Symbol, SYMBOL_SPREAD);
   if(spread > InpMaxSpread)
   {
      Print("Spread too high: ", spread, " points (max ", InpMaxSpread, ")");
      return false;
   }
   return true;
}
//+------------------------------------------------------------------+
//| Count open positions with this EA's magic number                 |
//+------------------------------------------------------------------+
int CountOpenPositions()
{
   int count = 0;
   for(int i = PositionsTotal() - 1; i >= 0; i--)
   {
      ulong ticket = PositionGetTicket(i);
      if(ticket > 0)
      {
         if(PositionGetString(POSITION_SYMBOL) == _Symbol &&
            PositionGetInteger(POSITION_MAGIC) == InpMagicNumber)
            count++;
      }
   }
   return count;
}
//+------------------------------------------------------------------+
//| Check if a new bar has formed                                    |
//+------------------------------------------------------------------+
bool IsNewBar()
{
   datetime currentBarTime = iTime(_Symbol, PERIOD_CURRENT, 0);
   if(currentBarTime == lastBarTime)
      return false;
   lastBarTime = currentBarTime;
   return true;
}
//+------------------------------------------------------------------+
//| Get trading signals based on EMA5/EMA20 strategy                 |
//+------------------------------------------------------------------+
bool GetSignal(bool &buySignal, bool &sellSignal)
{
   buySignal = false;
   sellSignal = false;
   
   // Copy EMA values (2 values: current and last closed)
   double emaFast[2], emaSlow[2];
   if(CopyBuffer(hEmaFast, 0, 0, 2, emaFast) < 2)
   {
      Print("Failed to copy fast EMA buffer");
      return false;
   }
   if(CopyBuffer(hEmaSlow, 0, 0, 2, emaSlow) < 2)
   {
      Print("Failed to copy slow EMA buffer");
      return false;
   }
   
   // Get OHLC of the last closed bar (bar index 1)
   double close1 = iClose(_Symbol, PERIOD_CURRENT, 1);
   double open1 = iOpen(_Symbol, PERIOD_CURRENT, 1);
   double low1 = iLow(_Symbol, PERIOD_CURRENT, 1);
   double high1 = iHigh(_Symbol, PERIOD_CURRENT, 1);
   
   double emaFast1 = emaFast[1];
   double emaSlow1 = emaSlow[1];
   
   // Uptrend: EMA5 > EMA20
   if(emaFast1 > emaSlow1)
   {
      // Buy signal: price pulled back to EMA20 and closed bullish
      if(low1 <= emaSlow1 && close1 > open1 && close1 > emaSlow1)
         buySignal = true;
   }
   // Downtrend: EMA5 < EMA20
   else if(emaFast1 < emaSlow1)
   {
      // Sell signal: price pulled back to EMA20 and closed bearish
      if(high1 >= emaSlow1 && close1 < open1 && close1 < emaSlow1)
         sellSignal = true;
   }
   
   return true;
}
//+------------------------------------------------------------------+
//| Open buy position                                                |
//+------------------------------------------------------------------+
void OpenBuy()
{
   double price = SymbolInfoDouble(_Symbol, SYMBOL_ASK);
   double sl = price - InpStopLoss * _Point;
   double tp = price + InpTakeProfit * _Point;
   
   if(!trade.Buy(InpLotSize, _Symbol, price, sl, tp, "EMA5_EMA20 BUY"))
   {
      Print("Buy order failed. Error: ", trade.ResultRetcode(), " - ", trade.ResultRetcodeDescription());
   }
}
//+------------------------------------------------------------------+
//| Open sell position                                               |
//+------------------------------------------------------------------+
void OpenSell()
{
   double price = SymbolInfoDouble(_Symbol, SYMBOL_BID);
   double sl = price + InpStopLoss * _Point;
   double tp = price - InpTakeProfit * _Point;
   
   if(!trade.Sell(InpLotSize, _Symbol, price, sl, tp, "EMA5_EMA20 SELL"))
   {
      Print("Sell order failed. Error: ", trade.ResultRetcode(), " - ", trade.ResultRetcodeDescription());
   }
}
//+------------------------------------------------------------------+
//| Manage open positions: break even and trailing stop               |
//+------------------------------------------------------------------+
void ManageOpenPositions()
{
   for(int i = PositionsTotal() - 1; i >= 0; i--)
   {
      ulong ticket = PositionGetTicket(i);
      if(ticket <= 0)
         continue;
      
      if(PositionGetString(POSITION_SYMBOL) != _Symbol)
         continue;
      if(PositionGetInteger(POSITION_MAGIC) != InpMagicNumber)
         continue;
      
      long positionType = PositionGetInteger(POSITION_TYPE);
      if(positionType != POSITION_TYPE_BUY && positionType != POSITION_TYPE_SELL)
         continue;
      
      double openPrice = PositionGetDouble(POSITION_PRICE_OPEN);
      double currentSL = PositionGetDouble(POSITION_SL);
      double currentTP = PositionGetDouble(POSITION_TP);
      double bid = SymbolInfoDouble(_Symbol, SYMBOL_BID);
      double ask = SymbolInfoDouble(_Symbol, SYMBOL_ASK);
      
      double profitPoints = 0;
      if(positionType == POSITION_TYPE_BUY)
         profitPoints = (bid - openPrice) / _Point;
      else if(positionType == POSITION_TYPE_SELL)
         profitPoints = (openPrice - ask) / _Point;
      
      // Break Even
      if(InpUseBreakEven && InpBreakEvenTrigger > 0)
      {
         if(profitPoints >= InpBreakEvenTrigger)
         {
            bool shouldUpdate = false;
            double newSL = 0;
            if(positionType == POSITION_TYPE_BUY)
            {
               newSL = openPrice;
               if(currentSL < newSL) // only move SL up
                  shouldUpdate = true;
            }
            else if(positionType == POSITION_TYPE_SELL)
            {
               newSL = openPrice;
               if(currentSL > newSL) // only move SL down
                  shouldUpdate = true;
            }
            if(shouldUpdate)
            {
               if(!trade.PositionModify(ticket, newSL, currentTP))
                  Print("Failed to modify position (Break Even) for ticket ", ticket, ". Error: ", trade.ResultRetcode(), " - ", trade.ResultRetcodeDescription());
               else
                  currentSL = newSL; // assume success to avoid conflicting trailing update
            }
         }
      }
      
      // Trailing Stop
      if(InpUseTrailingStop && InpTrailingStart > 0 && InpTrailingStop > 0)
      {
         if(profitPoints >= InpTrailingStart)
         {
            double newSL = 0;
            bool shouldUpdate = false;
            if(positionType == POSITION_TYPE_BUY)
            {
               newSL = bid - InpTrailingStop * _Point;
               if(currentSL < newSL) // only move SL up
                  shouldUpdate = true;
            }
            else if(positionType == POSITION_TYPE_SELL)
            {
               newSL = ask + InpTrailingStop * _Point;
               if(currentSL > newSL) // only move SL down
                  shouldUpdate = true;
            }
            if(shouldUpdate)
            {
               if(!trade.PositionModify(ticket, newSL, currentTP))
                  Print("Failed to modify position (Trailing) for ticket ", ticket, ". Error: ", trade.ResultRetcode(), " - ", trade.ResultRetcodeDescription());
            }
         }
      }
   }
}
//+------------------------------------------------------------------+
