#property strict
#include <Trade\Trade.mqh>
input double InpLotSize=0.01; input int InpStopLoss=300; input int InpTakeProfit=600; input ulong InpMagicNumber=123461; input int InpSlippage=10;
input group "Break Even & Trailing Stop"
input bool InpUseBreakEven=true; input int InpBreakEvenStart=150; input int InpBreakEvenOffset=0; input bool InpUseTrailingStop=true; input int InpTrailingStart=200; input int InpTrailingDistance=200; input int InpMaxSpreadPoints=30;
input int InpSessionStartHour=0; input int InpSessionEndHour=8;
CTrade trade;datetime g_bar=0;
bool NB(){datetime t=iTime(_Symbol,_Period,0);if(t==0||t==g_bar)return false;g_bar=t;return true;} bool TA(){return MQLInfoInteger(MQL_TRADE_ALLOWED)&&TerminalInfoInteger(TERMINAL_TRADE_ALLOWED)&&AccountInfoInteger(ACCOUNT_TRADE_ALLOWED);} bool SP(){MqlTick t;if(!SymbolInfoTick(_Symbol,t))return false;return(t.ask-t.bid)/_Point<=InpMaxSpreadPoints;} bool HP(){for(int i=PositionsTotal()-1;i>=0;--i){ulong x=PositionGetTicket(i);if(x&&PositionSelectByTicket(x)&&PositionGetString(POSITION_SYMBOL)==_Symbol&&(ulong)PositionGetInteger(POSITION_MAGIC)==InpMagicNumber)return true;}return false;} double P(double x){return NormalizeDouble(x,(int)SymbolInfoInteger(_Symbol,SYMBOL_DIGITS));} bool V(ENUM_ORDER_TYPE y,double s,double q){MqlTick t;if(!SymbolInfoTick(_Symbol,t))return false;double d=(int)SymbolInfoInteger(_Symbol,SYMBOL_TRADE_STOPS_LEVEL)*_Point;return y==ORDER_TYPE_BUY?(t.bid-s>=d&&q-t.bid>=d):(s-t.ask>=d&&t.ask-q>=d);}
void MP(){for(int i=PositionsTotal()-1;i>=0;--i){ulong x=PositionGetTicket(i);if(!x||!PositionSelectByTicket(x)||PositionGetString(POSITION_SYMBOL)!=_Symbol||(ulong)PositionGetInteger(POSITION_MAGIC)!=InpMagicNumber)continue;ENUM_POSITION_TYPE y=(ENUM_POSITION_TYPE)PositionGetInteger(POSITION_TYPE);double o=PositionGetDouble(POSITION_PRICE_OPEN),c=y==POSITION_TYPE_BUY?SymbolInfoDouble(_Symbol,SYMBOL_BID):SymbolInfoDouble(_Symbol,SYMBOL_ASK),s=PositionGetDouble(POSITION_SL),q=PositionGetDouble(POSITION_TP),p=y==POSITION_TYPE_BUY?(c-o)/_Point:(o-c)/_Point,n=s;bool m=false;if(InpUseBreakEven&&p>=InpBreakEvenStart){double b=P(y==POSITION_TYPE_BUY?o+InpBreakEvenOffset*_Point:o-InpBreakEvenOffset*_Point);if((y==POSITION_TYPE_BUY&&(s==0||b>s))||(y==POSITION_TYPE_SELL&&(s==0||b<s))){n=b;m=true;}}if(InpUseTrailingStop&&p>=InpTrailingStart){double z=P(y==POSITION_TYPE_BUY?c-InpTrailingDistance*_Point:c+InpTrailingDistance*_Point);if((y==POSITION_TYPE_BUY&&(n==0||z>n))||(y==POSITION_TYPE_SELL&&(n==0||z<n))){n=z;m=true;}}if(m&&((y==POSITION_TYPE_BUY&&n<c)||(y==POSITION_TYPE_SELL&&n>c))&&!trade.PositionModify(x,n,q))Print("PositionModify failed. Retcode=",trade.ResultRetcode());}}
bool OB(){MqlTick t;if(!SymbolInfoTick(_Symbol,t))return false;double s=P(t.ask-InpStopLoss*_Point),q=P(t.ask+InpTakeProfit*_Point);if(!V(ORDER_TYPE_BUY,s,q))return false;if(!trade.Buy(InpLotSize,_Symbol,0,s,q,"EA-106 BUY")){Print("Buy failed. Retcode=",trade.ResultRetcode());return false;}return true;} bool OS(){MqlTick t;if(!SymbolInfoTick(_Symbol,t))return false;double s=P(t.bid+InpStopLoss*_Point),q=P(t.bid-InpTakeProfit*_Point);if(!V(ORDER_TYPE_SELL,s,q))return false;if(!trade.Sell(InpLotSize,_Symbol,0,s,q,"EA-106 SELL")){Print("Sell failed. Retcode=",trade.ResultRetcode());return false;}return true;}
int OnInit(){trade.SetExpertMagicNumber(InpMagicNumber);trade.SetDeviationInPoints(InpSlippage);return INIT_SUCCEEDED;} void OnDeinit(const int reason){}
void OnTick(){MP();if(!TA()||!NB()||HP()||!SP())return;MqlDateTime d;TimeToStruct(iTime(_Symbol,_Period,1),d);if(d.hour<InpSessionEndHour||d.hour>=InpSessionEndHour+12)return;d.hour=InpSessionStartHour;d.min=0;d.sec=0;datetime start=StructToTime(d),end=start+InpSessionEndHour*3600;MqlRates r[];int n=CopyRates(_Symbol,_Period,start,end,r);if(n<2)return;double sh=-DBL_MAX,sl=DBL_MAX;for(int i=0;i<n;i++){if(r[i].high>sh)sh=r[i].high;if(r[i].low<sl)sl=r[i].low;}double h=iHigh(_Symbol,_Period,1),l=iLow(_Symbol,_Period,1),c=iClose(_Symbol,_Period,1);if(h>sh&&c<sh)OS();else if(l<sl&&c>sl)OB();}
