
//+------------------------------------------------------------------+
//|                                                  TrendTwoCandles.mq5 |
//|                                    Generated by Senior MQL5 Dev |
//+------------------------------------------------------------------+
#property copyright "Generated by Senior MQL5 Dev"
#property link      ""
#property version   "1.00"

#include <Trade\Trade.mqh>

//--- Input Parameters
input double   InpLotSize        = 0.01;      // Lot Size
input int      InpStopLoss       = 300;       // Stop Loss (points)
input int      InpTakeProfit     = 600;       // Take Profit (points)
input ulong    InpMagicNumber    = 123456;    // Magic Number
input int      InpSlippage       = 10;        // Slippage (points)
input int      InpMaxSpread      = 30;        // Maximum Spread (points)

//--- Break Even Parameters
input bool     InpUseBreakEven   = true;      // Enable Break Even
input int      InpBreakEvenStart = 150;       // Break Even Trigger (points profit)
input int      InpBreakEvenShift = 10;        // Break Even Shift (points above open)

//--- Trailing Stop Parameters
input bool     InpUseTrailing    = true;      // Enable Trailing Stop
input int      InpTrailingStart  = 200;       // Trailing Trigger (points profit)
input int      InpTrailingStep   = 50;        // Trailing Step (points)

//--- Trend Filter Parameters
input int      InpFastMA         = 20;        // Fast MA Period
input int      InpSlowMA         = 50;        // Slow MA Period

//--- Global Variables
CTrade  trade;
int     hFastMA;
int     hSlowMA;
datetime lastBarTime = 0;

//+------------------------------------------------------------------+
//| Expert initialization function                                   |
//+------------------------------------------------------------------+
int OnInit()
{
   //--- Validate inputs
   if(InpLotSize <= 0)
   {
      Print("Invalid Lot Size");
      return(INIT_PARAMETERS_INCORRECT);
   }
   if(InpStopLoss <= 0 || InpTakeProfit <= 0)
   {
      Print("Invalid SL/TP");
      return(INIT_PARAMETERS_INCORRECT);
   }
   if(InpFastMA >= InpSlowMA)
   {
      Print("Fast MA must be less than Slow MA");
      return(INIT_PARAMETERS_INCORRECT);
   }

   //--- Initialize indicators
   hFastMA = iMA(_Symbol, _Period, InpFastMA, 0, MODE_SMA, PRICE_CLOSE);
   hSlowMA = iMA(_Symbol, _Period, InpSlowMA, 0, MODE_SMA, PRICE_CLOSE);

   if(hFastMA == INVALID_HANDLE || hSlowMA == INVALID_HANDLE)
   {
      Print("Failed to create indicator handles");
      return(INIT_FAILED);
   }

   //--- Configure trade
   trade.SetExpertMagicNumber(InpMagicNumber);
   trade.SetDeviationInPoints(InpSlippage);
   trade.SetAsyncMode(false);

   lastBarTime = 0;

   Print("EA initialized successfully");
   return(INIT_SUCCEEDED);
}

//+------------------------------------------------------------------+
//| Expert deinitialization function                                 |
//+------------------------------------------------------------------+
void OnDeinit(const int reason)
{
   //--- Release indicator handles
   if(hFastMA != INVALID_HANDLE)
      IndicatorRelease(hFastMA);
   if(hSlowMA != INVALID_HANDLE)
      IndicatorRelease(hSlowMA);

   Print("EA deinitialized");
}

//+------------------------------------------------------------------+
//| Check if new bar has formed                                      |
//+------------------------------------------------------------------+
bool IsNewBar()
{
   datetime currentBarTime = iTime(_Symbol, _Period, 0);
   if(currentBarTime != lastBarTime)
   {
      lastBarTime = currentBarTime;
      return(true);
   }
   return(false);
}

//+------------------------------------------------------------------+
//| Count open positions with this Magic Number                      |
//+------------------------------------------------------------------+
int CountOpenPositions()
{
   int count = 0;
   for(int i = PositionsTotal() - 1; i >= 0; i--)
   {
      ulong ticket = PositionGetTicket(i);
      if(ticket > 0)
      {
         if(PositionGetString(POSITION_SYMBOL) == _Symbol &&
            PositionGetInteger(POSITION_MAGIC) == InpMagicNumber)
         {
            count++;
         }
      }
   }
   return(count);
}

//+------------------------------------------------------------------+
//| Check current spread                                             |
//+------------------------------------------------------------------+
bool IsSpreadValid()
{
   double spread = (SymbolInfoDouble(_Symbol, SYMBOL_ASK) - 
                    SymbolInfoDouble(_Symbol, SYMBOL_BID)) / _Point;
   return(spread <= InpMaxSpread);
}

//+------------------------------------------------------------------+
//| Get trend direction based on MA crossover                        |
//+------------------------------------------------------------------+
int GetTrendDirection()
{
   double fastMA[1], slowMA[1];
   
   if(CopyBuffer(hFastMA, 0, 0, 1, fastMA) != 1)
      return(0);
   if(CopyBuffer(hSlowMA, 0, 0, 1, slowMA) != 1)
      return(0);
   
   if(fastMA[0] > slowMA[0])
      return(1);  // Uptrend
   else if(fastMA[0] < slowMA[0])
      return(-1); // Downtrend
   else
      return(0);  // No trend
}

//+------------------------------------------------------------------+
//| Check for two consecutive candles in trend direction             |
//+------------------------------------------------------------------+
bool HasTwoConsecutiveCandles(int trendDirection)
{
   if(trendDirection == 0)
      return(false);
   
   // Get last 3 candles (current bar is incomplete, check closed candles)
   MqlRates candles[3];
   if(CopyRates(_Symbol, _Period, 1, 3, candles) != 3)
      return(false);
   
   // Check last two closed candles
   for(int i = 1; i < 3; i++)
   {
      if(trendDirection == 1) // Uptrend - expect bullish candles
      {
         if(candles[i].close <= candles[i].open)
            return(false);
      }
      else if(trendDirection == -1) // Downtrend - expect bearish candles
      {
         if(candles[i].close >= candles[i].open)
            return(false);
      }
   }
   
   return(true);
}

//+------------------------------------------------------------------+
//| Open buy position                                                |
//+------------------------------------------------------------------+
bool OpenBuyPosition()
{
   double price = SymbolInfoDouble(_Symbol, SYMBOL_ASK);
   double sl = price - InpStopLoss * _Point;
   double tp = price + InpTakeProfit * _Point;
   
   if(trade.Buy(InpLotSize, _Symbol, price, sl, tp, "TrendTwoCandles Buy"))
   {
      Print("Buy order opened successfully. Ticket: ", trade.ResultOrder());
      return(true);
   }
   else
   {
      Print("Failed to open Buy order. Error: ", trade.ResultRetcode());
      return(false);
   }
}

//+------------------------------------------------------------------+
//| Open sell position                                               |
//+------------------------------------------------------------------+
bool OpenSellPosition()
{
   double price = SymbolInfoDouble(_Symbol, SYMBOL_BID);
   double sl = price + InpStopLoss * _Point;
   double tp = price - InpTakeProfit * _Point;
   
   if(trade.Sell(InpLotSize, _Symbol, price, sl, tp, "TrendTwoCandles Sell"))
   {
      Print("Sell order opened successfully. Ticket: ", trade.ResultOrder());
      return(true);
   }
   else
   {
      Print("Failed to open Sell order. Error: ", trade.ResultRetcode());
      return(false);
   }
}

//+------------------------------------------------------------------+
//| Manage Break Even                                                |
//+------------------------------------------------------------------+
void ManageBreakEven()
{
   if(!InpUseBreakEven)
      return;
   
   for(int i = PositionsTotal() - 1; i >= 0; i--)
   {
      ulong ticket = PositionGetTicket(i);
      if(ticket > 0)
      {
         if(PositionGetString(POSITION_SYMBOL) == _Symbol &&
            PositionGetInteger(POSITION_MAGIC) == InpMagicNumber)
         {
            double currentPrice = PositionGetDouble(POSITION_PRICE_CURRENT);
            double openPrice = PositionGetDouble(POSITION_PRICE_OPEN);
            double currentSL = PositionGetDouble(POSITION_SL);
            
            if(PositionGetInteger(POSITION_TYPE) == POSITION_TYPE_BUY)
            {
               double profitPoints = (currentPrice - openPrice) / _Point;
               
               if(profitPoints >= InpBreakEvenStart)
               {
                  double newSL = openPrice + InpBreakEvenShift * _Point;
                  if(newSL > currentSL)
                  {
                     trade.PositionModify(ticket, newSL, PositionGetDouble(POSITION_TP));
                  }
               }
            }
            else if(PositionGetInteger(POSITION_TYPE) == POSITION_TYPE_SELL)
            {
               double profitPoints = (openPrice - currentPrice) / _Point;
               
               if(profitPoints >= InpBreakEvenStart)
               {
                  double newSL = openPrice - InpBreakEvenShift * _Point;
                  if(newSL < currentSL)
                  {
                     trade.PositionModify(ticket, newSL, PositionGetDouble(POSITION_TP));
                  }
               }
            }
         }
      }
   }
}

//+------------------------------------------------------------------+
//| Manage Trailing Stop                                             |
//+------------------------------------------------------------------+
void ManageTrailingStop()
{
   if(!InpUseTrailing)
      return;
   
   for(int i = PositionsTotal() - 1; i >= 0; i--)
   {
      ulong ticket = PositionGetTicket(i);
      if(ticket > 0)
      {
         if(PositionGetString(POSITION_SYMBOL) == _Symbol &&
            PositionGetInteger(POSITION_MAGIC) == InpMagicNumber)
         {
            double currentPrice = PositionGetDouble(POSITION_PRICE_CURRENT);
            double openPrice = PositionGetDouble(POSITION_PRICE_OPEN);
            double currentSL = PositionGetDouble(POSITION_SL);
            
            if(PositionGetInteger(POSITION_TYPE) == POSITION_TYPE_BUY)
            {
               double profitPoints = (currentPrice - openPrice) / _Point;
               
               if(profitPoints >= InpTrailingStart)
               {
                  double newSL = currentPrice - InpTrailingStep * _Point;
                  if(newSL > currentSL + InpTrailingStep * _Point)
                  {
                     trade.PositionModify(ticket, newSL, PositionGetDouble(POSITION_TP));
                  }
               }
            }
            else if(PositionGetInteger(POSITION_TYPE) == POSITION_TYPE_SELL)
            {
               double profitPoints = (openPrice - currentPrice) / _Point;
               
               if(profitPoints >= InpTrailingStart)
               {
                  double newSL = currentPrice + InpTrailingStep * _Point;
                  if(newSL < currentSL - InpTrailingStep * _Point)
                  {
                     trade.PositionModify(ticket, newSL, PositionGetDouble(POSITION_TP));
                  }
               }
            }
         }
      }
   }
}

//+------------------------------------------------------------------+
//| Expert tick function                                             |
//+------------------------------------------------------------------+
void OnTick()
{
   //--- Check for new bar
   if(!IsNewBar())
      return;
   
   //--- Check spread
   if(!IsSpreadValid())
   {
      Print("Spread too high: ", 
            (SymbolInfoDouble(_Symbol, SYMBOL_ASK) - SymbolInfoDouble(_Symbol, SYMBOL_BID)) / _Point,
            " points. Max: ", InpMaxSpread);
      return;
   }
   
   //--- Manage existing positions
   ManageBreakEven();
   ManageTrailingStop();
   
   //--- Check for existing positions
   if(CountOpenPositions() >= 1)
      return;
   
   //--- Get trend direction
   int trendDirection = GetTrendDirection();
   if(trendDirection == 0)
      return;
   
   //--- Check for two consecutive candles
   if(!HasTwoConsecutiveCandles(trendDirection))
      return;
   
   //--- Open position based on trend
   if(trendDirection == 1)
   {
      OpenBuyPosition();
   }
   else if(trendDirection == -1)
   {
      OpenSellPosition();
   }
}
//+------------------------------------------------------------------+