
//+------------------------------------------------------------------+
//|                                                  BreakoutEA.mq5 |
//|                                     Generated by Senior MQL5 Dev |
//+------------------------------------------------------------------+
#property copyright "Senior MQL5 Developer"
#property link      ""
#property version   "1.00"
#property description "Breakout EA: Buy khi giá đóng trên high nến trước, Sell khi đóng dưới low nến trước"
#property strict

#include <Trade\Trade.mqh>

//--- Input parameters
input group "=== Thông số giao dịch ==="
input double   InpLotSize        = 0.01;         // Lot size
input int      InpStopLoss       = 300;          // Stop Loss (points)
input int      InpTakeProfit     = 600;          // Take Profit (points)
input ulong    InpMagicNumber    = 123456;       // Magic Number
input int      InpSlippage       = 10;           // Slippage / Deviation (points)
input int      InpMaxSpread      = 30;           // Spread tối đa cho phép (points)

input group "=== Quản lý lệnh ==="
input bool     InpUseBreakEven   = true;         // Sử dụng Break Even
input int      InpBreakEvenStart = 150;          // Break Even kích hoạt từ (points)
input bool     InpUseTrailing    = true;         // Sử dụng Trailing Stop
input int      InpTrailingStart  = 200;          // Trailing Stop kích hoạt từ (points)
input int      InpTrailingStep   = 50;           // Bước nhảy Trailing Stop (points)

//--- Global variables
CTrade  trade;
MqlTick currentTick;
datetime lastBarTime = 0;
bool isNewBar = false;

//+------------------------------------------------------------------+
//| Expert initialization function                                   |
//+------------------------------------------------------------------+
int OnInit()
  {
   //--- Thiết lập Magic Number cho CTrade
   trade.SetExpertMagicNumber(InpMagicNumber);
   trade.SetDeviationInPoints(InpSlippage);
   trade.SetTypeFillingBySymbol(_Symbol);

   //--- Khởi tạo thời gian nến cuối
   lastBarTime = 0;
   isNewBar = false;

   Print("Breakout EA initialized successfully on ", _Symbol);
   return(INIT_SUCCEEDED);
  }

//+------------------------------------------------------------------+
//| Expert deinitialization function                                 |
//+------------------------------------------------------------------+
void OnDeinit(const int reason)
  {
   Print("Breakout EA deinitialized. Reason: ", reason);
  }

//+------------------------------------------------------------------+
//| Expert tick function                                             |
//+------------------------------------------------------------------+
void OnTick()
  {
   //--- Kiểm tra nến mới
   if(!CheckNewBar())
      return;

   //--- Kiểm tra điều kiện tài khoản và spread
   if(!CheckTradingConditions())
      return;

   //--- Quản lý lệnh đang mở (Break Even & Trailing)
   ManageOpenPositions();

   //--- Kiểm tra nếu đã có lệnh mở thuộc Magic Number này
   if(CountOpenPositions() >= 1)
      return;

   //--- Tính toán tín hiệu giao dịch
   int signal = GetTradeSignal();
   if(signal == 0)
      return;

   //--- Thực hiện giao dịch
   ExecuteTrade(signal);
  }

//+------------------------------------------------------------------+
//| Kiểm tra nến mới                                                 |
//+------------------------------------------------------------------+
bool CheckNewBar()
  {
   datetime currentBarTime = iTime(_Symbol, PERIOD_CURRENT, 0);
   
   if(currentBarTime != lastBarTime)
     {
      lastBarTime = currentBarTime;
      isNewBar = true;
      return true;
     }
   
   isNewBar = false;
   return false;
  }

//+------------------------------------------------------------------+
//| Kiểm tra điều kiện giao dịch                                    |
//+------------------------------------------------------------------+
bool CheckTradingConditions()
  {
   //--- Kiểm tra spread hiện tại
   if(!SymbolInfoTick(_Symbol, currentTick))
     {
      Print("Không thể lấy thông tin tick cho ", _Symbol);
      return false;
     }

   long spreadPoints = (long)((currentTick.ask - currentTick.bid) / _Point);
   
   if(spreadPoints > InpMaxSpread)
     {
      Print("Spread quá cao: ", spreadPoints, " points (tối đa: ", InpMaxSpread, " points)");
      return false;
     }

   return true;
  }

//+------------------------------------------------------------------+
//| Đếm số lượng lệnh đang mở                                      |
//+------------------------------------------------------------------+
int CountOpenPositions()
  {
   int count = 0;
   
   for(int i = PositionsTotal() - 1; i >= 0; i--)
     {
      ulong positionTicket = PositionGetTicket(i);
      if(positionTicket > 0)
        {
         if(PositionGetInteger(POSITION_MAGIC) == InpMagicNumber)
           {
            if(PositionGetString(POSITION_SYMBOL) == _Symbol)
              {
               count++;
              }
           }
        }
     }
   
   return count;
  }

//+------------------------------------------------------------------+
//| Tính toán tín hiệu giao dịch                                   |
//| Trả về: 1 = Buy, -1 = Sell, 0 = Không có tín hiệu             |
//+------------------------------------------------------------------+
int GetTradeSignal()
  {
   //--- Lấy giá của nến hiện tại và nến trước
   double currentClose = iClose(_Symbol, PERIOD_CURRENT, 0);
   double previousHigh = iHigh(_Symbol, PERIOD_CURRENT, 1);
   double previousLow = iLow(_Symbol, PERIOD_CURRENT, 1);
   
   //--- Kiểm tra dữ liệu hợp lệ
   if(currentClose <= 0 || previousHigh <= 0 || previousLow <= 0)
     {
      Print("Dữ liệu giá không hợp lệ");
      return 0;
     }
   
   //--- Tín hiệu BUY: Giá đóng trên high nến trước
   if(currentClose > previousHigh)
      return 1;
   
   //--- Tín hiệu SELL: Giá đóng dưới low nến trước
   if(currentClose < previousLow)
      return -1;
   
   return 0;
  }

//+------------------------------------------------------------------+
//| Thực hiện giao dịch                                             |
//+------------------------------------------------------------------+
void ExecuteTrade(int signal)
  {
   //--- Lấy giá hiện tại
   if(!SymbolInfoTick(_Symbol, currentTick))
     {
      Print("Không thể lấy giá hiện tại");
      return;
     }

   double price;
   double stopLoss = 0;
   double takeProfit = 0;
   bool result = false;
   
   //--- Tính toán SL và TP dựa trên tín hiệu
   if(signal > 0) // BUY
     {
      price = currentTick.ask;
      stopLoss = price - InpStopLoss * _Point;
      takeProfit = price + InpTakeProfit * _Point;
      
      result = trade.Buy(InpLotSize, _Symbol, price, stopLoss, takeProfit, "Breakout Buy");
      
      if(result)
         Print("Lệnh BUY đã được mở thành công. Giá: ", price, ", SL: ", stopLoss, ", TP: ", takeProfit);
      else
         Print("Lỗi khi mở lệnh BUY. Error code: ", GetLastError(), " - ", trade.ResultRetcodeDescription());
     }
   else if(signal < 0) // SELL
     {
      price = currentTick.bid;
      stopLoss = price + InpStopLoss * _Point;
      takeProfit = price - InpTakeProfit * _Point;
      
      result = trade.Sell(InpLotSize, _Symbol, price, stopLoss, takeProfit, "Breakout Sell");
      
      if(result)
         Print("Lệnh SELL đã được mở thành công. Giá: ", price, ", SL: ", stopLoss, ", TP: ", takeProfit);
      else
         Print("Lỗi khi mở lệnh SELL. Error code: ", GetLastError(), " - ", trade.ResultRetcodeDescription());
     }
  }

//+------------------------------------------------------------------+
//| Quản lý các lệnh đang mở (Break Even & Trailing Stop)          |
//+------------------------------------------------------------------+
void ManageOpenPositions()
  {
   for(int i = PositionsTotal() - 1; i >= 0; i--)
     {
      ulong positionTicket = PositionGetTicket(i);
      
      if(positionTicket > 0)
        {
         if(PositionGetInteger(POSITION_MAGIC) == InpMagicNumber)
           {
            if(PositionGetString(POSITION_SYMBOL) == _Symbol)
              {
               double currentPrice = 0;
               double openPrice = PositionGetDouble(POSITION_PRICE_OPEN);
               double currentSL = PositionGetDouble(POSITION_SL);
               double currentTP = PositionGetDouble(POSITION_TP);
               long positionType = PositionGetInteger(POSITION_TYPE);
               
               //--- Lấy giá hiện tại dựa trên loại lệnh
               if(!SymbolInfoTick(_Symbol, currentTick))
                  continue;
                  
               if(positionType == POSITION_TYPE_BUY)
                  currentPrice = currentTick.bid;
               else if(positionType == POSITION_TYPE_SELL)
                  currentPrice = currentTick.ask;
               else
                  continue;
               
               //--- Break Even
               if(InpUseBreakEven)
                  ApplyBreakEven(positionTicket, positionType, openPrice, currentSL, currentPrice);
               
               //--- Trailing Stop
               if(InpUseTrailing)
                  ApplyTrailingStop(positionTicket, positionType, currentSL, currentPrice);
              }
           }
        }
     }
  }

//+------------------------------------------------------------------+
//| Áp dụng Break Even                                              |
//+------------------------------------------------------------------+
void ApplyBreakEven(ulong ticket, long positionType, double openPrice, double currentSL, double currentPrice)
  {
   double breakEvenLevel = InpBreakEvenStart * _Point;
   
   if(positionType == POSITION_TYPE_BUY)
     {
      //--- Kiểm tra nếu giá đã đạt mức Break Even và SL chưa được chuyển lên
      if(currentPrice - openPrice >= breakEvenLevel && currentSL < openPrice)
        {
         double newSL = openPrice;
         
         if(trade.PositionModify(ticket, newSL, PositionGetDouble(POSITION_TP)))
            Print("Break Even áp dụng cho lệnh BUY #", ticket, " - SL mới: ", newSL);
         else
            Print("Lỗi khi áp dụng Break Even cho lệnh BUY. Error: ", GetLastError());
        }
     }
   else if(positionType == POSITION_TYPE_SELL)
     {
      //--- Kiểm tra nếu giá đã đạt mức Break Even và SL chưa được chuyển xuống
      if(openPrice - currentPrice >= breakEvenLevel && currentSL > openPrice)
        {
         double newSL = openPrice;
         
         if(trade.PositionModify(ticket, newSL, PositionGetDouble(POSITION_TP)))
            Print("Break Even áp dụng cho lệnh SELL #", ticket, " - SL mới: ", newSL);
         else
            Print("Lỗi khi áp dụng Break Even cho lệnh SELL. Error: ", GetLastError());
        }
     }
  }

//+------------------------------------------------------------------+
//| Áp dụng Trailing Stop                                           |
//+------------------------------------------------------------------+
void ApplyTrailingStop(ulong ticket, long positionType, double currentSL, double currentPrice)
  {
   double trailingStart = InpTrailingStart * _Point;
   double trailingStep = InpTrailingStep * _Point;
   
   if(positionType == POSITION_TYPE_BUY)
     {
      double openPrice = PositionGetDouble(POSITION_PRICE_OPEN);
      double newSL = currentPrice - trailingStart;
      
      //--- Chỉ điều chỉnh SL nếu giá đã đi đúng hướng và SL mới hợp lệ
      if(currentPrice - openPrice >= trailingStart)
        {
         //--- Đảm bảo SL chỉ đi theo hướng có lợi (tăng lên)
         if(newSL > currentSL + trailingStep || currentSL == 0)
           {
            if(trade.PositionModify(ticket, newSL, PositionGetDouble(POSITION_TP)))
               Print("Trailing Stop áp dụng cho lệnh BUY #", ticket, " - SL mới: ", newSL);
            else
               Print("Lỗi khi áp dụng Trailing Stop cho lệnh BUY. Error: ", GetLastError());
           }
        }
     }
   else if(positionType == POSITION_TYPE_SELL)
     {
      double openPrice = PositionGetDouble(POSITION_PRICE_OPEN);
      double newSL = currentPrice + trailingStart;
      
      //--- Chỉ điều chỉnh SL nếu giá đã đi đúng hướng và SL mới hợp lệ
      if(openPrice - currentPrice >= trailingStart)
        {
         //--- Đảm bảo SL chỉ đi theo hướng có lợi (giảm xuống)
         if(newSL < currentSL - trailingStep || currentSL == 0)
           {
            if(trade.PositionModify(ticket, newSL, PositionGetDouble(POSITION_TP)))
               Print("Trailing Stop áp dụng cho lệnh SELL #", ticket, " - SL mới: ", newSL);
            else
               Print("Lỗi khi áp dụng Trailing Stop cho lệnh SELL. Error: ", GetLastError());
           }
        }
     }
  }
//+------------------------------------------------------------------+