
//+------------------------------------------------------------------+
//|                                                      BreakoutEA.mq5 |
//|                                    Generated by Senior MQL5 Dev  |
//|                                                                  |
//+------------------------------------------------------------------+
#property copyright "Generated by Senior MQL5 Dev"
#property link      ""
#property version   "1.00"

#include <Trade\Trade.mqh>

//--- Input Parameters
input group "=== General Settings ==="
input double InpLotSize        = 0.01;    // Lot Size
input ulong  InpMagicNumber    = 123456;  // Magic Number
input int    InpSlippage       = 10;      // Slippage (points)

input group "=== Trade Management ==="
input int    InpStopLoss       = 300;     // Stop Loss (points)
input int    InpTakeProfit     = 600;     // Take Profit (points)

input group "=== Break Even Settings ==="
input bool   InpUseBreakEven   = true;    // Enable Break Even
input int    InpBreakEvenTrigger = 150;   // Break Even Trigger (points)
input int    InpBreakEvenLock    = 0;     // Break Even Lock (points, 0 = BE)

input group "=== Trailing Stop Settings ==="
input bool   InpUseTrailing    = true;    // Enable Trailing Stop
input int    InpTrailingStart  = 200;     // Trailing Start (points)
input int    InpTrailingStep   = 50;      // Trailing Step (points)

input group "=== Filters ==="
input int    InpMaxSpread      = 30;      // Max Spread (points)
input int    InpBarsCount      = 5;       // Number of bars for breakout

//--- Global Variables
CTrade  trade;
MqlTick currentTick;
MqlRates lastBars[];
bool isNewBar = false;
datetime lastBarTime = 0;

//+------------------------------------------------------------------+
//| Expert initialization function                                   |
//+------------------------------------------------------------------+
int OnInit()
{
   //--- Validate inputs
   if(InpLotSize <= 0)
   {
      Print("Invalid lot size!");
      return(INIT_PARAMETERS_INCORRECT);
   }
   
   if(InpStopLoss <= 0 || InpTakeProfit <= 0)
   {
      Print("Invalid SL/TP!");
      return(INIT_PARAMETERS_INCORRECT);
   }
   
   if(InpBarsCount < 2)
   {
      Print("Invalid bars count (must be >= 2)!");
      return(INIT_PARAMETERS_INCORRECT);
   }

   //--- Set trade object parameters
   trade.SetExpertMagicNumber(InpMagicNumber);
   trade.SetDeviationInPoints(InpSlippage);
   trade.SetTypeFillingBySymbol(_Symbol);
   
   //--- Initialize array
   ArraySetAsSeries(lastBars, true);
   
   Print("Breakout EA initialized successfully!");
   return(INIT_SUCCEEDED);
}

//+------------------------------------------------------------------+
//| Expert deinitialization function                                 |
//+------------------------------------------------------------------+
void OnDeinit(const int reason)
{
   Print("Breakout EA deinitialized. Reason: ", reason);
}

//+------------------------------------------------------------------+
//| Expert tick function                                             |
//+------------------------------------------------------------------+
void OnTick()
{
   //--- Check for new bar
   if(!CheckNewBar())
      return;
   
   //--- Get current tick
   if(!SymbolInfoTick(_Symbol, currentTick))
   {
      Print("Failed to get tick data!");
      return;
   }
   
   //--- Check spread
   if(!CheckSpread())
      return;
   
   //--- Manage existing positions
   ManagePositions();
   
   //--- Check if position already exists
   if(CountPositions() > 0)
      return;
   
   //--- Get latest bars
   if(!GetBarsData())
      return;
   
   //--- Calculate breakout levels
   double highest = 0, lowest = 0;
   CalculateBreakoutLevels(highest, lowest);
   
   if(highest <= 0 || lowest <= 0)
      return;
   
   //--- Check breakout signals
   double ask = currentTick.ask;
   double bid = currentTick.bid;
   
   //--- Buy signal: price breaks above highest high
   if(ask > highest)
   {
      ExecuteBuy(ask);
   }
   //--- Sell signal: price breaks below lowest low
   else if(bid < lowest)
   {
      ExecuteSell(bid);
   }
}

//+------------------------------------------------------------------+
//| Check for new bar                                                |
//+------------------------------------------------------------------+
bool CheckNewBar()
{
   datetime currentBarTime = iTime(_Symbol, PERIOD_CURRENT, 0);
   
   if(currentBarTime != lastBarTime)
   {
      lastBarTime = currentBarTime;
      isNewBar = true;
      return true;
   }
   
   isNewBar = false;
   return false;
}

//+------------------------------------------------------------------+
//| Check spread                                                     |
//+------------------------------------------------------------------+
bool CheckSpread()
{
   int currentSpread = (int)MathRound((currentTick.ask - currentTick.bid) / _Point);
   
   if(currentSpread > InpMaxSpread)
   {
      Print("Spread too high: ", currentSpread, " points (max: ", InpMaxSpread, ")");
      return false;
   }
   
   return true;
}

//+------------------------------------------------------------------+
//| Get bars data                                                    |
//+------------------------------------------------------------------+
bool GetBarsData()
{
   if(CopyRates(_Symbol, PERIOD_CURRENT, 0, InpBarsCount + 1, lastBars) < InpBarsCount + 1)
   {
      Print("Failed to get bars data!");
      return false;
   }
   
   return true;
}

//+------------------------------------------------------------------+
//| Calculate breakout levels from previous bars                     |
//+------------------------------------------------------------------+
void CalculateBreakoutLevels(double &highest, double &lowest)
{
   highest = 0;
   lowest = DBL_MAX;
   
   //--- Start from index 1 to skip current incomplete bar
   for(int i = 1; i <= InpBarsCount; i++)
   {
      if(lastBars[i].high > highest)
         highest = lastBars[i].high;
      
      if(lastBars[i].low < lowest)
         lowest = lastBars[i].low;
   }
}

//+------------------------------------------------------------------+
//| Execute buy order                                                |
//+------------------------------------------------------------------+
void ExecuteBuy(double ask)
{
   double sl = NormalizeDouble(ask - InpStopLoss * _Point, _Digits);
   double tp = NormalizeDouble(ask + InpTakeProfit * _Point, _Digits);
   
   if(trade.Buy(InpLotSize, _Symbol, ask, sl, tp, "Breakout Buy"))
   {
      Print("Buy order placed successfully. Price: ", ask, " SL: ", sl, " TP: ", tp);
   }
   else
   {
      Print("Buy order failed. Error: ", trade.ResultRetcode(), " - ", trade.ResultRetcodeDescription());
   }
}

//+------------------------------------------------------------------+
//| Execute sell order                                               |
//+------------------------------------------------------------------+
void ExecuteSell(double bid)
{
   double sl = NormalizeDouble(bid + InpStopLoss * _Point, _Digits);
   double tp = NormalizeDouble(bid - InpTakeProfit * _Point, _Digits);
   
   if(trade.Sell(InpLotSize, _Symbol, bid, sl, tp, "Breakout Sell"))
   {
      Print("Sell order placed successfully. Price: ", bid, " SL: ", sl, " TP: ", tp);
   }
   else
   {
      Print("Sell order failed. Error: ", trade.ResultRetcode(), " - ", trade.ResultRetcodeDescription());
   }
}

//+------------------------------------------------------------------+
//| Count open positions with this magic number                       |
//+------------------------------------------------------------------+
int CountPositions()
{
   int count = 0;
   
   for(int i = PositionsTotal() - 1; i >= 0; i--)
   {
      ulong positionTicket = PositionGetTicket(i);
      
      if(positionTicket > 0)
      {
         if(PositionGetString(POSITION_SYMBOL) == _Symbol && 
            PositionGetInteger(POSITION_MAGIC) == InpMagicNumber)
         {
            count++;
         }
      }
   }
   
   return count;
}

//+------------------------------------------------------------------+
//| Manage existing positions (BE & Trailing)                        |
//+------------------------------------------------------------------+
void ManagePositions()
{
   for(int i = PositionsTotal() - 1; i >= 0; i--)
   {
      ulong positionTicket = PositionGetTicket(i);
      
      if(positionTicket <= 0)
         continue;
      
      if(PositionGetString(POSITION_SYMBOL) != _Symbol || 
         PositionGetInteger(POSITION_MAGIC) != InpMagicNumber)
         continue;
      
      //--- Get position details
      long positionType = PositionGetInteger(POSITION_TYPE);
      double positionOpenPrice = PositionGetDouble(POSITION_PRICE_OPEN);
      double positionSL = PositionGetDouble(POSITION_SL);
      double positionTP = PositionGetDouble(POSITION_TP);
      
      //--- Current price based on position type
      double currentPrice = (positionType == POSITION_TYPE_BUY) ? currentTick.bid : currentTick.ask;
      
      //--- Break Even management
      if(InpUseBreakEven)
      {
         ManageBreakEven(positionTicket, positionType, positionOpenPrice, positionSL, currentPrice);
      }
      
      //--- Refresh position data after possible SL modification
      positionSL = PositionGetDouble(POSITION_SL);
      
      //--- Trailing stop management
      if(InpUseTrailing)
      {
         ManageTrailingStop(positionTicket, positionType, positionOpenPrice, positionSL, currentPrice);
      }
   }
}

//+------------------------------------------------------------------+
//| Manage break even                                                |
//+------------------------------------------------------------------+
void ManageBreakEven(ulong ticket, long positionType, double openPrice, double currentSL, double currentPrice)
{
   double beLevel = 0;
   double newSL = 0;
   
   if(positionType == POSITION_TYPE_BUY)
   {
      //--- Calculate profit in points
      double profitPoints = (currentPrice - openPrice) / _Point;
      
      if(profitPoints >= InpBreakEvenTrigger)
      {
         beLevel = openPrice + InpBreakEvenLock * _Point;
         
         //--- Check if current SL is below BE level
         if(currentSL < beLevel || currentSL == 0)
         {
            newSL = NormalizeDouble(beLevel, _Digits);
            
            if(trade.PositionModify(ticket, newSL, PositionGetDouble(POSITION_TP)))
            {
               Print("Break even applied for buy position. New SL: ", newSL);
            }
         }
      }
   }
   else if(positionType == POSITION_TYPE_SELL)
   {
      //--- Calculate profit in points
      double profitPoints = (openPrice - currentPrice) / _Point;
      
      if(profitPoints >= InpBreakEvenTrigger)
      {
         beLevel = openPrice - InpBreakEvenLock * _Point;
         
         //--- Check if current SL is above BE level
         if(currentSL > beLevel || currentSL == 0)
         {
            newSL = NormalizeDouble(beLevel, _Digits);
            
            if(trade.PositionModify(ticket, newSL, PositionGetDouble(POSITION_TP)))
            {
               Print("Break even applied for sell position. New SL: ", newSL);
            }
         }
      }
   }
}

//+------------------------------------------------------------------+
//| Manage trailing stop                                             |
//+------------------------------------------------------------------+
void ManageTrailingStop(ulong ticket, long positionType, double openPrice, double currentSL, double currentPrice)
{
   double newSL = 0;
   
   if(positionType == POSITION_TYPE_BUY)
   {
      //--- Calculate profit in points
      double profitPoints = (currentPrice - openPrice) / _Point;
      
      if(profitPoints >= InpTrailingStart)
      {
         //--- Calculate new SL based on trailing
         newSL = NormalizeDouble(currentPrice - InpTrailingStart * _Point, _Digits);
         
         //--- Check if new SL is better than current
         if(newSL > currentSL || currentSL == 0)
         {
            //--- Apply step logic
            if(currentSL == 0 || newSL - currentSL >= InpTrailingStep * _Point)
            {
               if(trade.PositionModify(ticket, newSL, PositionGetDouble(POSITION_TP)))
               {
                  Print("Trailing stop updated for buy position. New SL: ", newSL);
               }
            }
         }
      }
   }
   else if(positionType == POSITION_TYPE_SELL)
   {
      //--- Calculate profit in points
      double profitPoints = (openPrice - currentPrice) / _Point;
      
      if(profitPoints >= InpTrailingStart)
      {
         //--- Calculate new SL based on trailing
         newSL = NormalizeDouble(currentPrice + InpTrailingStart * _Point, _Digits);
         
         //--- Check if new SL is better than current
         if(newSL < currentSL || currentSL == 0)
         {
            //--- Apply step logic
            if(currentSL == 0 || currentSL - newSL >= InpTrailingStep * _Point)
            {
               if(trade.PositionModify(ticket, newSL, PositionGetDouble(POSITION_TP)))
               {
                  Print("Trailing stop updated for sell position. New SL: ", newSL);
               }
            }
         }
      }
   }
}
//+------------------------------------------------------------------+