//+------------------------------------------------------------------+
//|                                                  EMA20_EMA50.mq5 |
//|                                    Generated by Senior MQL5 Dev |
//|                                                                  |
//+------------------------------------------------------------------+
#property copyright "Senior MQL5 Developer"
#property link      ""
#property version   "1.00"
#property strict

#include <Trade\Trade.mqh>

//--- Input Parameters
input group "=== Thông số giao dịch chính ==="
input double InpLotSize       = 0.01;          // Khối lượng giao dịch
input int    InpStopLoss      = 300;           // Stop Loss (points)
input int    InpTakeProfit    = 600;           // Take Profit (points)
input ulong  InpMagicNumber   = 20240501;      // Magic Number
input int    InpSlippage      = 10;            // Slippage / Deviation (points)

input group "=== Thông số tín hiệu EMA ==="
input int    InpFastEMA       = 20;            // Chu kỳ EMA nhanh
input int    InpSlowEMA       = 50;            // Chu kỳ EMA chậm
input int    InpMaxSpread     = 30;            // Spread tối đa cho phép (points)

input group "=== Quản lý lệnh ==="
input bool   InpUseBreakEven  = true;          // Sử dụng Break Even
input int    InpBreakEvenTrigger = 150;        // Điểm kích hoạt Break Even (points)
input int    InpBreakEvenShift   = 0;          // Dịch chuyển Break Even (points) - 0 = về giá mở cửa
input bool   InpUseTrailing   = true;          // Sử dụng Trailing Stop
input int    InpTrailingStart = 200;           // Điểm kích hoạt Trailing (points)
input int    InpTrailingStep  = 50;            // Bước nhảy Trailing (points)

//--- Global Variables
CTrade  trade;
int     fastEMAHandle;
int     slowEMAHandle;
double  fastEMA[];
double  slowEMA[];
datetime lastBarTime = 0;

//+------------------------------------------------------------------+
//| Expert initialization function                                   |
//+------------------------------------------------------------------+
int OnInit()
{
   //--- Thiết lập Magic Number cho CTrade
   trade.SetExpertMagicNumber(InpMagicNumber);
   
   //--- Thiết lập Slippage
   trade.SetDeviationInPoints(InpSlippage);
   
   //--- Khởi tạo indicator handles
   fastEMAHandle = iMA(_Symbol, PERIOD_CURRENT, InpFastEMA, 0, MODE_EMA, PRICE_CLOSE);
   slowEMAHandle = iMA(_Symbol, PERIOD_CURRENT, InpSlowEMA, 0, MODE_EMA, PRICE_CLOSE);
   
   if(fastEMAHandle == INVALID_HANDLE || slowEMAHandle == INVALID_HANDLE)
   {
      Print("Lỗi khởi tạo indicator handles: ", GetLastError());
      return(INIT_FAILED);
   }
   
   //--- Khởi tạo mảng
   ArraySetAsSeries(fastEMA, true);
   ArraySetAsSeries(slowEMA, true);
   
   lastBarTime = 0;
   
   Print("EA EMA20-EMA50 đã được khởi tạo thành công.");
   return(INIT_SUCCEEDED);
}

//+------------------------------------------------------------------+
//| Expert deinitialization function                                 |
//+------------------------------------------------------------------+
void OnDeinit(const int reason)
{
   //--- Giải phóng indicator handles
   if(fastEMAHandle != INVALID_HANDLE)
      IndicatorRelease(fastEMAHandle);
   if(slowEMAHandle != INVALID_HANDLE)
      IndicatorRelease(slowEMAHandle);
   
   Print("EA đã được gỡ bỏ. Reason: ", reason);
}

//+------------------------------------------------------------------+
//| Kiểm tra nến mới                                                 |
//+------------------------------------------------------------------+
bool IsNewBar()
{
   datetime currentBarTime = iTime(_Symbol, PERIOD_CURRENT, 0);
   if(currentBarTime != lastBarTime)
   {
      lastBarTime = currentBarTime;
      return(true);
   }
   return(false);
}

//+------------------------------------------------------------------+
//| Kiểm tra spread tối đa                                          |
//+------------------------------------------------------------------+
bool IsSpreadValid()
{
   long spreadPoints = SymbolInfoInteger(_Symbol, SYMBOL_SPREAD);
   if(spreadPoints <= InpMaxSpread)
      return(true);
   
   Print("Spread hiện tại (", spreadPoints, " points) vượt quá mức cho phép (", InpMaxSpread, " points). Bỏ qua tín hiệu.");
   return(false);
}

//+------------------------------------------------------------------+
//| Đếm số lệnh đang mở thuộc Magic Number                          |
//+------------------------------------------------------------------+
int CountOpenPositions()
{
   int count = 0;
   for(int i = PositionsTotal() - 1; i >= 0; i--)
   {
      ulong positionTicket = PositionGetTicket(i);
      if(positionTicket > 0)
      {
         if(PositionGetInteger(POSITION_MAGIC) == InpMagicNumber)
            count++;
      }
   }
   return(count);
}

//+------------------------------------------------------------------+
//| Lấy tín hiệu EMA                                                 |
//+------------------------------------------------------------------+
int GetEMASignal()
{
   //--- Lấy dữ liệu EMA
   if(CopyBuffer(fastEMAHandle, 0, 1, 3, fastEMA) < 3)
   {
      Print("Lỗi copy dữ liệu EMA nhanh: ", GetLastError());
      return(0);
   }
   if(CopyBuffer(slowEMAHandle, 0, 1, 3, slowEMA) < 3)
   {
      Print("Lỗi copy dữ liệu EMA chậm: ", GetLastError());
      return(0);
   }
   
   //--- Kiểm tra dữ liệu hợp lệ
   if(fastEMA[0] == 0 || fastEMA[1] == 0 || fastEMA[2] == 0 ||
      slowEMA[0] == 0 || slowEMA[1] == 0 || slowEMA[2] == 0)
      return(0);
   
   //--- Xác định độ dốc EMA nhanh
   double fastEMASlope = fastEMA[1] - fastEMA[2]; // Thay đổi của EMA nhanh so với nến trước
   
   //--- Xác định khoảng cách giữa EMA20 và EMA50
   double currentGap = fastEMA[0] - slowEMA[0];   // Khoảng cách hiện tại
   double previousGap = fastEMA[1] - slowEMA[1];  // Khoảng cách nến trước
   
   //--- Tín hiệu BUY: EMA20 dốc lên và khoảng cách đang mở rộng (dương)
   if(fastEMASlope > 0 && currentGap > previousGap && currentGap > 0)
      return(1); // BUY signal
   
   //--- Tín hiệu SELL: EMA20 dốc xuống và khoảng cách đang mở rộng (âm)
   if(fastEMASlope < 0 && currentGap < previousGap && currentGap < 0)
      return(-1); // SELL signal
   
   return(0); // Không có tín hiệu
}

//+------------------------------------------------------------------+
//| Mở lệnh BUY                                                     |
//+------------------------------------------------------------------+
void OpenBuyPosition()
{
   double price = SymbolInfoDouble(_Symbol, SYMBOL_ASK);
   double sl = price - InpStopLoss * _Point;
   double tp = price + InpTakeProfit * _Point;
   
   //--- Chuẩn hóa giá
   price = NormalizeDouble(price, _Digits);
   sl = NormalizeDouble(sl, _Digits);
   tp = NormalizeDouble(tp, _Digits);
   
   //--- Thực hiện lệnh Buy
   if(trade.Buy(InpLotSize, _Symbol, price, sl, tp, "EMA20-EMA50 BUY"))
   {
      Print("Mở lệnh BUY thành công. Ticket: ", trade.ResultOrder());
   }
   else
   {
      Print("Lỗi mở lệnh BUY: ", trade.ResultRetcode(), " - ", trade.ResultRetcodeDescription());
   }
}

//+------------------------------------------------------------------+
//| Mở lệnh SELL                                                    |
//+------------------------------------------------------------------+
void OpenSellPosition()
{
   double price = SymbolInfoDouble(_Symbol, SYMBOL_BID);
   double sl = price + InpStopLoss * _Point;
   double tp = price - InpTakeProfit * _Point;
   
   //--- Chuẩn hóa giá
   price = NormalizeDouble(price, _Digits);
   sl = NormalizeDouble(sl, _Digits);
   tp = NormalizeDouble(tp, _Digits);
   
   //--- Thực hiện lệnh Sell
   if(trade.Sell(InpLotSize, _Symbol, price, sl, tp, "EMA20-EMA50 SELL"))
   {
      Print("Mở lệnh SELL thành công. Ticket: ", trade.ResultOrder());
   }
   else
   {
      Print("Lỗi mở lệnh SELL: ", trade.ResultRetcode(), " - ", trade.ResultRetcodeDescription());
   }
}

//+------------------------------------------------------------------+
//| Quản lý Break Even                                               |
//+------------------------------------------------------------------+
void ManageBreakEven()
{
   for(int i = PositionsTotal() - 1; i >= 0; i--)
   {
      ulong ticket = PositionGetTicket(i);
      if(ticket > 0)
      {
         if(PositionGetInteger(POSITION_MAGIC) == InpMagicNumber && 
            PositionGetString(POSITION_SYMBOL) == _Symbol)
         {
            double openPrice = PositionGetDouble(POSITION_PRICE_OPEN);
            double currentSL = PositionGetDouble(POSITION_SL);
            double currentPrice = PositionGetDouble(POSITION_PRICE_CURRENT);
            long positionType = PositionGetInteger(POSITION_TYPE);
            
            //--- Kiểm tra lợi nhuận theo points
            if(positionType == POSITION_TYPE_BUY)
            {
               double profitPoints = (currentPrice - openPrice) / _Point;
               if(profitPoints >= InpBreakEvenTrigger)
               {
                  double newSL = openPrice + InpBreakEvenShift * _Point;
                  newSL = NormalizeDouble(newSL, _Digits);
                  
                  if(newSL != currentSL && newSL > currentSL)
                  {
                     if(trade.PositionModify(ticket, newSL, PositionGetDouble(POSITION_TP)))
                        Print("Break Even BUY được thiết lập. Ticket: ", ticket);
                  }
               }
            }
            else if(positionType == POSITION_TYPE_SELL)
            {
               double profitPoints = (openPrice - currentPrice) / _Point;
               if(profitPoints >= InpBreakEvenTrigger)
               {
                  double newSL = openPrice - InpBreakEvenShift * _Point;
                  newSL = NormalizeDouble(newSL, _Digits);
                  
                  if(newSL != currentSL && newSL < currentSL)
                  {
                     if(trade.PositionModify(ticket, newSL, PositionGetDouble(POSITION_TP)))
                        Print("Break Even SELL được thiết lập. Ticket: ", ticket);
                  }
               }
            }
         }
      }
   }
}

//+------------------------------------------------------------------+
//| Quản lý Trailing Stop                                           |
//+------------------------------------------------------------------+
void ManageTrailingStop()
{
   for(int i = PositionsTotal() - 1; i >= 0; i--)
   {
      ulong ticket = PositionGetTicket(i);
      if(ticket > 0)
      {
         if(PositionGetInteger(POSITION_MAGIC) == InpMagicNumber && 
            PositionGetString(POSITION_SYMBOL) == _Symbol)
         {
            double currentSL = PositionGetDouble(POSITION_SL);
            double currentPrice = PositionGetDouble(POSITION_PRICE_CURRENT);
            long positionType = PositionGetInteger(POSITION_TYPE);
            
            if(positionType == POSITION_TYPE_BUY)
            {
               double trailingLevel = currentPrice - InpTrailingStart * _Point;
               double newSL = currentPrice - InpTrailingStart * _Point;
               newSL = NormalizeDouble(newSL, _Digits);
               
               //--- Kiểm tra nếu SL mới cao hơn SL hiện tại (đối với BUY)
               if(newSL > currentSL)
               {
                  //--- Kiểm tra bước nhảy
                  double stepPoints = (newSL - currentSL) / _Point;
                  if(stepPoints >= InpTrailingStep || currentSL == 0)
                  {
                     if(trade.PositionModify(ticket, newSL, PositionGetDouble(POSITION_TP)))
                        Print("Trailing Stop BUY được cập nhật. Ticket: ", ticket);
                  }
               }
            }
            else if(positionType == POSITION_TYPE_SELL)
            {
               double newSL = currentPrice + InpTrailingStart * _Point;
               newSL = NormalizeDouble(newSL, _Digits);
               
               //--- Kiểm tra nếu SL mới thấp hơn SL hiện tại (đối với SELL)
               if(newSL < currentSL || currentSL == 0)
               {
                  //--- Kiểm tra bước nhảy
                  double stepPoints = (currentSL - newSL) / _Point;
                  if(stepPoints >= InpTrailingStep || currentSL == 0)
                  {
                     if(trade.PositionModify(ticket, newSL, PositionGetDouble(POSITION_TP)))
                        Print("Trailing Stop SELL được cập nhật. Ticket: ", ticket);
                  }
               }
            }
         }
      }
   }
}

//+------------------------------------------------------------------+
//| Expert tick function                                            |
//+------------------------------------------------------------------+
void OnTick()
{
   //--- Kiểm tra nến mới (chỉ giao dịch khi có nến mới)
   if(!IsNewBar())
      return;
   
   //--- Kiểm tra spread
   if(!IsSpreadValid())
      return;
   
   //--- Đếm số lệnh đang mở
   int openPositions = CountOpenPositions();
   
   //--- Quản lý lệnh đang mở
   if(openPositions > 0)
   {
      if(InpUseBreakEven)
         ManageBreakEven();
      if(InpUseTrailing)
         ManageTrailingStop();
      return; // Không vào lệnh mới khi đã có lệnh
   }
   
   //--- Kiểm tra tín hiệu và vào lệnh mới
   int signal = GetEMASignal();
   
   if(signal == 1)
   {
      Print("Phát hiện tín hiệu BUY. Đang mở lệnh...");
      OpenBuyPosition();
   }
   else if(signal == -1)
   {
      Print("Phát hiện tín hiệu SELL. Đang mở lệnh...");
      OpenSellPosition();
   }
}
//+------------------------------------------------------------------+