//+------------------------------------------------------------------+
//|                                              EMA_Trend_EA.mq5   |
//|                                     Generated by Senior MQL5    |
//|                                             Version 2.00        |
//+------------------------------------------------------------------+
#property copyright "Senior MQL5 Developer"
#property link      ""
#property version   "2.00"
#property description "EA based on EMA20 trend: Buy when EMA20 rises and close above EMA20, Sell when EMA20 falls and close below EMA20."

#include <Trade\Trade.mqh>

//--- Input parameters
input group "=== General Parameters ==="
input double InpLotSize        = 0.01;   // Lot size
input int    InpStopLoss       = 300;    // Stop Loss (points)
input int    InpTakeProfit     = 600;    // Take Profit (points)
input ulong  InpMagicNumber    = 123456; // Magic Number
input int    InpSlippage       = 10;     // Slippage/Deviation (points)
input int    InpMaxSpread      = 30;     // Maximum spread allowed (points)

input group "=== Signal Parameters ==="
input int    InpEMAPeriod      = 50;     // EMA period
input int    InpMinTrendBars   = 1;      // Minimum consecutive bars EMA rising/falling (1 = simple rise/fall)
input bool   InpDebugMode      = false;  // Enable debug logging (print signal details)

input group "=== Risk Management ==="
input bool   InpUseBreakEven   = true;   // Use Break Even
input int    InpBreakEvenTrigger = 150;  // Break Even trigger (points)
input bool   InpUseTrailing    = true;   // Use Trailing Stop
input int    InpTrailingTrigger  = 200;  // Trailing trigger (points)
input int    InpTrailingStep   = 50;     // Trailing step (points)

//--- Global variables
CTrade trade;
int emaHandle = INVALID_HANDLE;
datetime lastBarTime = 0;

//+------------------------------------------------------------------+
//| Expert initialization function                                   |
//+------------------------------------------------------------------+
int OnInit() {
   // Set trade parameters
   trade.SetExpertMagicNumber(InpMagicNumber);
   trade.SetDeviationInPoints(InpSlippage);
   trade.SetTypeFillingBySymbol(_Symbol);

   // Create EMA indicator handle
   emaHandle = iMA(_Symbol, _Period, InpEMAPeriod, 0, MODE_EMA, PRICE_CLOSE);
   if(emaHandle == INVALID_HANDLE) {
      Print("Error creating EMA handle: ", GetLastError());
      return(INIT_FAILED);
   }

   return(INIT_SUCCEEDED);
}

//+------------------------------------------------------------------+
//| Expert deinitialization function                                 |
//+------------------------------------------------------------------+
void OnDeinit(const int reason) {
   if(emaHandle != INVALID_HANDLE) {
      IndicatorRelease(emaHandle);
      emaHandle = INVALID_HANDLE;
   }
}

//+------------------------------------------------------------------+
//| Expert tick function                                             |
//+------------------------------------------------------------------+
void OnTick() {
   // Check account and terminal trading conditions
   if(!CheckTradingConditions()) return;

   // Manage existing positions (Break Even, Trailing) on every tick
   ManageOpenPositions();

   // Check for new bar to avoid multiple entries per bar
   if(!IsNewBar()) return;

   // Check spread
   double ask = SymbolInfoDouble(_Symbol, SYMBOL_ASK);
   double bid = SymbolInfoDouble(_Symbol, SYMBOL_BID);
   double spreadPoints = (ask - bid) / _Point;
   if(spreadPoints > InpMaxSpread) {
      if(InpDebugMode) Print("Spread too high: ", spreadPoints, " > ", InpMaxSpread);
      return;
   }

   // Check maximum open positions
   if(CountOpenPositions(InpMagicNumber) >= 1) {
      if(InpDebugMode) Print("Already have an open position with magic ", InpMagicNumber);
      return;
   }

   // Prepare array for EMA values (need from shift 0 to shift InpMinTrendBars+1)
   int barsToCopy = InpMinTrendBars + 2; // e.g., if MinTrendBars=1 => 3 elements (indices 0..2)
   double ema[];
   ArrayResize(ema, barsToCopy);
   ArraySetAsSeries(ema, true); // index 0 = current bar, 1 = previous bar, ...

   if(CopyBuffer(emaHandle, 0, 0, barsToCopy, ema) < barsToCopy) {
      int err = GetLastError();
      Print("Error copying EMA buffer: ", err);
      if(InpDebugMode) Print("barsToCopy=", barsToCopy, ", copied=", CopyBuffer(emaHandle, 0, 0, barsToCopy, ema));
      return;
   }

   // Get close price of previous closed bar (shift 1)
   double closePrev = iClose(_Symbol, _Period, 1);
   if(closePrev <= 0) {
      Print("Error getting close price of previous bar");
      return;
   }

   // Determine trend: consecutive rising/falling EMA (based on closed bars)
   bool trendUp = true;
   bool trendDown = true;
   for(int i = 1; i <= InpMinTrendBars; i++) {
      // Compare ema[i] (previous bar i) with ema[i+1] (one bar before)
      if(ema[i] <= ema[i+1]) trendUp = false;
      if(ema[i] >= ema[i+1]) trendDown = false;
   }

   // Generate signals
   bool buySignal  = trendUp   && (closePrev > ema[1]);
   bool sellSignal = trendDown && (closePrev < ema[1]);

   if(InpDebugMode) {
      Print("--- New Bar Signal Check ---");
      Print("Time: ", TimeToString(iTime(_Symbol, _Period, 0)));
      Print("EMA[1]=", ema[1], ", EMA[2]=", ema[2], ", Close[1]=", closePrev);
      Print("TrendUp=", trendUp, ", TrendDown=", trendDown);
      Print("BuySignal=", buySignal, ", SellSignal=", sellSignal);
      Print("Spread=", spreadPoints);
      Print("OpenPositions=", CountOpenPositions(InpMagicNumber));
   }

   // Execute trades
   if(buySignal) {
      double currentAsk = SymbolInfoDouble(_Symbol, SYMBOL_ASK);
      double sl = currentAsk - InpStopLoss * _Point;
      double tp = currentAsk + InpTakeProfit * _Point;
      if(trade.Buy(InpLotSize, _Symbol, currentAsk, sl, tp, "EMA20 Trend EA Buy")) {
         Print("Buy order opened successfully. Ticket: ", trade.ResultOrder());
      } else {
         Print("Buy order failed. Error code: ", trade.ResultRetcode(), " - ", trade.ResultRetcodeDescription());
      }
   } else if(sellSignal) {
      double currentBid = SymbolInfoDouble(_Symbol, SYMBOL_BID);
      double sl = currentBid + InpStopLoss * _Point;
      double tp = currentBid - InpTakeProfit * _Point;
      if(trade.Sell(InpLotSize, _Symbol, currentBid, sl, tp, "EMA20 Trend EA Sell")) {
         Print("Sell order opened successfully. Ticket: ", trade.ResultOrder());
      } else {
         Print("Sell order failed. Error code: ", trade.ResultRetcode(), " - ", trade.ResultRetcodeDescription());
      }
   }
}

//+------------------------------------------------------------------+
//| Check trading conditions                                         |
//+------------------------------------------------------------------+
bool CheckTradingConditions() {
   if(!TerminalInfoInteger(TERMINAL_TRADE_ALLOWED)) return false;
   if(!AccountInfoInteger(ACCOUNT_TRADE_EXPERT)) return false;
   if(!AccountInfoInteger(ACCOUNT_TRADE_ALLOWED)) return false;
   return true;
}

//+------------------------------------------------------------------+
//| Check if new bar has appeared                                    |
//+------------------------------------------------------------------+
bool IsNewBar() {
   datetime curBarTime = iTime(_Symbol, _Period, 0);
   if(curBarTime == 0) return false;
   if(curBarTime != lastBarTime) {
      lastBarTime = curBarTime;
      return true;
   }
   return false;
}

//+------------------------------------------------------------------+
//| Count open positions with specified magic number                 |
//+------------------------------------------------------------------+
int CountOpenPositions(ulong magic) {
   int count = 0;
   for(int i = PositionsTotal() - 1; i >= 0; i--) {
      ulong ticket = PositionGetTicket(i);
      if(ticket != 0) {
         if(PositionSelectByTicket(ticket)) {
            if(PositionGetString(POSITION_SYMBOL) == _Symbol && PositionGetInteger(POSITION_MAGIC) == magic) {
               count++;
            }
         }
      }
   }
   return count;
}

//+------------------------------------------------------------------+
//| Manage open positions (Break Even and Trailing Stop)             |
//+------------------------------------------------------------------+
void ManageOpenPositions() {
   for(int i = PositionsTotal() - 1; i >= 0; i--) {
      ulong ticket = PositionGetTicket(i);
      if(ticket == 0) continue;
      if(!PositionSelectByTicket(ticket)) continue;
      if(PositionGetString(POSITION_SYMBOL) != _Symbol || PositionGetInteger(POSITION_MAGIC) != InpMagicNumber) continue;

      long posType = PositionGetInteger(POSITION_TYPE);
      double openPrice = PositionGetDouble(POSITION_PRICE_OPEN);
      double currentSL = PositionGetDouble(POSITION_SL);
      double currentTP = PositionGetDouble(POSITION_TP);
      double bid = SymbolInfoDouble(_Symbol, SYMBOL_BID);
      double ask = SymbolInfoDouble(_Symbol, SYMBOL_ASK);
      double point = _Point;
      double profitPoints = 0.0;
      double newSL = currentSL;
      bool modify = false;

      if(posType == POSITION_TYPE_BUY) {
         profitPoints = (bid - openPrice) / point;

         // Break Even: move SL to open price when profit reaches trigger
         if(InpUseBreakEven && currentSL < openPrice && profitPoints >= InpBreakEvenTrigger) {
            newSL = MathMax(newSL, openPrice);
            modify = true;
         }

         // Trailing Stop: move SL when profit reaches trigger
         if(InpUseTrailing && profitPoints >= InpTrailingTrigger) {
            double trailSL = bid - InpTrailingTrigger * point;
            // Only modify if new SL is better than current by at least trailing step
            if(trailSL > currentSL + InpTrailingStep * point) {
               newSL = MathMax(newSL, trailSL);
               modify = true;
            }
         }
      } else if(posType == POSITION_TYPE_SELL) {
         profitPoints = (openPrice - ask) / point;

         // Break Even: move SL to open price when profit reaches trigger
         if(InpUseBreakEven && currentSL > openPrice && profitPoints >= InpBreakEvenTrigger) {
            newSL = MathMin(newSL, openPrice);
            modify = true;
         }

         // Trailing Stop: move SL when profit reaches trigger
         if(InpUseTrailing && profitPoints >= InpTrailingTrigger) {
            double trailSL = ask + InpTrailingTrigger * point;
            // Only modify if new SL is better than current by at least trailing step
            if(trailSL < currentSL - InpTrailingStep * point) {
               newSL = MathMin(newSL, trailSL);
               modify = true;
            }
         }
      }

      // Apply modification if needed
      if(modify && newSL != currentSL) {
         if(trade.PositionModify(ticket, newSL, currentTP)) {
            Print("Position ", ticket, " modified: new SL = ", newSL);
         } else {
            Print("Failed to modify position ", ticket, ". Error: ", trade.ResultRetcode(), " - ", trade.ResultRetcodeDescription());
         }
      }
   }
}