//+------------------------------------------------------------------+
//|                                                   InsideBarEA.mq5 |
//|                                        Generated by Senior MQL5  |
//|                                                                  |
//+------------------------------------------------------------------+
#property copyright "Senior MQL5 Developer"
#property link      ""
#property version   "1.00"
#property description "EA giao dịch Inside Bar theo xu hướng cho XAU"

#include <Trade\Trade.mqh>

//--- Input parameters
input group "=== Lot Size ==="
input double InpLotSize = 0.01;              // Lot Size

input group "=== Stop Loss / Take Profit (Points) ==="
input int    InpStopLoss = 300;              // Stop Loss (points)
input int    InpTakeProfit = 600;            // Take Profit (points)

input group "=== Order Settings ==="
input ulong  InpMagicNumber = 123456;        // Magic Number
input int    InpSlippage = 10;               // Slippage / Deviation

input group "=== Trade Filters ==="
input int    InpMaxSpreadPoints = 25;        // Max Spread (points)
input int    InpMaxOrders = 1;               // Max Open Orders

input group "=== Break Even / Trailing ==="
input bool   InpUseBreakEven = true;         // Use Break Even
input int    InpBreakEvenTrigger = 150;      // BE Trigger (points)
input int    InpBreakEvenLevel = 0;          // BE Level (points, 0 = entry)
input bool   InpUseTrailing = true;          // Use Trailing Stop
input int    InpTrailingStart = 200;         // Trailing Start (points)
input int    InpTrailingStep = 50;           // Trailing Step (points)

//--- Global variables
CTrade  trade;
MqlRates lastBar;
datetime lastBarTime = 0;
bool isNewBar = false;

//+------------------------------------------------------------------+
//| Expert initialization function                                   |
//+------------------------------------------------------------------+
int OnInit()
{
   //--- Set magic number and slippage for all trades
   trade.SetExpertMagicNumber(InpMagicNumber);
   trade.SetDeviationInPoints(InpSlippage);
   trade.SetTypeFillingBySymbol(_Symbol);
   
   //--- Check input parameters
   if(InpLotSize <= 0)
   {
      Print("Lot size phải lớn hơn 0");
      return INIT_PARAMETERS_INCORRECT;
   }
   
   if(InpStopLoss <= 0 || InpTakeProfit <= 0)
   {
      Print("SL và TP phải lớn hơn 0");
      return INIT_PARAMETERS_INCORRECT;
   }
   
   //--- Initialize last bar time
   lastBarTime = 0;
   
   Print("InsideBarEA initialized successfully on ", _Symbol);
   Print("Symbol: ", _Symbol, " | Digits: ", _Digits);
   return INIT_SUCCEEDED;
}

//+------------------------------------------------------------------+
//| Expert deinitialization function                                 |
//+------------------------------------------------------------------+
void OnDeinit(const int reason)
{
   Print("InsideBarEA deinitialized. Reason: ", reason);
}

//+------------------------------------------------------------------+
//| Expert tick function                                             |
//+------------------------------------------------------------------+
void OnTick()
{
   //--- Check new bar
   if(!CheckNewBar())
      return;
   
   //--- Check if we already have max orders
   if(CountOpenOrders() >= InpMaxOrders)
      return;
   
   //--- Check spread
   if(!CheckSpread())
      return;
   
   //--- Get signal
   int signal = GetTradeSignal();
   
   //--- Execute trade if signal exists
   if(signal != 0)
   {
      if(signal > 0)
         OpenBuyOrder();
      else
         OpenSellOrder();
   }
   
   //--- Manage open positions
   ManageOpenPositions();
}

//+------------------------------------------------------------------+
//| Check if a new bar has formed                                    |
//+------------------------------------------------------------------+
bool CheckNewBar()
{
   MqlRates rates[];
   ArraySetAsSeries(rates, true);
   
   if(CopyRates(_Symbol, PERIOD_CURRENT, 0, 3, rates) < 3)
   {
      Print("Không thể copy rates");
      return false;
   }
   
   if(lastBarTime == 0)
   {
      lastBarTime = rates[0].time;
      return false;
   }
   
   if(rates[0].time != lastBarTime)
   {
      lastBarTime = rates[0].time;
      isNewBar = true;
      return true;
   }
   
   isNewBar = false;
   return false;
}

//+------------------------------------------------------------------+
//| Check if current spread is acceptable                             |
//+------------------------------------------------------------------+
bool CheckSpread()
{
   long spreadPoints = SymbolInfoInteger(_Symbol, SYMBOL_SPREAD);
   
   //--- Debug: In ra spread hiện tại
   Print("Current spread: ", spreadPoints, " points (Max allowed: ", InpMaxSpreadPoints, ")");
   
   if(spreadPoints > InpMaxSpreadPoints)
   {
      Print("Spread quá cao: ", spreadPoints, " points (Max: ", InpMaxSpreadPoints, ")");
      return false;
   }
   
   return true;
}

//+------------------------------------------------------------------+
//| Count open orders with current magic number                       |
//+------------------------------------------------------------------+
int CountOpenOrders()
{
   int count = 0;
   
   for(int i = 0; i < PositionsTotal(); i++)
   {
      ulong ticket = PositionGetTicket(i);
      if(ticket > 0)
      {
         if(PositionGetString(POSITION_SYMBOL) == _Symbol && 
            PositionGetInteger(POSITION_MAGIC) == InpMagicNumber)
         {
            count++;
         }
      }
   }
   
   return count;
}

//+------------------------------------------------------------------+
//| Determine trend direction                                         |
//+------------------------------------------------------------------+
int GetTrendDirection()
{
   //--- Sử dụng EMA 50 để xác định xu hướng
   double ema50[];
   ArraySetAsSeries(ema50, true);
   
   int emaHandle = iMA(_Symbol, PERIOD_CURRENT, 50, 0, MODE_EMA, PRICE_CLOSE);
   if(emaHandle == INVALID_HANDLE)
   {
      Print("Không thể tạo EMA handle");
      return 0;
   }
   
   if(CopyBuffer(emaHandle, 0, 0, 3, ema50) < 3)
   {
      Print("Không thể copy EMA data");
      IndicatorRelease(emaHandle);
      return 0;
   }
   
   IndicatorRelease(emaHandle);
   
   //--- So sánh giá hiện tại với EMA 50
   double currentPrice = SymbolInfoDouble(_Symbol, SYMBOL_BID);
   
   if(currentPrice > ema50[0])
      return 1;  // Uptrend
   else if(currentPrice < ema50[0])
      return -1; // Downtrend
   
   return 0; // Sideways
}

//+------------------------------------------------------------------+
//| Check if current bar is an inside bar                             |
//+------------------------------------------------------------------+
bool IsInsideBar()
{
   MqlRates rates[];
   ArraySetAsSeries(rates, true);
   
   if(CopyRates(_Symbol, PERIOD_CURRENT, 0, 3, rates) < 3)
      return false;
   
   //--- Kiểm tra nến hiện tại (rates[1] là nến đã đóng) có nằm trong nến trước (rates[2])
   if(rates[1].high <= rates[2].high && rates[1].low >= rates[2].low)
      return true;
   
   return false;
}

//+------------------------------------------------------------------+
//| Generate trading signal                                          |
//+------------------------------------------------------------------+
int GetTradeSignal()
{
   int trend = GetTrendDirection();
   
   if(trend == 0)
      return 0; // Không có xu hướng rõ ràng
   
   if(!IsInsideBar())
      return 0; // Không phải inside bar
   
   MqlRates rates[];
   ArraySetAsSeries(rates, true);
   
   if(CopyRates(_Symbol, PERIOD_CURRENT, 0, 3, rates) < 3)
      return 0;
   
   double currentPrice = SymbolInfoDouble(_Symbol, SYMBOL_BID);
   
   //--- Tín hiệu phá vỡ theo hướng xu hướng
   if(trend > 0 && currentPrice > rates[2].high)
      return 1;  // Buy signal
   
   if(trend < 0 && currentPrice < rates[2].low)
      return -1; // Sell signal
   
   return 0;
}

//+------------------------------------------------------------------+
//| Open buy order                                                   |
//+------------------------------------------------------------------+
void OpenBuyOrder()
{
   double price = SymbolInfoDouble(_Symbol, SYMBOL_ASK);
   double sl = NormalizeDouble(price - InpStopLoss * _Point, _Digits);
   double tp = NormalizeDouble(price + InpTakeProfit * _Point, _Digits);
   
   if(trade.Buy(InpLotSize, _Symbol, price, sl, tp, "InsideBar BUY"))
   {
      Print("Buy order opened successfully. Ticket: ", trade.ResultOrder());
   }
   else
   {
      Print("Buy order failed. Error: ", trade.ResultRetcode());
   }
}

//+------------------------------------------------------------------+
//| Open sell order                                                  |
//+------------------------------------------------------------------+
void OpenSellOrder()
{
   double price = SymbolInfoDouble(_Symbol, SYMBOL_BID);
   double sl = NormalizeDouble(price + InpStopLoss * _Point, _Digits);
   double tp = NormalizeDouble(price - InpTakeProfit * _Point, _Digits);
   
   if(trade.Sell(InpLotSize, _Symbol, price, sl, tp, "InsideBar SELL"))
   {
      Print("Sell order opened successfully. Ticket: ", trade.ResultOrder());
   }
   else
   {
      Print("Sell order failed. Error: ", trade.ResultRetcode());
   }
}

//+------------------------------------------------------------------+
//| Manage open positions (BE & Trailing)                            |
//+------------------------------------------------------------------+
void ManageOpenPositions()
{
   for(int i = PositionsTotal() - 1; i >= 0; i--)
   {
      ulong ticket = PositionGetTicket(i);
      if(ticket > 0)
      {
         if(PositionGetString(POSITION_SYMBOL) == _Symbol && 
            PositionGetInteger(POSITION_MAGIC) == InpMagicNumber)
         {
            ManageSinglePosition(ticket);
         }
      }
   }
}

//+------------------------------------------------------------------+
//| Manage a single position                                         |
//+------------------------------------------------------------------+
void ManageSinglePosition(ulong ticket)
{
   if(!PositionSelectByTicket(ticket))
      return;
   
   double currentSL = PositionGetDouble(POSITION_SL);
   double currentTP = PositionGetDouble(POSITION_TP);
   double openPrice = PositionGetDouble(POSITION_PRICE_OPEN);
   double currentPrice = PositionGetDouble(POSITION_PRICE_CURRENT);
   long positionType = PositionGetInteger(POSITION_TYPE);
   
   double point = _Point;
   
   //--- Break Even logic
   if(InpUseBreakEven)
   {
      double beTrigger = InpBreakEvenTrigger * point;
      double beLevel = InpBreakEvenLevel * point;
      
      if(positionType == POSITION_TYPE_BUY)
      {
         if(currentPrice - openPrice >= beTrigger)
         {
            double newSL = NormalizeDouble(openPrice + beLevel, _Digits);
            if(newSL > currentSL)
            {
               trade.PositionModify(ticket, newSL, currentTP);
            }
         }
      }
      else if(positionType == POSITION_TYPE_SELL)
      {
         if(openPrice - currentPrice >= beTrigger)
         {
            double newSL = NormalizeDouble(openPrice - beLevel, _Digits);
            if(newSL < currentSL || currentSL == 0)
            {
               trade.PositionModify(ticket, newSL, currentTP);
            }
         }
      }
   }
   
   //--- Trailing Stop logic
   if(InpUseTrailing)
   {
      double trailingStart = InpTrailingStart * point;
      double trailingStep = InpTrailingStep * point;
      
      if(positionType == POSITION_TYPE_BUY)
      {
         if(currentPrice - openPrice >= trailingStart)
         {
            double newSL = NormalizeDouble(currentPrice - trailingStart, _Digits);
            
            if(currentSL == 0 || newSL > currentSL + trailingStep)
            {
               trade.PositionModify(ticket, newSL, currentTP);
            }
         }
      }
      else if(positionType == POSITION_TYPE_SELL)
      {
         if(openPrice - currentPrice >= trailingStart)
         {
            double newSL = NormalizeDouble(currentPrice + trailingStart, _Digits);
            
            if(currentSL == 0 || newSL < currentSL - trailingStep)
            {
               trade.PositionModify(ticket, newSL, currentTP);
            }
         }
      }
   }
}
//+------------------------------------------------------------------+

