//+------------------------------------------------------------------+
//|                                                  EMA_Crossover.mq5 |
//|                        Generated by Senior MQL5 Developer         |
//+------------------------------------------------------------------+
#property copyright "Senior MQL5 Developer"
#property link      ""
#property version   "1.00"

#include <Trade\Trade.mqh>

//+------------------------------------------------------------------+
//| Input parameters                                                 |
//+------------------------------------------------------------------+
input double   InpLotSize          = 0.01;     // Lot size
input int     InpStopLoss         = 300;      // Stop Loss (points)
input int     InpTakeProfit       = 600;      // Take Profit (points)
input ulong   InpMagicNumber      = 123456;   // Magic number
input int     InpSlippage         = 10;       // Slippage / Deviation
input bool    InpBreakEvenEnable  = true;     // Enable Break Even
input int     InpBreakEvenLevel   = 150;      // Break Even activation (points)
input bool    InpTrailingEnable   = true;     // Enable Trailing Stop
input int     InpTrailingLevel    = 200;      // Trailing Stop level (points)
input int     InpMaxSpread        = 30;       // Maximum spread (points)
input int     InpMAPeriodFast     = 13;       // Fast EMA period
input int     InpMAPeriodSlow     = 34;       // Slow EMA period

//+------------------------------------------------------------------+
//| Global variables                                                 |
//+------------------------------------------------------------------+
CTrade trade;
ulong   magic_number;
int     stop_loss_points;
int     take_profit_points;
int     slippage_points;
double  lot_size;
int     handle_fast_ema;
int     handle_slow_ema;
datetime last_bar_time;

//+------------------------------------------------------------------+
//| Expert initialization function                                   |
//+------------------------------------------------------------------+
int OnInit()
{
   //--- Set magic number
   magic_number = InpMagicNumber;
   trade.SetExpertMagicNumber(magic_number);
   
   //--- Set deviation
   slippage_points = InpSlippage;
   trade.SetDeviationInPoints(slippage_points);
   
   //--- Store parameters
   lot_size = InpLotSize;
   stop_loss_points = InpStopLoss;
   take_profit_points = InpTakeProfit;
   
   //--- Create EMA handles
   handle_fast_ema = iMA(_Symbol, _Period, InpMAPeriodFast, 0, MODE_EMA, PRICE_CLOSE);
   handle_slow_ema = iMA(_Symbol, _Period, InpMAPeriodSlow, 0, MODE_EMA, PRICE_CLOSE);
   
   if(handle_fast_ema == INVALID_HANDLE || handle_slow_ema == INVALID_HANDLE)
   {
      Print("Failed to create indicator handles. Error: ", GetLastError());
      return(INIT_FAILED);
   }
   
   //--- Initialize last bar time
   last_bar_time = 0;
   
   //--- Set type filling for orders
   trade.SetTypeFilling(ORDER_FILLING_FOK);
   
   return(INIT_SUCCEEDED);
}

//+------------------------------------------------------------------+
//| Expert deinitialization function                                 |
//+------------------------------------------------------------------+
void OnDeinit(const int reason)
{
   //--- Release indicator handles
   if(handle_fast_ema != INVALID_HANDLE)
      IndicatorRelease(handle_fast_ema);
   if(handle_slow_ema != INVALID_HANDLE)
      IndicatorRelease(handle_slow_ema);
}

//+------------------------------------------------------------------+
//| Check spread limit                                               |
//+------------------------------------------------------------------+
bool CheckSpread()
{
   int spread = (int)SymbolInfoInteger(_Symbol, SYMBOL_SPREAD);
   if(spread > InpMaxSpread)
      return false;
   return true;
}

//+------------------------------------------------------------------+
//| Check if new bar appeared                                        |
//+------------------------------------------------------------------+
bool IsNewBar()
{
   datetime current_time = iTime(_Symbol, _Period, 0);
   if(current_time != last_bar_time)
   {
      last_bar_time = current_time;
      return true;
   }
   return false;
}

//+------------------------------------------------------------------+
//| Check if position exists                                         |
//+------------------------------------------------------------------+
bool PositionExists()
{
   for(int i = PositionsTotal() - 1; i >= 0; i--)
   {
      ulong ticket = PositionGetTicket(i);
      if(ticket > 0)
      {
         if(PositionGetInteger(POSITION_MAGIC) == magic_number &&
            PositionGetString(POSITION_SYMBOL) == _Symbol)
         {
            return true;
         }
      }
   }
   return false;
}

//+------------------------------------------------------------------+
//| Get position ticket                                              |
//+------------------------------------------------------------------+
ulong GetPositionTicket()
{
   for(int i = PositionsTotal() - 1; i >= 0; i--)
   {
      ulong ticket = PositionGetTicket(i);
      if(ticket > 0)
      {
         if(PositionGetInteger(POSITION_MAGIC) == magic_number &&
            PositionGetString(POSITION_SYMBOL) == _Symbol)
         {
            return ticket;
         }
      }
   }
   return 0;
}

//+------------------------------------------------------------------+
//| Open Buy Order                                                   |
//+------------------------------------------------------------------+
void OpenBuyOrder()
{
   //--- Get ask price
   double price = SymbolInfoDouble(_Symbol, SYMBOL_ASK);
   
   //--- Calculate SL and TP
   double sl = 0, tp = 0;
   if(stop_loss_points > 0)
      sl = price - stop_loss_points * _Point * 10;
   if(take_profit_points > 0)
      tp = price + take_profit_points * _Point * 10;
   
   //--- Open position
   if(trade.Buy(lot_size, _Symbol, price, sl, tp, "EMA Crossover BUY"))
   {
      if(trade.ResultRetcode() == TRADE_RETCODE_DONE)
      {
         Print("BUY position opened. Ticket: ", trade.ResultOrder());
      }
      else
      {
         Print("Failed to open BUY position. Error: ", trade.ResultRetcodeDescription());
      }
   }
   else
   {
      Print("BUY order failed. Error: ", GetLastError());
   }
}

//+------------------------------------------------------------------+
//| Open Sell Order                                                  |
//+------------------------------------------------------------------+
void OpenSellOrder()
{
   //--- Get bid price
   double price = SymbolInfoDouble(_Symbol, SYMBOL_BID);
   
   //--- Calculate SL and TP
   double sl = 0, tp = 0;
   if(stop_loss_points > 0)
      sl = price + stop_loss_points * _Point * 10;
   if(take_profit_points > 0)
      tp = price - take_profit_points * _Point * 10;
   
   //--- Open position
   if(trade.Sell(lot_size, _Symbol, price, sl, tp, "EMA Crossover SELL"))
   {
      if(trade.ResultRetcode() == TRADE_RETCODE_DONE)
      {
         Print("SELL position opened. Ticket: ", trade.ResultOrder());
      }
      else
      {
         Print("Failed to open SELL position. Error: ", trade.ResultRetcodeDescription());
      }
   }
   else
   {
      Print("SELL order failed. Error: ", GetLastError());
   }
}

//+------------------------------------------------------------------+
//| Manage Break Even                                                |
//+------------------------------------------------------------------+
void ManageBreakEven(ulong ticket, double open_price, double current_price, double current_tp)
{
   if(!InpBreakEvenEnable)
      return;
   
   double current_sl = PositionGetDouble(POSITION_SL);
   if(current_sl != 0)
      return;
   
   double profit_points;
   ENUM_POSITION_TYPE pos_type = (ENUM_POSITION_TYPE)PositionGetInteger(POSITION_TYPE);
   
   if(pos_type == POSITION_TYPE_BUY)
      profit_points = (current_price - open_price) / _Point / 10;
   else
      profit_points = (open_price - current_price) / _Point / 10;
   
   if(profit_points >= InpBreakEvenLevel)
   {
      double break_even_price = open_price;
      if(trade.PositionModify(ticket, break_even_price, current_tp))
      {
         if(trade.ResultRetcode() == TRADE_RETCODE_DONE)
            Print("Break Even applied. Ticket: ", ticket);
      }
   }
}

//+------------------------------------------------------------------+
//| Manage Trailing Stop                                             |
//+------------------------------------------------------------------+
void ManageTrailingStop(ulong ticket, double open_price, double current_price, double current_sl, double current_tp)
{
   if(!InpTrailingEnable)
      return;
   
   double profit_points;
   ENUM_POSITION_TYPE pos_type = (ENUM_POSITION_TYPE)PositionGetInteger(POSITION_TYPE);
   
   if(pos_type == POSITION_TYPE_BUY)
      profit_points = (current_price - open_price) / _Point / 10;
   else
      profit_points = (open_price - current_price) / _Point / 10;
   
   if(profit_points >= InpTrailingLevel)
   {
      double new_sl = 0;
      if(pos_type == POSITION_TYPE_BUY)
      {
         new_sl = current_price - InpTrailingLevel * _Point * 10;
         if(new_sl > current_sl)
         {
            if(trade.PositionModify(ticket, new_sl, current_tp))
            {
               if(trade.ResultRetcode() == TRADE_RETCODE_DONE)
                  Print("Trailing Stop updated. Ticket: ", ticket);
            }
         }
      }
      else
      {
         new_sl = current_price + InpTrailingLevel * _Point * 10;
         if(new_sl < current_sl || current_sl == 0)
         {
            if(trade.PositionModify(ticket, new_sl, current_tp))
            {
               if(trade.ResultRetcode() == TRADE_RETCODE_DONE)
                  Print("Trailing Stop updated. Ticket: ", ticket);
            }
         }
      }
   }
}

//+------------------------------------------------------------------+
//| Manage existing position                                         |
//+------------------------------------------------------------------+
void ManagePosition()
{
   ulong ticket = GetPositionTicket();
   if(ticket == 0)
      return;
   
   if(PositionSelectByTicket(ticket))
   {
      double open_price = PositionGetDouble(POSITION_PRICE_OPEN);
      double current_sl = PositionGetDouble(POSITION_SL);
      double current_tp = PositionGetDouble(POSITION_TP);
      
      double current_price;
      ENUM_POSITION_TYPE pos_type = (ENUM_POSITION_TYPE)PositionGetInteger(POSITION_TYPE);
      
      if(pos_type == POSITION_TYPE_BUY)
         current_price = SymbolInfoDouble(_Symbol, SYMBOL_BID);
      else
         current_price = SymbolInfoDouble(_Symbol, SYMBOL_ASK);
      
      //--- Apply Break Even
      ManageBreakEven(ticket, open_price, current_price, current_tp);
      
      //--- Apply Trailing Stop
      ManageTrailingStop(ticket, open_price, current_price, current_sl, current_tp);
   }
}

//+------------------------------------------------------------------+
//| Check signal and open order                                      |
//+------------------------------------------------------------------+
void CheckSignalAndOpen()
{
   //--- Check spread
   if(!CheckSpread())
      return;
   
   //--- Check if position exists
   if(PositionExists())
      return;
   
   //--- Check new bar
   if(!IsNewBar())
      return;
   
   //--- Get EMA values
   double ema_fast[], ema_slow[];
   ArraySetAsSeries(ema_fast, true);
   ArraySetAsSeries(ema_slow, true);
   
   if(CopyBuffer(handle_fast_ema, 0, 0, 3, ema_fast) < 3)
      return;
   if(CopyBuffer(handle_slow_ema, 0, 0, 3, ema_slow) < 3)
      return;
   
   //--- Get candlestick data
   MqlRates rates[];
   ArraySetAsSeries(rates, true);
   if(CopyRates(_Symbol, _Period, 0, 2, rates) < 2)
      return;
   
   //--- Check crossover signals
   if(ema_fast[1] <= ema_slow[1] && ema_fast[0] > ema_slow[0])
   {
      if(rates[0].close > rates[0].open)
      {
         OpenBuyOrder();
      }
   }
   else if(ema_fast[1] >= ema_slow[1] && ema_fast[0] < ema_slow[0])
   {
      if(rates[0].close < rates[0].open)
      {
         OpenSellOrder();
      }
   }
}

//+------------------------------------------------------------------+
//| Expert tick function                                             |
//+------------------------------------------------------------------+
void OnTick()
{
   //--- Check spread first
   if(!CheckSpread())
      return;
   
   //--- Manage existing position if any
   if(PositionExists())
   {
      ManagePosition();
   }
   else
   {
      //--- Check for new signal
      CheckSignalAndOpen();
   }
}