
//+------------------------------------------------------------------+
//|                                                  KeltnerMidEA.mq5|
//|                                    Generated by Senior MQL5 Dev  |
//|                                             Keltner Midline EA   |
//+------------------------------------------------------------------+
#property copyright "Generated by Senior MQL5 Dev"
#property version   "1.00"
#property description "EA giao dịch theo Keltner Midline: BUY khi giá trên midline dốc lên, SELL ngược"

#include <Trade\Trade.mqh>
#include <Indicators\Oscilators.mqh>

//--- Input Parameters
input group "=== Thông số giao dịch ==="
input double InpLotSize          = 0.01;       // Khối lượng giao dịch
input int    InpStopLoss         = 300;        // Stop Loss (points)
input int    InpTakeProfit       = 600;        // Take Profit (points)
input int    InpSlippage         = 10;         // Slippage/Deviation
input ulong  InpMagicNumber      = 24082601;   // Magic Number

input group "=== Bộ lọc giao dịch ==="
input int    InpMaxSpread        = 30;         // Spread tối đa (points)
input int    InpMaxPositions     = 1;          // Số lệnh tối đa

input group "=== Quản lý lệnh ==="
input bool   InpUseBreakEven     = true;       // Kích hoạt Break Even
input int    InpBreakEvenTrigger = 150;        // Break Even kích hoạt từ (points)
input bool   InpUseTrailingStop  = true;       // Kích hoạt Trailing Stop
input int    InpTrailingStart    = 200;        // Trailing bắt đầu từ (points)

input group "=== Tham số Keltner ==="
input int    InpKeltnerPeriod    = 20;         // Chu kỳ Keltner
input double InpKeltnerMultiplier= 2.0;        // Hệ số nhân ATR
input ENUM_TIMEFRAMES InpKeltnerTF = PERIOD_CURRENT; // Timeframe Keltner

//--- Global Variables
CTrade  trade;
int     keltnerHandle;
datetime lastBarTime = 0;
bool    isNewBar = false;

//+------------------------------------------------------------------+
//| Expert initialization function                                   |
//+------------------------------------------------------------------+
int OnInit()
{
    //--- Thiết lập thông số cho CTrade
    trade.SetExpertMagicNumber(InpMagicNumber);
    trade.SetDeviationInPoints(InpSlippage);
    trade.SetTypeFillingBySymbol(_Symbol);
    
    //--- Khởi tạo indicator Keltner Channel thủ công (custom calculation)
    keltnerHandle = INVALID_HANDLE;
    
    Print("EA Keltner Midline khởi tạo thành công!");
    return(INIT_SUCCEEDED);
}

//+------------------------------------------------------------------+
//| Expert deinitialization function                                 |
//+------------------------------------------------------------------+
void OnDeinit(const int reason)
{
    Print("EA Keltner Midline đã được gỡ bỏ. Lý do: ", reason);
}

//+------------------------------------------------------------------+
//| Expert tick function                                             |
//+------------------------------------------------------------------+
void OnTick()
{
    //--- Kiểm tra nến mới
    CheckNewBar();
    
    //--- Quản lý lệnh đang mở
    ManageOpenPositions();
    
    //--- Nếu không phải nến mới, thoát
    if(!isNewBar)
        return;
    
    //--- Kiểm tra điều kiện giao dịch
    if(!CheckTradingConditions())
        return;
    
    //--- Lấy tín hiệu giao dịch
    int signal = GetKeltnerSignal();
    
    //--- Thực hiện giao dịch theo tín hiệu
    if(signal == 1)
        ExecuteBuy();
    else if(signal == -1)
        ExecuteSell();
}

//+------------------------------------------------------------------+
//| Kiểm tra nến mới                                                 |
//+------------------------------------------------------------------+
void CheckNewBar()
{
    datetime currentBarTime = iTime(_Symbol, PERIOD_CURRENT, 0);
    
    if(currentBarTime != lastBarTime)
    {
        lastBarTime = currentBarTime;
        isNewBar = true;
    }
    else
    {
        isNewBar = false;
    }
}

//+------------------------------------------------------------------+
//| Kiểm tra điều kiện giao dịch                                     |
//+------------------------------------------------------------------+
bool CheckTradingConditions()
{
    //--- Kiểm tra spread
    long currentSpread = SymbolInfoInteger(_Symbol, SYMBOL_SPREAD);
    
    if(currentSpread > InpMaxSpread)
    {
        Print("Spread quá cao: ", currentSpread, " > ", InpMaxSpread);
        return false;
    }
    
    //--- Kiểm tra số lượng lệnh đang mở
    int openPositions = CountOpenPositions();
    
    if(openPositions >= InpMaxPositions)
    {
        Print("Đã đạt số lượng lệnh tối đa: ", openPositions, " >= ", InpMaxPositions);
        return false;
    }
    
    return true;
}

//+------------------------------------------------------------------+
//| Đếm số lệnh đang mở thuộc Magic Number                           |
//+------------------------------------------------------------------+
int CountOpenPositions()
{
    int count = 0;
    
    for(int i = PositionsTotal() - 1; i >= 0; i--)
    {
        ulong posTicket = PositionGetTicket(i);
        
        if(posTicket == 0)
            continue;
            
        if(PositionGetString(POSITION_SYMBOL) == _Symbol && 
           PositionGetInteger(POSITION_MAGIC) == InpMagicNumber)
        {
            count++;
        }
    }
    
    return count;
}

//+------------------------------------------------------------------+
//| Tính toán Keltner Channel thủ công                               |
//+------------------------------------------------------------------+
void CalculateKeltner(double &midlineCurrent[], double &midlinePrevious[])
{
    ArrayResize(midlineCurrent, 1);
    ArrayResize(midlinePrevious, 1);
    
    //--- Lấy giá đóng cửa và giá cao/thấp
    double closes[];
    double highs[];
    double lows[];
    
    ArraySetAsSeries(closes, true);
    ArraySetAsSeries(highs, true);
    ArraySetAsSeries(lows, true);
    
    int barsToCopy = InpKeltnerPeriod + 2;
    
    if(CopyClose(_Symbol, InpKeltnerTF, 0, barsToCopy, closes) < barsToCopy ||
       CopyHigh(_Symbol, InpKeltnerTF, 0, barsToCopy, highs) < barsToCopy ||
       CopyLow(_Symbol, InpKeltnerTF, 0, barsToCopy, lows) < barsToCopy)
    {
        Print("Không thể lấy dữ liệu giá. Lỗi: ", GetLastError());
        return;
    }
    
    //--- Tính Exponential Moving Average (EMA) làm midline
    double emaCurrent = 0, emaPrevious = 0;
    double emaMultiplier = 2.0 / (InpKeltnerPeriod + 1);
    
    //--- Bắt đầu với SMA cho giá trị đầu tiên
    double sumCurrent = 0, sumPrevious = 0;
    
    for(int i = 0; i < InpKeltnerPeriod; i++)
    {
        sumCurrent += closes[i];
        sumPrevious += closes[i + 1];
    }
    
    emaCurrent = sumCurrent / InpKeltnerPeriod;
    emaPrevious = sumPrevious / InpKeltnerPeriod;
    
    //--- Tính EMA cho tất cả các giá trị
    for(int i = InpKeltnerPeriod - 1; i >= 0; i--)
    {
        emaCurrent = closes[i] * emaMultiplier + emaCurrent * (1 - emaMultiplier);
    }
    
    for(int i = InpKeltnerPeriod; i >= 1; i--)
    {
        emaPrevious = closes[i] * emaMultiplier + emaPrevious * (1 - emaMultiplier);
    }
    
    //--- Tính ATR
    double atrSum = 0;
    
    for(int i = 0; i < InpKeltnerPeriod; i++)
    {
        double trueRange = 0;
        double highLow = highs[i] - lows[i];
        double highClosePrev = MathAbs(highs[i] - closes[i + 1]);
        double lowClosePrev = MathAbs(lows[i] - closes[i + 1]);
        
        trueRange = MathMax(highLow, MathMax(highClosePrev, lowClosePrev));
        atrSum += trueRange;
    }
    
    double atrValue = atrSum / InpKeltnerPeriod;
    
    midlineCurrent[0] = emaCurrent;
    midlinePrevious[0] = emaPrevious;
}

//+------------------------------------------------------------------+
//| Lấy tín hiệu từ Keltner Midline                                  |
//+------------------------------------------------------------------+
int GetKeltnerSignal()
{
    double midlineCurrent[];
    double midlinePrevious[];
    
    //--- Tính toán Keltner Channel thủ công
    CalculateKeltner(midlineCurrent, midlinePrevious);
    
    if(ArraySize(midlineCurrent) == 0 || ArraySize(midlinePrevious) == 0)
        return 0;
    
    //--- Lấy giá hiện tại
    double currentPrice = SymbolInfoDouble(_Symbol, SYMBOL_BID);
    
    //--- Kiểm tra điều kiện Midline dốc lên/xuống
    bool midlineRising = (midlineCurrent[0] > midlinePrevious[0]);
    bool midlineFalling = (midlineCurrent[0] < midlinePrevious[0]);
    
    //--- Tín hiệu BUY: giá trên midline và midline dốc lên
    if(currentPrice > midlineCurrent[0] && midlineRising)
        return 1;
    
    //--- Tín hiệu SELL: giá dưới midline và midline dốc xuống
    if(currentPrice < midlineCurrent[0] && midlineFalling)
        return -1;
    
    return 0;
}

//+------------------------------------------------------------------+
//| Thực hiện lệnh BUY                                               |
//+------------------------------------------------------------------+
void ExecuteBuy()
{
    double price = SymbolInfoDouble(_Symbol, SYMBOL_ASK);
    double sl = NormalizeDouble(price - InpStopLoss * _Point, _Digits);
    double tp = NormalizeDouble(price + InpTakeProfit * _Point, _Digits);
    
    if(trade.Buy(InpLotSize, _Symbol, price, sl, tp, "Keltner Midline BUY"))
    {
        Print("Lệnh BUY thành công: Ticket=", trade.ResultOrder(), 
              " SL=", sl, " TP=", tp);
    }
    else
    {
        Print("Lỗi khi mở lệnh BUY: ", trade.ResultRetcode(), " - ", trade.ResultRetcodeDescription());
    }
}

//+------------------------------------------------------------------+
//| Thực hiện lệnh SELL                                              |
//+------------------------------------------------------------------+
void ExecuteSell()
{
    double price = SymbolInfoDouble(_Symbol, SYMBOL_BID);
    double sl = NormalizeDouble(price + InpStopLoss * _Point, _Digits);
    double tp = NormalizeDouble(price - InpTakeProfit * _Point, _Digits);
    
    if(trade.Sell(InpLotSize, _Symbol, price, sl, tp, "Keltner Midline SELL"))
    {
        Print("Lệnh SELL thành công: Ticket=", trade.ResultOrder(), 
              " SL=", sl, " TP=", tp);
    }
    else
    {
        Print("Lỗi khi mở lệnh SELL: ", trade.ResultRetcode(), " - ", trade.ResultRetcodeDescription());
    }
}

//+------------------------------------------------------------------+
//| Quản lý lệnh đang mở (Break Even & Trailing Stop)               |
//+------------------------------------------------------------------+
void ManageOpenPositions()
{
    if(!InpUseBreakEven && !InpUseTrailingStop)
        return;
    
    for(int i = PositionsTotal() - 1; i >= 0; i--)
    {
        ulong posTicket = PositionGetTicket(i);
        
        if(posTicket == 0)
            continue;
            
        //--- Chỉ quản lý lệnh thuộc symbol và magic number của EA
        if(PositionGetString(POSITION_SYMBOL) != _Symbol || 
           PositionGetInteger(POSITION_MAGIC) != InpMagicNumber)
            continue;
        
        double posOpenPrice = PositionGetDouble(POSITION_PRICE_OPEN);
        double posSL = PositionGetDouble(POSITION_SL);
        double posTP = PositionGetDouble(POSITION_TP);
        long posType = PositionGetInteger(POSITION_TYPE);
        double currentPrice = (posType == POSITION_TYPE_BUY) ? 
                              SymbolInfoDouble(_Symbol, SYMBOL_BID) : 
                              SymbolInfoDouble(_Symbol, SYMBOL_ASK);
        
        //--- Break Even
        if(InpUseBreakEven)
            ApplyBreakEven(posTicket, posType, posOpenPrice, posSL, currentPrice);
        
        //--- Trailing Stop
        if(InpUseTrailingStop)
            ApplyTrailingStop(posTicket, posType, posOpenPrice, posSL, currentPrice);
    }
}

//+------------------------------------------------------------------+
//| Áp dụng Break Even                                               |
//+------------------------------------------------------------------+
void ApplyBreakEven(ulong posTicket, long posType, double openPrice, 
                    double currentSL, double currentPrice)
{
    if(currentSL == 0 || currentSL == 0.0)
        return;
    
    double profitPoints = (posType == POSITION_TYPE_BUY) ? 
                          (currentPrice - openPrice) / _Point : 
                          (openPrice - currentPrice) / _Point;
    
    if(profitPoints >= InpBreakEvenTrigger)
    {
        double newSL = openPrice;
        
        //--- Chỉ cập nhật nếu SL mới tốt hơn SL hiện tại
        if((posType == POSITION_TYPE_BUY && newSL > currentSL) ||
           (posType == POSITION_TYPE_SELL && newSL < currentSL))
        {
            if(trade.PositionModify(posTicket, newSL, PositionGetDouble(POSITION_TP)))
            {
                Print("Break Even áp dụng cho lệnh #", posTicket, " SL mới=", newSL);
            }
        }
    }
}

//+------------------------------------------------------------------+
//| Áp dụng Trailing Stop                                            |
//+------------------------------------------------------------------+
void ApplyTrailingStop(ulong posTicket, long posType, double openPrice, 
                       double currentSL, double currentPrice)
{
    double profitPoints = (posType == POSITION_TYPE_BUY) ? 
                          (currentPrice - openPrice) / _Point : 
                          (openPrice - currentPrice) / _Point;
    
    if(profitPoints >= InpTrailingStart)
    {
        double newSL = 0;
        
        if(posType == POSITION_TYPE_BUY)
        {
            newSL = currentPrice - InpTrailingStart * _Point;
            
            if(newSL > currentSL)
            {
                if(trade.PositionModify(posTicket, newSL, PositionGetDouble(POSITION_TP)))
                {
                    Print("Trailing Stop cập nhật cho lệnh #", posTicket, " SL mới=", newSL);
                }
            }
        }
        else if(posType == POSITION_TYPE_SELL)
        {
            newSL = currentPrice + InpTrailingStart * _Point;
            
            if(newSL < currentSL)
            {
                if(trade.PositionModify(posTicket, newSL, PositionGetDouble(POSITION_TP)))
                {
                    Print("Trailing Stop cập nhật cho lệnh #", posTicket, " SL mới=", newSL);
                }
            }
        }
    }
}

//+------------------------------------------------------------------+