//+------------------------------------------------------------------+
//|                                              PullbackThreeBar.mq5|
//|                                    Generated by Senior MQL5 Dev  |
//+------------------------------------------------------------------+
#property copyright "Senior MQL5 Developer"
#property version   "1.00"
#property description "Pullback Three Bar EA: BUY on three higher closes, SELL on three lower closes"

#include <Trade\Trade.mqh>

//--- Input Parameters
input group "=== Trade Settings ==="
input double InpLotSize        = 0.01;     // Lot Size
input int    InpStopLoss       = 300;      // Stop Loss (points)
input int    InpTakeProfit     = 600;      // Take Profit (points)
input ulong  InpMagicNumber    = 20240001; // Magic Number
input int    InpSlippage       = 10;       // Slippage / Deviation

input group "=== Risk Filters ==="
input int    InpMaxSpread      = 30;       // Max Spread (points)
input int    InpMaxPositions   = 1;        // Max Concurrent Positions

input group "=== Trade Management ==="
input bool   InpUseBreakEven   = true;     // Enable Break Even
input int    InpBreakEvenStart = 150;      // Break Even Trigger (points)
input bool   InpUseTrailing    = true;     // Enable Trailing Stop
input int    InpTrailingStart  = 200;      // Trailing Trigger (points)
input int    InpTrailingStep   = 50;       // Trailing Step (points)

//--- Global Variables
CTrade  trade;
bool    g_isNewBar = false;
datetime g_lastBarTime = 0;

//+------------------------------------------------------------------+
//| Expert initialization function                                   |
//+------------------------------------------------------------------+
int OnInit()
{
    // Validate inputs
    if(InpLotSize <= 0)
    {
        Print("Invalid Lot Size");
        return INIT_PARAMETERS_INCORRECT;
    }
    if(InpStopLoss <= 0 || InpTakeProfit <= 0)
    {
        Print("Invalid SL/TP");
        return INIT_PARAMETERS_INCORRECT;
    }
    if(InpMaxSpread <= 0)
    {
        Print("Invalid Max Spread");
        return INIT_PARAMETERS_INCORRECT;
    }

    // Setup Trade object
    trade.SetExpertMagicNumber(InpMagicNumber);
    trade.SetDeviationInPoints(InpSlippage);
    trade.SetAsyncMode(false);

    // Initialize last bar time
    g_lastBarTime = iTime(_Symbol, PERIOD_CURRENT, 0);

    Print("PullbackThreeBar EA initialized on ", _Symbol, " ", EnumToString(PERIOD_CURRENT));
    return INIT_SUCCEEDED;
}

//+------------------------------------------------------------------+
//| Expert deinitialization function                                 |
//+------------------------------------------------------------------+
void OnDeinit(const int reason)
{
    Print("PullbackThreeBar EA deinitialized. Reason: ", reason);
}

//+------------------------------------------------------------------+
//| Expert tick function                                             |
//+------------------------------------------------------------------+
void OnTick()
{
    //--- 1. Check for new bar
    g_isNewBar = IsNewBar();
    if(!g_isNewBar)
        return;

    //--- 2. Check spread filter
    if(!CheckSpreadFilter())
        return;

    //--- 3. Check existing positions
    if(CountPositions() >= InpMaxPositions)
        return;

    //--- 4. Calculate trading signals
    int signal = GetTradeSignal();

    //--- 5. Execute trades based on signal
    if(signal > 0)
    {
        OpenBuyPosition();
    }
    else if(signal < 0)
    {
        OpenSellPosition();
    }

    //--- 6. Manage existing positions (BE & Trailing)
    if(InpUseBreakEven)
        ManageBreakEven();
    if(InpUseTrailing)
        ManageTrailingStop();
}

//+------------------------------------------------------------------+
//| Check if we have a new bar                                       |
//+------------------------------------------------------------------+
bool IsNewBar()
{
    datetime currentBarTime = iTime(_Symbol, PERIOD_CURRENT, 0);
    if(currentBarTime != g_lastBarTime)
    {
        g_lastBarTime = currentBarTime;
        return true;
    }
    return false;
}

//+------------------------------------------------------------------+
//| Check spread filter                                              |
//+------------------------------------------------------------------+
bool CheckSpreadFilter()
{
    long spreadPoints = SymbolInfoInteger(_Symbol, SYMBOL_SPREAD);
    return (spreadPoints <= InpMaxSpread);
}

//+------------------------------------------------------------------+
//| Count open positions for this symbol/magic                       |
//+------------------------------------------------------------------+
int CountPositions()
{
    int count = 0;
    for(int i = PositionsTotal() - 1; i >= 0; i--)
    {
        ulong ticket = PositionGetTicket(i);
        if(ticket == 0)
            continue;
        if(PositionSelectByTicket(ticket))
        {
            if(PositionGetString(POSITION_SYMBOL) == _Symbol &&
               PositionGetInteger(POSITION_MAGIC) == InpMagicNumber)
            {
                count++;
            }
        }
    }
    return count;
}

//+------------------------------------------------------------------+
//| Generate trading signal based on three bar pattern               |
//| Returns: 1 = BUY, -1 = SELL, 0 = No signal                       |
//+------------------------------------------------------------------+
int GetTradeSignal()
{
    // Need at least 3 completed bars (shift 1, 2, 3)
    // Bar 1 = most recent completed bar
    // Bar 2 = previous bar
    // Bar 3 = oldest bar in the pattern

    double close1 = iClose(_Symbol, PERIOD_CURRENT, 1);
    double close2 = iClose(_Symbol, PERIOD_CURRENT, 2);
    double close3 = iClose(_Symbol, PERIOD_CURRENT, 3);

    if(close1 == 0 || close2 == 0 || close3 == 0)
        return 0;

    // BUY: Three bars with higher closes (close1 > close2 > close3)
    if(close1 > close2 && close2 > close3)
        return 1;

    // SELL: Three bars with lower closes (close1 < close2 < close3)
    if(close1 < close2 && close2 < close3)
        return -1;

    return 0;
}

//+------------------------------------------------------------------+
//| Open BUY position                                                |
//+------------------------------------------------------------------+
void OpenBuyPosition()
{
    double price = SymbolInfoDouble(_Symbol, SYMBOL_ASK);
    double sl = price - InpStopLoss * _Point;
    double tp = price + InpTakeProfit * _Point;

    // Normalize price values
    price = NormalizeDouble(price, _Digits);
    sl = NormalizeDouble(sl, _Digits);
    tp = NormalizeDouble(tp, _Digits);

    if(!trade.Buy(InpLotSize, _Symbol, price, sl, tp, "Pullback ThreeBar BUY"))
    {
        Print("BUY order failed. Error: ", trade.ResultRetcode(), " - ", trade.ResultRetcodeDescription());
    }
    else
    {
        Print("BUY order opened at ", price, " SL: ", sl, " TP: ", tp);
    }
}

//+------------------------------------------------------------------+
//| Open SELL position                                               |
//+------------------------------------------------------------------+
void OpenSellPosition()
{
    double price = SymbolInfoDouble(_Symbol, SYMBOL_BID);
    double sl = price + InpStopLoss * _Point;
    double tp = price - InpTakeProfit * _Point;

    // Normalize price values
    price = NormalizeDouble(price, _Digits);
    sl = NormalizeDouble(sl, _Digits);
    tp = NormalizeDouble(tp, _Digits);

    if(!trade.Sell(InpLotSize, _Symbol, price, sl, tp, "Pullback ThreeBar SELL"))
    {
        Print("SELL order failed. Error: ", trade.ResultRetcode(), " - ", trade.ResultRetcodeDescription());
    }
    else
    {
        Print("SELL order opened at ", price, " SL: ", sl, " TP: ", tp);
    }
}

//+------------------------------------------------------------------+
//| Manage Break Even for open positions                             |
//+------------------------------------------------------------------+
void ManageBreakEven()
{
    for(int i = PositionsTotal() - 1; i >= 0; i--)
    {
        ulong ticket = PositionGetTicket(i);
        if(ticket == 0)
            continue;

        if(!PositionSelectByTicket(ticket))
            continue;

        // Filter by symbol and magic
        if(PositionGetString(POSITION_SYMBOL) != _Symbol)
            continue;
        if(PositionGetInteger(POSITION_MAGIC) != InpMagicNumber)
            continue;

        double openPrice = PositionGetDouble(POSITION_PRICE_OPEN);
        double currentSl = PositionGetDouble(POSITION_SL);
        long positionType = PositionGetInteger(POSITION_TYPE);

        if(positionType == POSITION_TYPE_BUY)
        {
            double currentPrice = SymbolInfoDouble(_Symbol, SYMBOL_BID);
            double breakEvenPrice = openPrice + InpBreakEvenStart * _Point;

            // Check if price has moved enough for break even
            if(currentPrice >= breakEvenPrice && currentSl < openPrice)
            {
                double newSl = NormalizeDouble(openPrice, _Digits);
                if(!trade.PositionModify(ticket, newSl, PositionGetDouble(POSITION_TP)))
                {
                    Print("Break Even modify failed for BUY #", ticket, ". Error: ", trade.ResultRetcode());
                }
                else
                {
                    Print("Break Even applied to BUY #", ticket, " at ", newSl);
                }
            }
        }
        else if(positionType == POSITION_TYPE_SELL)
        {
            double currentPrice = SymbolInfoDouble(_Symbol, SYMBOL_ASK);
            double breakEvenPrice = openPrice - InpBreakEvenStart * _Point;

            // Check if price has moved enough for break even
            if(currentPrice <= breakEvenPrice && currentSl > openPrice)
            {
                double newSl = NormalizeDouble(openPrice, _Digits);
                if(!trade.PositionModify(ticket, newSl, PositionGetDouble(POSITION_TP)))
                {
                    Print("Break Even modify failed for SELL #", ticket, ". Error: ", trade.ResultRetcode());
                }
                else
                {
                    Print("Break Even applied to SELL #", ticket, " at ", newSl);
                }
            }
        }
    }
}

//+------------------------------------------------------------------+
//| Manage Trailing Stop for open positions                          |
//+------------------------------------------------------------------+
void ManageTrailingStop()
{
    for(int i = PositionsTotal() - 1; i >= 0; i--)
    {
        ulong ticket = PositionGetTicket(i);
        if(ticket == 0)
            continue;

        if(!PositionSelectByTicket(ticket))
            continue;

        // Filter by symbol and magic
        if(PositionGetString(POSITION_SYMBOL) != _Symbol)
            continue;
        if(PositionGetInteger(POSITION_MAGIC) != InpMagicNumber)
            continue;

        double openPrice = PositionGetDouble(POSITION_PRICE_OPEN);
        double currentSl = PositionGetDouble(POSITION_SL);
        long positionType = PositionGetInteger(POSITION_TYPE);

        if(positionType == POSITION_TYPE_BUY)
        {
            double currentPrice = SymbolInfoDouble(_Symbol, SYMBOL_BID);
            double trailingTrigger = openPrice + InpTrailingStart * _Point;

            if(currentPrice >= trailingTrigger)
            {
                double newSl = currentPrice - InpTrailingStep * _Point;
                newSl = NormalizeDouble(newSl, _Digits);

                // Only move SL up
                if(newSl > currentSl)
                {
                    if(!trade.PositionModify(ticket, newSl, PositionGetDouble(POSITION_TP)))
                    {
                        Print("Trailing modify failed for BUY #", ticket, ". Error: ", trade.ResultRetcode());
                    }
                    else
                    {
                        Print("Trailing applied to BUY #", ticket, " new SL: ", newSl);
                    }
                }
            }
        }
        else if(positionType == POSITION_TYPE_SELL)
        {
            double currentPrice = SymbolInfoDouble(_Symbol, SYMBOL_ASK);
            double trailingTrigger = openPrice - InpTrailingStart * _Point;

            if(currentPrice <= trailingTrigger)
            {
                double newSl = currentPrice + InpTrailingStep * _Point;
                newSl = NormalizeDouble(newSl, _Digits);

                // Only move SL down
                if(newSl < currentSl)
                {
                    if(!trade.PositionModify(ticket, newSl, PositionGetDouble(POSITION_TP)))
                    {
                        Print("Trailing modify failed for SELL #", ticket, ". Error: ", trade.ResultRetcode());
                    }
                    else
                    {
                        Print("Trailing applied to SELL #", ticket, " new SL: ", newSl);
                    }
                }
            }
        }
    }
}
//+------------------------------------------------------------------+