//+------------------------------------------------------------------+
//|                                                     ADX_EMA_EA.mq5 |
//|                        Generated by Senior MQL5 Developer        |
//|                                                                  |
//+------------------------------------------------------------------+
#property copyright "Senior MQL5 Developer"
#property link      ""
#property version   "1.00"
#property description "EA giao dịch dựa trên tín hiệu ADX/DMI kết hợp độ dốc EMA50"
#property description "Chỉ giao dịch khi có sự đồng thuận giữa DMI và EMA50"

#include <Trade\Trade.mqh>

//+------------------------------------------------------------------+
//| Input Parameters                                                 |
//+------------------------------------------------------------------+
input group "=== Thông số giao dịch ==="
input double InpLotSize = 0.01;              // Khối lượng giao dịch (Lot)
input ulong  InpMagicNumber = 2024001;       // Mã nhận diện EA (Magic Number)
input int    InpSlippage = 10;               // Độ trượt giá tối đa (points)

input group "=== Thông số EMA ==="
input int InpEmaPeriod = 50;                 // Chu kỳ EMA

input group "=== Thông số DMI/ADX ==="
input int InpAdxPeriod = 14;                 // Chu kỳ ADX/DMI

input group "=== Quản lý lệnh ==="
input int InpStopLoss = 300;                 // Stop Loss (points)
input int InpTakeProfit = 600;               // Take Profit (points)
input bool InpUseBreakEven = true;           // Sử dụng Break Even
input int InpBreakEvenStartPoints = 150;     // Điểm kích hoạt Break Even
input bool InpUseTrailingStop = true;        // Sử dụng Trailing Stop
input int InpTrailingStartPoints = 200;      // Điểm kích hoạt Trailing Stop
input int InpTrailingDistancePoints = 0;     // Khoảng cách Trailing Stop (points, 0 = tự động dùng 50% khoảng cách hiện tại)

input group "=== Bộ lọc Spread ==="
input int InpMaxSpreadPoints = 30;           // Spread tối đa cho phép (points)

input group "=== Giới hạn lệnh ==="
input int InpMaxOpenPositions = 1;           // Số lệnh mở tối đa

//+------------------------------------------------------------------+
//| Global Variables                                                 |
//+------------------------------------------------------------------+
CTrade  trade;
int     emaHandle;
int     adxHandle;
datetime lastBarTime = 0;
string  g_symbol;
int     g_digits;

//+------------------------------------------------------------------+
//| Expert initialization function                                   |
//+------------------------------------------------------------------+
int OnInit()
{
    // Thiết lập thông số giao dịch
    g_symbol = _Symbol;
    g_digits = (int)_Digits;
    
    trade.SetExpertMagicNumber(InpMagicNumber);
    trade.SetDeviationInPoints(InpSlippage);
    trade.SetTypeFillingBySymbol(g_symbol);
    
    // Khởi tạo indicator handles
    emaHandle = iMA(g_symbol, PERIOD_CURRENT, InpEmaPeriod, 0, MODE_EMA, PRICE_CLOSE);
    if(emaHandle == INVALID_HANDLE)
    {
        Print("Lỗi khởi tạo EMA indicator: ", GetLastError());
        return INIT_FAILED;
    }
    
    adxHandle = iADX(g_symbol, PERIOD_CURRENT, InpAdxPeriod);
    if(adxHandle == INVALID_HANDLE)
    {
        Print("Lỗi khởi tạo ADX indicator: ", GetLastError());
        return INIT_FAILED;
    }
    
    // Khởi tạo lastBarTime
    lastBarTime = iTime(g_symbol, PERIOD_CURRENT, 0);
    
    Print("EA khởi tạo thành công!");
    Print("Symbol: ", g_symbol, " | Magic: ", InpMagicNumber);
    Print("SL: ", InpStopLoss, " points | TP: ", InpTakeProfit, " points");
    
    return INIT_SUCCEEDED;
}

//+------------------------------------------------------------------+
//| Expert deinitialization function                                 |
//+------------------------------------------------------------------+
void OnDeinit(const int reason)
{
    // Giải phóng indicator handles
    if(emaHandle != INVALID_HANDLE)
        IndicatorRelease(emaHandle);
    
    if(adxHandle != INVALID_HANDLE)
        IndicatorRelease(adxHandle);
    
    Print("EA đã được gỡ bỏ. Lý do: ", reason);
}

//+------------------------------------------------------------------+
//| Expert tick function                                             |
//+------------------------------------------------------------------+
void OnTick()
{
    //=== BƯỚC 1: Quản lý lệnh đang mở ===
    ManageOpenPositions();
    
    //=== BƯỚC 2: Kiểm tra số lượng lệnh đang mở ===
    if(CountOpenPositions() >= InpMaxOpenPositions)
        return; // Đã đạt giới hạn, không mở thêm
    
    //=== BƯỚC 3: Kiểm tra nến mới ===
    if(!IsNewBar())
        return; // Chưa có nến mới
    
    //=== BƯỚC 4: Kiểm tra spread ===
    if(GetCurrentSpread() > InpMaxSpreadPoints)
        return; // Spread quá cao
    
    //=== BƯỚC 5: Kiểm tra tín hiệu ===
    int signal = GetTradingSignal();
    
    //=== BƯỚC 6: Mở lệnh nếu có tín hiệu ===
    if(signal == 1) // BUY signal
    {
        OpenBuyPosition();
    }
    else if(signal == -1) // SELL signal
    {
        OpenSellPosition();
    }
}

//+------------------------------------------------------------------+
//| Kiểm tra nến mới                                                 |
//+------------------------------------------------------------------+
bool IsNewBar()
{
    datetime currentBarTime = iTime(g_symbol, PERIOD_CURRENT, 0);
    
    if(currentBarTime != lastBarTime)
    {
        lastBarTime = currentBarTime;
        return true;
    }
    
    return false;
}

//+------------------------------------------------------------------+
//| Đếm số lệnh đang mở thuộc Magic Number                          |
//+------------------------------------------------------------------+
int CountOpenPositions()
{
    int count = 0;
    
    for(int i = PositionsTotal() - 1; i >= 0; i--)
    {
        ulong positionTicket = PositionGetTicket(i);
        if(positionTicket > 0)
        {
            if(PositionGetInteger(POSITION_MAGIC) == InpMagicNumber && 
               PositionGetString(POSITION_SYMBOL) == g_symbol)
            {
                count++;
            }
        }
    }
    
    return count;
}

//+------------------------------------------------------------------+
//| Lấy spread hiện tại (points)                                     |
//+------------------------------------------------------------------+
double GetCurrentSpread()
{
    double ask = SymbolInfoDouble(g_symbol, SYMBOL_ASK);
    double bid = SymbolInfoDouble(g_symbol, SYMBOL_BID);
    double spread = (ask - bid) / _Point;
    return spread;
}

//+------------------------------------------------------------------+
//| Đọc tín hiệu giao dịch                                           |
//| Trả về: 1 = BUY, -1 = SELL, 0 = Không tín hiệu                   |
//+------------------------------------------------------------------+
int GetTradingSignal()
{
    // Đảm bảo đủ dữ liệu để tính toán
    if(Bars(g_symbol, PERIOD_CURRENT) < MathMax(InpEmaPeriod, InpAdxPeriod) + 5)
        return 0;
    
    // Lấy giá trị +DI và -DI từ nến đã đóng (shift 1)
    double plusDI[1];
    double minusDI[1];
    
    // Lấy giá trị EMA50 từ nến đã đóng (shift 1 và shift 2)
    double ema50[2];
    
    // Copy dữ liệu từ indicator buffers
    if(CopyBuffer(adxHandle, 1, 1, 1, plusDI) <= 0) // +DI buffer
        return 0;
    
    if(CopyBuffer(adxHandle, 2, 1, 1, minusDI) <= 0) // -DI buffer
        return 0;
    
    if(CopyBuffer(emaHandle, 0, 1, 2, ema50) <= 0) // EMA buffer
        return 0;
    
    // Kiểm tra tín hiệu BUY
    if(plusDI[0] > minusDI[0] && ema50[0] > ema50[1])
    {
        return 1; // BUY signal
    }
    
    // Kiểm tra tín hiệu SELL
    if(minusDI[0] > plusDI[0] && ema50[0] < ema50[1])
    {
        return -1; // SELL signal
    }
    
    return 0; // Không có tín hiệu
}

//+------------------------------------------------------------------+
//| Mở lệnh BUY                                                      |
//+------------------------------------------------------------------+
void OpenBuyPosition()
{
    double price = SymbolInfoDouble(g_symbol, SYMBOL_ASK);
    double sl = price - InpStopLoss * _Point;
    double tp = price + InpTakeProfit * _Point;
    
    // Chuẩn hóa giá
    sl = NormalizeDouble(sl, g_digits);
    tp = NormalizeDouble(tp, g_digits);
    
    if(trade.Buy(InpLotSize, g_symbol, price, sl, tp, "ADX/EMA BUY"))
    {
        Print("Đã mở lệnh BUY thành công. Giá: ", price, " | SL: ", sl, " | TP: ", tp);
    }
    else
    {
        Print("Lỗi mở lệnh BUY: ", trade.ResultRetcode(), " - ", trade.ResultRetcodeDescription());
    }
}

//+------------------------------------------------------------------+
//| Mở lệnh SELL                                                     |
//+------------------------------------------------------------------+
void OpenSellPosition()
{
    double price = SymbolInfoDouble(g_symbol, SYMBOL_BID);
    double sl = price + InpStopLoss * _Point;
    double tp = price - InpTakeProfit * _Point;
    
    // Chuẩn hóa giá
    sl = NormalizeDouble(sl, g_digits);
    tp = NormalizeDouble(tp, g_digits);
    
    if(trade.Sell(InpLotSize, g_symbol, price, sl, tp, "ADX/EMA SELL"))
    {
        Print("Đã mở lệnh SELL thành công. Giá: ", price, " | SL: ", sl, " | TP: ", tp);
    }
    else
    {
        Print("Lỗi mở lệnh SELL: ", trade.ResultRetcode(), " - ", trade.ResultRetcodeDescription());
    }
}

//+------------------------------------------------------------------+
//| Quản lý lệnh đang mở (Break Even & Trailing Stop)                |
//+------------------------------------------------------------------+
void ManageOpenPositions()
{
    for(int i = PositionsTotal() - 1; i >= 0; i--)
    {
        ulong positionTicket = PositionGetTicket(i);
        if(positionTicket <= 0)
            continue;
        
        // Kiểm tra lệnh thuộc Magic Number và Symbol
        if(PositionGetInteger(POSITION_MAGIC) != InpMagicNumber)
            continue;
        
        if(PositionGetString(POSITION_SYMBOL) != g_symbol)
            continue;
        
        // Lấy thông tin lệnh
        long positionType = PositionGetInteger(POSITION_TYPE);
        double currentSL = PositionGetDouble(POSITION_SL);
        double currentTP = PositionGetDouble(POSITION_TP);
        double openPrice = PositionGetDouble(POSITION_PRICE_OPEN);
        double currentPrice = PositionGetDouble(POSITION_PRICE_CURRENT);
        double profitPoints = 0;
        
        // Tính lợi nhuận hiện tại theo points
        if(positionType == POSITION_TYPE_BUY)
        {
            profitPoints = (currentPrice - openPrice) / _Point;
        }
        else if(positionType == POSITION_TYPE_SELL)
        {
            profitPoints = (openPrice - currentPrice) / _Point;
        }
        
        //=== BREAK EVEN ===
        if(InpUseBreakEven && profitPoints >= InpBreakEvenStartPoints)
        {
            ApplyBreakEven(positionTicket, positionType, openPrice, currentSL);
        }
        
        //=== TRAILING STOP ===
        if(InpUseTrailingStop && profitPoints >= InpTrailingStartPoints)
        {
            ApplyTrailingStop(positionTicket, positionType, currentPrice, currentSL);
        }
    }
}

//+------------------------------------------------------------------+
//| Áp dụng Break Even                                               |
//+------------------------------------------------------------------+
void ApplyBreakEven(ulong ticket, long positionType, double openPrice, double currentSL)
{
    bool modifyNeeded = false;
    double newSL = currentSL;
    
    if(positionType == POSITION_TYPE_BUY)
    {
        // Đối với lệnh BUY: Di chuyển SL về giá mở lệnh nếu SL thấp hơn
        if(currentSL < openPrice)
        {
            newSL = openPrice;
            modifyNeeded = true;
        }
    }
    else if(positionType == POSITION_TYPE_SELL)
    {
        // Đối với lệnh SELL: Di chuyển SL về giá mở lệnh nếu SL cao hơn
        if(currentSL > openPrice || currentSL == 0)
        {
            newSL = openPrice;
            modifyNeeded = true;
        }
    }
    
    if(modifyNeeded)
    {
        newSL = NormalizeDouble(newSL, g_digits);
        if(trade.PositionModify(ticket, newSL, PositionGetDouble(POSITION_TP)))
        {
            Print("Đã di chuyển SL về hòa vốn cho lệnh #", ticket);
        }
    }
}

//+------------------------------------------------------------------+
//| Áp dụng Trailing Stop                                            |
//+------------------------------------------------------------------+
void ApplyTrailingStop(ulong ticket, long positionType, double currentPrice, double currentSL)
{
    bool modifyNeeded = false;
    double newSL = currentSL;
    
    // Xác định khoảng cách trailing
    double trailingDistance = InpTrailingDistancePoints;
    if(trailingDistance <= 0)
    {
        // Nếu không set, dùng 50% khoảng cách từ giá vào đến giá hiện tại
        trailingDistance = 0; // Không áp dụng nếu không được cấu hình
    }
    
    if(trailingDistance <= 0)
        return;
    
    if(positionType == POSITION_TYPE_BUY)
    {
        // Đối với lệnh BUY: SL mới = Giá hiện tại - Trailing Distance
        double potentialSL = currentPrice - trailingDistance * _Point;
        potentialSL = NormalizeDouble(potentialSL, g_digits);
        
        // Chỉ di chuyển SL lên (không bao giờ giảm SL của lệnh BUY)
        if(potentialSL > currentSL)
        {
            newSL = potentialSL;
            modifyNeeded = true;
        }
    }
    else if(positionType == POSITION_TYPE_SELL)
    {
        // Đối với lệnh SELL: SL mới = Giá hiện tại + Trailing Distance
        double potentialSL = currentPrice + trailingDistance * _Point;
        potentialSL = NormalizeDouble(potentialSL, g_digits);
        
        // Chỉ di chuyển SL xuống (không bao giờ tăng SL của lệnh SELL)
        if(potentialSL < currentSL || currentSL == 0)
        {
            newSL = potentialSL;
            modifyNeeded = true;
        }
    }
    
    if(modifyNeeded)
    {
        if(trade.PositionModify(ticket, newSL, PositionGetDouble(POSITION_TP)))
        {
            Print("Đã di chuyển Trailing Stop cho lệnh #", ticket, " | SL mới: ", newSL);
        }
    }
}

//+------------------------------------------------------------------+