//+------------------------------------------------------------------+
//|                                               DonchianBreakout.mq5|
//|                                    Generated by Senior MQL5 Dev  |
//+------------------------------------------------------------------+
#property copyright "Copyright 2026, Senior MQL5 Developer"
#property version   "1.10"
#property strict

#include <Trade\Trade.mqh>

//--- Input parameters
input group "=== Trade Settings ==="
input double   InpLotSize          = 0.01;          // Lot Size
input ulong    InpMagicNumber      = 123456;        // Magic Number
input int      InpSlippage         = 10;            // Slippage (points)

input group "=== Donchian Parameters ==="
input int      InpDonchianPeriod   = 10;            // Donchian Period
input int      InpMaxSpread        = 30;            // Max Spread (points)

input group "=== Risk Management ==="
input int      InpStopLoss         = 300;           // Stop Loss (points)
input int      InpTakeProfit       = 600;           // Take Profit (points)

input group "=== Break Even & Trailing ==="
input bool     InpUseBreakEven     = true;          // Use Break Even
input int      InpBreakEvenTrigger = 150;           // Break Even Trigger (points)
input bool     InpUseTrailingStop  = true;          // Use Trailing Stop
input int      InpTrailingStart    = 200;           // Trailing Start (points)

//--- Global variables
CTrade trade;
MqlTick currentTick;
MqlRates priceData[];
datetime lastBarTime = 0;

//+------------------------------------------------------------------+
//| Expert initialization function                                   |
//+------------------------------------------------------------------+
int OnInit()
{
   //--- Validate inputs
   if(InpDonchianPeriod < 2)
   {
      Print("Error: Donchian Period must be at least 2");
      return INIT_PARAMETERS_INCORRECT;
   }

   if(InpLotSize <= 0)
   {
      Print("Error: Lot size must be positive");
      return INIT_PARAMETERS_INCORRECT;
   }
   
   if(InpStopLoss <= 0 || InpTakeProfit <= 0)
   {
      Print("Error: Stop Loss and Take Profit must be positive");
      return INIT_PARAMETERS_INCORRECT;
   }

   //--- Set trade object properties
   trade.SetExpertMagicNumber(InpMagicNumber);
   trade.SetDeviationInPoints(InpSlippage);
   trade.SetAsyncMode(false);

   //--- Set symbol parameters
   trade.SetTypeFillingBySymbol(_Symbol);

   //--- Initialize last bar time
   lastBarTime = 0;
   
   //--- Initialize array as series
   ArraySetAsSeries(priceData, true);

   Print("Donchian Breakout EA initialized successfully on ", _Symbol);
   Print("Donchian Period: ", InpDonchianPeriod);
   Print("Lot Size: ", InpLotSize);
   Print("Stop Loss: ", InpStopLoss, " points");
   Print("Take Profit: ", InpTakeProfit, " points");
   
   return INIT_SUCCEEDED;
}

//+------------------------------------------------------------------+
//| Expert deinitialization function                                 |
//+------------------------------------------------------------------+
void OnDeinit(const int reason)
{
   Print("Donchian Breakout EA deinitialized, reason: ", reason);
}

//+------------------------------------------------------------------+
//| Expert tick function                                             |
//+------------------------------------------------------------------+
void OnTick()
{
   //--- Check if it's a new bar
   if(!IsNewBar())
      return;

   //--- Check maximum spread
   if(!CheckSpread())
      return;

   //--- Check if there are already open positions with this magic number
   if(CountOpenPositions() > 0)
   {
      //--- Manage existing positions
      ManageBreakEven();
      ManageTrailingStop();
      return;
   }

   //--- Check for breakout signals
   CheckForBreakout();
}

//+------------------------------------------------------------------+
//| Check if it's a new bar                                          |
//+------------------------------------------------------------------+
bool IsNewBar()
{
   datetime currentBarTime = iTime(_Symbol, PERIOD_CURRENT, 0);

   if(currentBarTime != lastBarTime)
   {
      lastBarTime = currentBarTime;
      return true;
   }

   return false;
}

//+------------------------------------------------------------------+
//| Check current spread against maximum allowed                     |
//+------------------------------------------------------------------+
bool CheckSpread()
{
   if(!SymbolInfoTick(_Symbol, currentTick))
   {
      Print("Error: Failed to get current tick");
      return false;
   }

   //--- Calculate spread in points (fixed type conversion)
   long spreadPoints = (long)MathRound((currentTick.ask - currentTick.bid) / _Point);

   if(spreadPoints > InpMaxSpread)
   {
      static int lastSpreadWarningTime = 0;
      int currentTime = (int)TimeCurrent();
      
      //--- Print warning only once per minute to avoid spam
      if(currentTime - lastSpreadWarningTime > 60)
      {
         Print("Spread too high: ", spreadPoints, " points. Maximum allowed: ", InpMaxSpread);
         lastSpreadWarningTime = currentTime;
      }
      return false;
   }

   return true;
}

//+------------------------------------------------------------------+
//| Count open positions with this magic number                      |
//+------------------------------------------------------------------+
int CountOpenPositions()
{
   int count = 0;

   for(int i = PositionsTotal() - 1; i >= 0; i--)
   {
      ulong ticket = PositionGetTicket(i);
      if(ticket > 0)
      {
         if(PositionGetString(POSITION_SYMBOL) == _Symbol &&
            PositionGetInteger(POSITION_MAGIC) == InpMagicNumber)
         {
            count++;
         }
      }
   }

   return count;
}

//+------------------------------------------------------------------+
//| Check for Donchian breakout                                      |
//+------------------------------------------------------------------+
void CheckForBreakout()
{
   //--- Load price data
   int barsToCopy = InpDonchianPeriod + 1;
   
   if(CopyRates(_Symbol, PERIOD_CURRENT, 0, barsToCopy, priceData) < barsToCopy)
   {
      Print("Error: Failed to copy price data. Error code: ", GetLastError());
      return;
   }

   //--- Calculate Donchian boundaries (excluding current bar)
   double highestHigh = priceData[1].high;
   double lowestLow = priceData[1].low;

   for(int i = 2; i <= InpDonchianPeriod; i++)
   {
      if(priceData[i].high > highestHigh)
         highestHigh = priceData[i].high;

      if(priceData[i].low < lowestLow)
         lowestLow = priceData[i].low;
   }

   //--- Get current bar close price
   double currentClose = priceData[0].close;

   //--- Check for upward breakout
   if(currentClose > highestHigh)
   {
      Print("Detected upward Donchian breakout: ", DoubleToString(currentClose, _Digits), 
            " > ", DoubleToString(highestHigh, _Digits));
      OpenBuyPosition();
      return;
   }

   //--- Check for downward breakout
   if(currentClose < lowestLow)
   {
      Print("Detected downward Donchian breakout: ", DoubleToString(currentClose, _Digits), 
            " < ", DoubleToString(lowestLow, _Digits));
      OpenSellPosition();
      return;
   }
}

//+------------------------------------------------------------------+
//| Open buy position                                                |
//+------------------------------------------------------------------+
void OpenBuyPosition()
{
   if(!SymbolInfoTick(_Symbol, currentTick))
   {
      Print("Error: Failed to get current tick");
      return;
   }

   double price = currentTick.ask;
   double sl = NormalizeDouble(price - InpStopLoss * _Point, _Digits);
   double tp = NormalizeDouble(price + InpTakeProfit * _Point, _Digits);

   if(trade.Buy(InpLotSize, _Symbol, price, sl, tp, "Donchian Breakout BUY"))
   {
      Print("Buy order opened successfully at price: ", DoubleToString(price, _Digits));
   }
   else
   {
      Print("Failed to open buy order. Error: ", GetLastError());
   }
}

//+------------------------------------------------------------------+
//| Open sell position                                               |
//+------------------------------------------------------------------+
void OpenSellPosition()
{
   if(!SymbolInfoTick(_Symbol, currentTick))
   {
      Print("Error: Failed to get current tick");
      return;
   }

   double price = currentTick.bid;
   double sl = NormalizeDouble(price + InpStopLoss * _Point, _Digits);
   double tp = NormalizeDouble(price - InpTakeProfit * _Point, _Digits);

   if(trade.Sell(InpLotSize, _Symbol, price, sl, tp, "Donchian Breakout SELL"))
   {
      Print("Sell order opened successfully at price: ", DoubleToString(price, _Digits));
   }
   else
   {
      Print("Failed to open sell order. Error: ", GetLastError());
   }
}

//+------------------------------------------------------------------+
//| Manage Break Even                                                |
//+------------------------------------------------------------------+
void ManageBreakEven()
{
   if(!InpUseBreakEven)
      return;

   for(int i = PositionsTotal() - 1; i >= 0; i--)
   {
      ulong ticket = PositionGetTicket(i);
      if(ticket == 0)
         continue;
         
      if(PositionGetString(POSITION_SYMBOL) != _Symbol ||
         PositionGetInteger(POSITION_MAGIC) != InpMagicNumber)
         continue;

      double openPrice = PositionGetDouble(POSITION_PRICE_OPEN);
      double currentPrice = PositionGetDouble(POSITION_PRICE_CURRENT);
      double stopLoss = PositionGetDouble(POSITION_SL);
      long positionType = PositionGetInteger(POSITION_TYPE);

      double profitPoints = 0;
      double breakEvenLevel = NormalizeDouble(openPrice, _Digits);

      if(positionType == POSITION_TYPE_BUY)
      {
         profitPoints = (currentPrice - openPrice) / _Point;

         if(profitPoints >= InpBreakEvenTrigger && stopLoss < breakEvenLevel)
         {
            if(trade.PositionModify(ticket, breakEvenLevel, PositionGetDouble(POSITION_TP)))
            {
               Print("Break Even activated for BUY position, ticket: ", ticket);
            }
         }
      }
      else if(positionType == POSITION_TYPE_SELL)
      {
         profitPoints = (openPrice - currentPrice) / _Point;

         if(profitPoints >= InpBreakEvenTrigger && (stopLoss > breakEvenLevel || stopLoss == 0))
         {
            if(trade.PositionModify(ticket, breakEvenLevel, PositionGetDouble(POSITION_TP)))
            {
               Print("Break Even activated for SELL position, ticket: ", ticket);
            }
         }
      }
   }
}

//+------------------------------------------------------------------+
//| Manage Trailing Stop                                             |
//+------------------------------------------------------------------+
void ManageTrailingStop()
{
   if(!InpUseTrailingStop)
      return;

   for(int i = PositionsTotal() - 1; i >= 0; i--)
   {
      ulong ticket = PositionGetTicket(i);
      if(ticket == 0)
         continue;
         
      if(PositionGetString(POSITION_SYMBOL) != _Symbol ||
         PositionGetInteger(POSITION_MAGIC) != InpMagicNumber)
         continue;

      double openPrice = PositionGetDouble(POSITION_PRICE_OPEN);
      double currentPrice = PositionGetDouble(POSITION_PRICE_CURRENT);
      double stopLoss = PositionGetDouble(POSITION_SL);
      long positionType = PositionGetInteger(POSITION_TYPE);

      double profitPoints = 0;
      double newStopLoss = 0;

      if(positionType == POSITION_TYPE_BUY)
      {
         profitPoints = (currentPrice - openPrice) / _Point;

         if(profitPoints >= InpTrailingStart)
         {
            newStopLoss = NormalizeDouble(currentPrice - InpTrailingStart * _Point, _Digits);

            if(newStopLoss > stopLoss)
            {
               if(trade.PositionModify(ticket, newStopLoss, PositionGetDouble(POSITION_TP)))
               {
                  Print("Trailing Stop moved for BUY position, ticket: ", ticket, 
                        ", new SL: ", DoubleToString(newStopLoss, _Digits));
               }
            }
         }
      }
      else if(positionType == POSITION_TYPE_SELL)
      {
         profitPoints = (openPrice - currentPrice) / _Point;

         if(profitPoints >= InpTrailingStart)
         {
            newStopLoss = NormalizeDouble(currentPrice + InpTrailingStart * _Point, _Digits);

            if(newStopLoss < stopLoss || stopLoss == 0)
            {
               if(trade.PositionModify(ticket, newStopLoss, PositionGetDouble(POSITION_TP)))
               {
                  Print("Trailing Stop moved for SELL position, ticket: ", ticket, 
                        ", new SL: ", DoubleToString(newStopLoss, _Digits));
               }
            }
         }
      }
   }
}
//+------------------------------------------------------------------+