
//+------------------------------------------------------------------+
//|                                             EmaPullbackTrader.mq5|
//|                                    Generated by Senior MQL5 Dev  |
//+------------------------------------------------------------------+
#property copyright "Senior MQL5 Developer"
#property link      ""
#property version   "1.00"
#property strict

#include <Trade\Trade.mqh>

//--- Input Parameters
input group "=== Lot & Risk ==="
input double InpLotSize       = 0.01;    // Lot Size
input int    InpStopLoss      = 300;     // Stop Loss (points)
input int    InpTakeProfit    = 600;     // Take Profit (points)
input int    InpMaxSpread     = 30;      // Max Spread (points)

input group "=== Order Management ==="
input ulong  InpMagicNumber   = 123456;  // Magic Number
input int    InpSlippage      = 10;      // Slippage (points)

input group "=== Break Even & Trailing ==="
input bool   InpUseBreakEven  = true;    // Use Break Even
input int    InpBreakEvenTrigger = 150;  // Break Even Trigger (points)
input bool   InpUseTrailing   = true;    // Use Trailing Stop
input int    InpTrailingStart = 200;     // Trailing Start (points)
input int    InpTrailingStep  = 10;      // Trailing Step (points)

input group "=== Indicator Parameters ==="
input int    InpEmaFastPeriod = 20;      // EMA Fast Period
input int    InpEmaSlowPeriod = 50;      // EMA Slow Period
input int    InpSwingBars      = 5;      // Swing Bars (Higher-Low/Lower-High)

//--- Global Variables
CTrade  trade;
MqlTick currentTick;
int     emaFastHandle;
int     emaSlowHandle;
datetime lastBarTime = 0;

//+------------------------------------------------------------------+
//| Expert initialization function                                   |
//+------------------------------------------------------------------+
int OnInit()
{
   // Set magic number for all trades
   trade.SetExpertMagicNumber(InpMagicNumber);
   trade.SetDeviationInPoints(InpSlippage);
   
   // Initialize indicator handles
   emaFastHandle = iMA(_Symbol, PERIOD_CURRENT, InpEmaFastPeriod, 0, MODE_EMA, PRICE_CLOSE);
   emaSlowHandle = iMA(_Symbol, PERIOD_CURRENT, InpEmaSlowPeriod, 0, MODE_EMA, PRICE_CLOSE);
   
   if(emaFastHandle == INVALID_HANDLE || emaSlowHandle == INVALID_HANDLE)
   {
      Print("Failed to create indicator handles. Error: ", GetLastError());
      return(INIT_FAILED);
   }
   
   return(INIT_SUCCEEDED);
}

//+------------------------------------------------------------------+
//| Expert deinitialization function                                 |
//+------------------------------------------------------------------+
void OnDeinit(const int reason)
{
   // Release indicator handles
   if(emaFastHandle != INVALID_HANDLE)
      IndicatorRelease(emaFastHandle);
   if(emaSlowHandle != INVALID_HANDLE)
      IndicatorRelease(emaSlowHandle);
}

//+------------------------------------------------------------------+
//| Expert tick function                                             |
//+------------------------------------------------------------------+
void OnTick()
{
   // Check for new bar
   if(!IsNewBar())
      return;
   
   // Check spread
   if(!CheckSpread())
      return;
   
   // Check existing positions with our magic number
   if(CountPositions() > 0)
      return;
   
   // Get indicator values
   double emaFast[], emaSlow[];
   ArraySetAsSeries(emaFast, true);
   ArraySetAsSeries(emaSlow, true);
   
   if(CopyBuffer(emaFastHandle, 0, 0, 3, emaFast) < 3)
   {
      Print("Failed to copy EMA fast data. Error: ", GetLastError());
      return;
   }
   
   if(CopyBuffer(emaSlowHandle, 0, 0, 3, emaSlow) < 3)
   {
      Print("Failed to copy EMA slow data. Error: ", GetLastError());
      return;
   }
   
   // Check for BUY signal
   if(CheckBuySignal(emaFast, emaSlow))
   {
      ExecuteBuy();
      return;
   }
   
   // Check for SELL signal
   if(CheckSellSignal(emaFast, emaSlow))
   {
      ExecuteSell();
   }
}

//+------------------------------------------------------------------+
//| Check for new bar                                                |
//+------------------------------------------------------------------+
bool IsNewBar()
{
   datetime currentBarTime = iTime(_Symbol, PERIOD_CURRENT, 0);
   
   if(currentBarTime != lastBarTime)
   {
      lastBarTime = currentBarTime;
      return(true);
   }
   
   return(false);
}

//+------------------------------------------------------------------+
//| Check spread                                                     |
//+------------------------------------------------------------------+
bool CheckSpread()
{
   if(!SymbolInfoTick(_Symbol, currentTick))
   {
      Print("Failed to get tick info. Error: ", GetLastError());
      return(false);
   }
   
   int currentSpread = (int)((currentTick.ask - currentTick.bid) / _Point);
   
   if(currentSpread > InpMaxSpread)
   {
      Print("Spread too high: ", currentSpread, " points (Max: ", InpMaxSpread, ")");
      return(false);
   }
   
   return(true);
}

//+------------------------------------------------------------------+
//| Count positions with our magic number                           |
//+------------------------------------------------------------------+
int CountPositions()
{
   int count = 0;
   
   for(int i = PositionsTotal() - 1; i >= 0; i--)
   {
      ulong ticket = PositionGetTicket(i);
      if(ticket > 0)
      {
         if(PositionSelectByTicket(ticket))
         {
            if(PositionGetString(POSITION_SYMBOL) == _Symbol && 
               PositionGetInteger(POSITION_MAGIC) == InpMagicNumber)
            {
               count++;
            }
         }
      }
   }
   
   return(count);
}

//+------------------------------------------------------------------+
//| Check for BUY signal                                             |
//+------------------------------------------------------------------+
bool CheckBuySignal(double &emaFast[], double &emaSlow[])
{
   // EMA Fast > EMA Slow (uptrend)
   if(emaFast[0] <= emaSlow[0] || emaFast[1] <= emaSlow[1])
      return(false);
   
   // Check for higher-low structure
   double currentLow = iLow(_Symbol, PERIOD_CURRENT, 0);
   double previousLow = FindSwingLow();
   
   if(previousLow == 0 || currentLow <= previousLow)
      return(false);
   
   // Check for breakout of pullback high
   double currentHigh = iHigh(_Symbol, PERIOD_CURRENT, 0);
   double previousHigh = FindSwingHigh();
   
   if(previousHigh == 0 || currentHigh <= previousHigh)
      return(false);
   
   // Check if price is breaking above the pullback high
   if(!SymbolInfoTick(_Symbol, currentTick))
      return(false);
   
   if(currentTick.ask <= previousHigh)
      return(false);
   
   return(true);
}

//+------------------------------------------------------------------+
//| Check for SELL signal                                            |
//+------------------------------------------------------------------+
bool CheckSellSignal(double &emaFast[], double &emaSlow[])
{
   // EMA Fast < EMA Slow (downtrend)
   if(emaFast[0] >= emaSlow[0] || emaFast[1] >= emaSlow[1])
      return(false);
   
   // Check for lower-high structure
   double currentHigh = iHigh(_Symbol, PERIOD_CURRENT, 0);
   double previousHigh = FindSwingHigh();
   
   if(previousHigh == 0 || currentHigh >= previousHigh)
      return(false);
   
   // Check for breakdown of pullback low
   double currentLow = iLow(_Symbol, PERIOD_CURRENT, 0);
   double previousLow = FindSwingLow();
   
   if(previousLow == 0 || currentLow >= previousLow)
      return(false);
   
   // Check if price is breaking below the pullback low
   if(!SymbolInfoTick(_Symbol, currentTick))
      return(false);
   
   if(currentTick.bid >= previousLow)
      return(false);
   
   return(true);
}

//+------------------------------------------------------------------+
//| Find swing low                                                   |
//+------------------------------------------------------------------+
double FindSwingLow()
{
   int shift = 0;
   
   // Search for the most recent swing low within the last 20 bars
   for(int i = 1; i < 20; i++)
   {
      double low = iLow(_Symbol, PERIOD_CURRENT, i);
      bool isSwingLow = true;
      
      // Check if this is a swing low (InpSwingBars bars on each side)
      for(int j = 1; j <= InpSwingBars; j++)
      {
         if(i - j < 0)
         {
            isSwingLow = false;
            break;
         }
         
         if(iLow(_Symbol, PERIOD_CURRENT, i - j) < low || 
            iLow(_Symbol, PERIOD_CURRENT, i + j) < low)
         {
            isSwingLow = false;
            break;
         }
      }
      
      if(isSwingLow)
         return(low);
   }
   
   return(0);
}

//+------------------------------------------------------------------+
//| Find swing high                                                  |
//+------------------------------------------------------------------+
double FindSwingHigh()
{
   // Search for the most recent swing high within the last 20 bars
   for(int i = 1; i < 20; i++)
   {
      double high = iHigh(_Symbol, PERIOD_CURRENT, i);
      bool isSwingHigh = true;
      
      // Check if this is a swing high (InpSwingBars bars on each side)
      for(int j = 1; j <= InpSwingBars; j++)
      {
         if(i - j < 0)
         {
            isSwingHigh = false;
            break;
         }
         
         if(iHigh(_Symbol, PERIOD_CURRENT, i - j) > high || 
            iHigh(_Symbol, PERIOD_CURRENT, i + j) > high)
         {
            isSwingHigh = false;
            break;
         }
      }
      
      if(isSwingHigh)
         return(high);
   }
   
   return(0);
}

//+------------------------------------------------------------------+
//| Execute BUY order                                                |
//+------------------------------------------------------------------+
void ExecuteBuy()
{
   if(!SymbolInfoTick(_Symbol, currentTick))
   {
      Print("Failed to get tick info. Error: ", GetLastError());
      return;
   }
   
   double price = currentTick.ask;
   double sl = price - InpStopLoss * _Point;
   double tp = price + InpTakeProfit * _Point;
   
   if(!trade.Buy(InpLotSize, _Symbol, price, sl, tp, "EMA Pullback BUY"))
   {
      Print("BUY order failed. Error: ", trade.ResultRetcode(), " - ", trade.ResultRetcodeDescription());
   }
   else
   {
      Print("BUY order placed successfully. Ticket: ", trade.ResultOrder());
   }
}

//+------------------------------------------------------------------+
//| Execute SELL order                                               |
//+------------------------------------------------------------------+
void ExecuteSell()
{
   if(!SymbolInfoTick(_Symbol, currentTick))
   {
      Print("Failed to get tick info. Error: ", GetLastError());
      return;
   }
   
   double price = currentTick.bid;
   double sl = price + InpStopLoss * _Point;
   double tp = price - InpTakeProfit * _Point;
   
   if(!trade.Sell(InpLotSize, _Symbol, price, sl, tp, "EMA Pullback SELL"))
   {
      Print("SELL order failed. Error: ", trade.ResultRetcode(), " - ", trade.ResultRetcodeDescription());
   }
   else
   {
      Print("SELL order placed successfully. Ticket: ", trade.ResultOrder());
   }
}

//+------------------------------------------------------------------+
//| Manage Break Even and Trailing Stop                              |
//+------------------------------------------------------------------+
void ManagePositions()
{
   // Iterate through all positions with our magic number
   for(int i = PositionsTotal() - 1; i >= 0; i--)
   {
      ulong ticket = PositionGetTicket(i);
      if(ticket > 0 && PositionSelectByTicket(ticket))
      {
         if(PositionGetString(POSITION_SYMBOL) == _Symbol && 
            PositionGetInteger(POSITION_MAGIC) == InpMagicNumber)
         {
            ManageSinglePosition(ticket);
         }
      }
   }
}

//+------------------------------------------------------------------+
//| Manage single position for BE/TS                                 |
//+------------------------------------------------------------------+
void ManageSinglePosition(ulong ticket)
{
   if(!PositionSelectByTicket(ticket))
      return;
   
   double positionOpenPrice = PositionGetDouble(POSITION_PRICE_OPEN);
   double positionCurrentSL = PositionGetDouble(POSITION_SL);
   double positionCurrentTP = PositionGetDouble(POSITION_TP);
   long positionType = PositionGetInteger(POSITION_TYPE);
   
   if(!SymbolInfoTick(_Symbol, currentTick))
      return;
   
   double currentPrice = (positionType == POSITION_TYPE_BUY) ? currentTick.bid : currentTick.ask;
   double point = _Point;
   double newSL = 0;
   
   // Break Even Management
   if(InpUseBreakEven)
   {
      if(positionType == POSITION_TYPE_BUY)
      {
         double beTriggerPrice = positionOpenPrice + InpBreakEvenTrigger * point;
         if(currentPrice >= beTriggerPrice && positionCurrentSL < positionOpenPrice)
         {
            newSL = positionOpenPrice;
            
            // Modify position with break even
            if(!trade.PositionModify(ticket, newSL, positionCurrentTP))
            {
               Print("Failed to set Break Even for BUY #", ticket, ". Error: ", trade.ResultRetcode());
            }
            else
            {
               Print("Break Even set for BUY #", ticket, " at: ", newSL);
               positionCurrentSL = newSL;
            }
         }
      }
      else if(positionType == POSITION_TYPE_SELL)
      {
         double beTriggerPrice = positionOpenPrice - InpBreakEvenTrigger * point;
         if(currentPrice <= beTriggerPrice && positionCurrentSL > positionOpenPrice)
         {
            newSL = positionOpenPrice;
            
            // Modify position with break even
            if(!trade.PositionModify(ticket, newSL, positionCurrentTP))
            {
               Print("Failed to set Break Even for SELL #", ticket, ". Error: ", trade.ResultRetcode());
            }
            else
            {
               Print("Break Even set for SELL #", ticket, " at: ", newSL);
               positionCurrentSL = newSL;
            }
         }
      }
   }
   
   // Trailing Stop Management
   if(InpUseTrailing && positionCurrentSL != 0)
   {
      if(positionType == POSITION_TYPE_BUY)
      {
         double trailingTriggerPrice = positionOpenPrice + InpTrailingStart * point;
         if(currentPrice >= trailingTriggerPrice)
         {
            newSL = currentPrice - InpTrailingStart * point;
            
            // Ensure SL only moves up
            if(newSL > positionCurrentSL + InpTrailingStep * point)
            {
               if(!trade.PositionModify(ticket, newSL, positionCurrentTP))
               {
                  Print("Failed to set Trailing Stop for BUY #", ticket, ". Error: ", trade.ResultRetcode());
               }
               else
               {
                  Print("Trailing Stop updated for BUY #", ticket, " to: ", newSL);
                  positionCurrentSL = newSL;
               }
            }
         }
      }
      else if(positionType == POSITION_TYPE_SELL)
      {
         double trailingTriggerPrice = positionOpenPrice - InpTrailingStart * point;
         if(currentPrice <= trailingTriggerPrice)
         {
            newSL = currentPrice + InpTrailingStart * point;
            
            // Ensure SL only moves down
            if(newSL < positionCurrentSL - InpTrailingStep * point || positionCurrentSL == 0)
            {
               if(!trade.PositionModify(ticket, newSL, positionCurrentTP))
               {
                  Print("Failed to set Trailing Stop for SELL #", ticket, ". Error: ", trade.ResultRetcode());
               }
               else
               {
                  Print("Trailing Stop updated for SELL #", ticket, " to: ", newSL);
                  positionCurrentSL = newSL;
               }
            }
         }
      }
   }
}

//+------------------------------------------------------------------+
//| Trade transaction function                                       |
//+------------------------------------------------------------------+
void OnTradeTransaction(const MqlTradeTransaction &trans,
                        const MqlTradeRequest &request,
                        const MqlTradeResult &result)
{
   // Auto-manage positions on trade events
   if(trans.type == TRADE_TRANSACTION_DEAL_ADD || 
      trans.type == TRADE_TRANSACTION_ORDER_ADD ||
      trans.type == TRADE_TRANSACTION_ORDER_UPDATE)
   {
      ManagePositions();
   }
}