
//+------------------------------------------------------------------+
//|                                                  SimpleHistEA.mq5 |
//|                                    Generated by Senior MQL5 Dev  |
//|                                                                  |
//+------------------------------------------------------------------+
#property copyright "Senior MQL5 Developer"
#property link      ""
#property version   "1.00"

#include <Trade\Trade.mqh>

//--- Input Parameters (mandatory)
input double InpLotSize        = 0.01;          // Lot size
input int    InpStopLoss       = 500;           // Stop Loss (points)
input int    InpTakeProfit     = 1000;          // Take Profit (points)
input ulong  InpMagicNumber    = 123456;        // Magic Number
input int    InpSlippage       = 10;            // Slippage (points)

//--- Break Even & Trailing Stop group
input bool   InpUseBreakEven   = true;           // Enable Break Even
input bool   InpUseTrailing    = true;           // Enable Trailing Stop

//--- Additional strategy parameters
input int    InpBreakEvenPoints = 150;           // Break Even trigger (points)
input int    InpTrailingStart   = 200;           // Trailing start (points)
input int    InpTrailingDistance = 200;          // Trailing distance (points)
input int    InpMaxSpread       = 30;            // Maximum allowed spread (points)

//--- Global variables
CTrade   trade;
int      handleOsMA;
datetime lastBarTime = 0;

//+------------------------------------------------------------------+
//| Expert initialization function                                   |
//+------------------------------------------------------------------+
int OnInit()
  {
   //--- Set trade parameters
   trade.SetDeviationInPoints(InpSlippage);
   trade.SetExpertMagicNumber(InpMagicNumber);

   //--- Create OsMA indicator handle (MACD histogram)
   handleOsMA = iOsMA(_Symbol, _Period, 12, 26, 9, PRICE_CLOSE);
   if(handleOsMA == INVALID_HANDLE)
     {
      Print("Failed to create OsMA indicator handle. Error: ", GetLastError());
      return(INIT_FAILED);
     }

   //--- Initialize last bar time
   lastBarTime = 0;

   Print("EA initialized successfully on ", _Symbol, " ", EnumToString(_Period));
   return(INIT_SUCCEEDED);
  }
//+------------------------------------------------------------------+
//| Expert deinitialization function                                 |
//+------------------------------------------------------------------+
void OnDeinit(const int reason)
  {
   //--- Release indicator handle
   if(handleOsMA != INVALID_HANDLE)
      IndicatorRelease(handleOsMA);
   Print("EA deinitialized. Reason: ", reason);
  }
//+------------------------------------------------------------------+
//| Expert tick function                                             |
//+------------------------------------------------------------------+
void OnTick()
  {
   //--- Check if a new bar has formed (only then we evaluate trading signals)
   datetime currentBarTime = iTime(_Symbol, _Period, 0);
   bool isNewBar = (currentBarTime != lastBarTime);
   if(isNewBar)
     {
      lastBarTime = currentBarTime;
      //--- Evaluate entry conditions only on new bar
      CheckForEntry();
     }

   //--- Manage open positions (Break Even & Trailing) on every tick
   if(InpUseBreakEven || InpUseTrailing)
      ManageOpenPositions();
  }
//+------------------------------------------------------------------+
//| Check entry signals and open a trade if valid                    |
//+------------------------------------------------------------------+
void CheckForEntry()
  {
   //--- Check maximum spread
   double spreadPoints = (SymbolInfoDouble(_Symbol, SYMBOL_ASK) - SymbolInfoDouble(_Symbol, SYMBOL_BID)) / _Point;
   if(spreadPoints > InpMaxSpread)
     {
      Print("Spread too high: ", spreadPoints, " points. Maximum allowed: ", InpMaxSpread);
      return;
     }

   //--- Ensure only one position is open with this magic number
   if(CountOpenPositions() >= 1)
      return;

   //--- Get OsMA histogram values (buffer 0)
   double hist[2];
   if(CopyBuffer(handleOsMA, 0, 1, 2, hist) != 2)
     {
      Print("Failed to copy OsMA histogram data. Error: ", GetLastError());
      return;
     }

   //--- Define histogram values
   double histCurrent  = hist[0];
   double histPrevious = hist[1];

   //--- Determine trading signal
   bool buySignal  = false;
   bool sellSignal = false;

   // BUY: histogram positive and increasing for two consecutive bars
   if(histCurrent > 0 && histPrevious > 0 && histCurrent > histPrevious)
      buySignal = true;
   // SELL: histogram negative and decreasing (more negative) for two consecutive bars
   else if(histCurrent < 0 && histPrevious < 0 && histCurrent < histPrevious)
      sellSignal = true;

   //--- Execute trade if signal exists
   if(buySignal)
     {
      double ask = SymbolInfoDouble(_Symbol, SYMBOL_ASK);
      double sl  = ask - InpStopLoss * _Point;
      double tp  = ask + InpTakeProfit * _Point;
      if(!trade.Buy(InpLotSize, _Symbol, ask, sl, tp, "Histogram Buy Signal"))
        {
         Print("Buy order failed. Error code: ", GetLastError(), ", Retcode: ", trade.ResultRetcode());
        }
      else
        {
         Print("Buy order opened at ", ask, " SL=", sl, " TP=", tp);
        }
     }
   else if(sellSignal)
     {
      double bid = SymbolInfoDouble(_Symbol, SYMBOL_BID);
      double sl  = bid + InpStopLoss * _Point;
      double tp  = bid - InpTakeProfit * _Point;
      if(!trade.Sell(InpLotSize, _Symbol, bid, sl, tp, "Histogram Sell Signal"))
        {
         Print("Sell order failed. Error code: ", GetLastError(), ", Retcode: ", trade.ResultRetcode());
        }
      else
        {
         Print("Sell order opened at ", bid, " SL=", sl, " TP=", tp);
        }
     }
  }
//+------------------------------------------------------------------+
//| Count open positions with our magic number                       |
//+------------------------------------------------------------------+
int CountOpenPositions()
  {
   int count = 0;
   for(int i = PositionsTotal() - 1; i >= 0; i--)
     {
      ulong ticket = PositionGetTicket(i);
      if(ticket > 0)
        {
         if(PositionGetString(POSITION_SYMBOL) == _Symbol && PositionGetInteger(POSITION_MAGIC) == InpMagicNumber)
            count++;
        }
     }
   return count;
  }
//+------------------------------------------------------------------+
//| Manage Break Even and Trailing Stop for open positions           |
//+------------------------------------------------------------------+
void ManageOpenPositions()
  {
   //--- Iterate through all open positions
   for(int i = PositionsTotal() - 1; i >= 0; i--)
     {
      ulong ticket = PositionGetTicket(i);
      if(ticket == 0)
         continue;

      //--- Check symbol and magic number
      if(PositionGetString(POSITION_SYMBOL) != _Symbol || PositionGetInteger(POSITION_MAGIC) != InpMagicNumber)
         continue;

      //--- Get position details
      long   posType   = PositionGetInteger(POSITION_TYPE);
      double openPrice = PositionGetDouble(POSITION_PRICE_OPEN);
      double sl        = PositionGetDouble(POSITION_SL);
      double tp        = PositionGetDouble(POSITION_TP);
      double currentBid = SymbolInfoDouble(_Symbol, SYMBOL_BID);
      double currentAsk = SymbolInfoDouble(_Symbol, SYMBOL_ASK);

      //--- Calculate profit in points
      double profitPoints = 0.0;
      if(posType == POSITION_TYPE_BUY)
         profitPoints = (currentBid - openPrice) / _Point;
      else if(posType == POSITION_TYPE_SELL)
         profitPoints = (openPrice - currentAsk) / _Point;

      //--- Break Even management
      if(InpUseBreakEven && profitPoints >= InpBreakEvenPoints)
        {
         double beLevel = openPrice; // Break even at entry
         // For buy: move SL to entry if current SL is below entry
         // For sell: move SL to entry if current SL is above entry
         bool modifyNeeded = false;
         if(posType == POSITION_TYPE_BUY && (sl < beLevel))
           {
            modifyNeeded = true;
           }
         else if(posType == POSITION_TYPE_SELL && (sl > beLevel))
           {
            modifyNeeded = true;
           }

         if(modifyNeeded)
           {
            if(trade.PositionModify(ticket, beLevel, tp))
               Print("Break Even applied: Position #", ticket, " SL moved to ", beLevel);
            else
               Print("Failed to apply Break Even for position #", ticket, ". Error: ", GetLastError());
           }
        }

      //--- Trailing Stop management
      if(InpUseTrailing && profitPoints >= InpTrailingStart)
        {
         double newSL = 0.0;
         if(posType == POSITION_TYPE_BUY)
           {
            newSL = currentBid - InpTrailingDistance * _Point;
            // Only move SL up (for buy) if newSL is greater than current SL
            if(newSL > sl)
              {
               if(trade.PositionModify(ticket, newSL, tp))
                  Print("Trailing updated: Position #", ticket, " new SL=", newSL);
               else
                  Print("Failed to update trailing for position #", ticket, ". Error: ", GetLastError());
              }
           }
         else if(posType == POSITION_TYPE_SELL)
           {
            newSL = currentAsk + InpTrailingDistance * _Point;
            // Only move SL down (for sell) if newSL is lower than current SL
            if(newSL < sl)
              {
               if(trade.PositionModify(ticket, newSL, tp))
                  Print("Trailing updated: Position #", ticket, " new SL=", newSL);
               else
                  Print("Failed to update trailing for position #", ticket, ". Error: ", GetLastError());
              }
           }
        }
     }
  }
//+------------------------------------------------------------------+