//+------------------------------------------------------------------+
//|                                              IchimokuKijunEA.mq5 |
//|                                    Generated by Senior MQL5 Dev  |
//|                                                                  |
//+------------------------------------------------------------------+
#property copyright "Senior MQL5 Developer"
#property link      ""
#property version   "1.00"
#property strict

#include <Trade\Trade.mqh>

//--- Input parameters
input double   InpLotSize          = 0.01;         // Lot size
input int      InpStopLoss         = 300;           // Stop Loss (points)
input int      InpTakeProfit       = 600;           // Take Profit (points)
input ulong    InpMagicNumber      = 123456;        // Magic Number
input int      InpSlippage         = 10;            // Slippage / Deviation (points)
input int      InpMaxSpreadPoints  = 30;            // Max spread allowed (points)
input int      InpMaxPositions     = 1;             // Max open positions

//--- Ichimoku parameters
input int      InpTenkanSen        = 9;             // Tenkan-sen g_period
input int      InpKijunSen         = 26;            // Kijun-sen g_period
input int      InpSenkouSpanB      = 52;            // Senkou Span B g_period

//--- Break Even & Trailing Stop
input bool     InpUseBreakEven     = true;          // Use Break Even
input int      InpBreakEvenTrigger = 150;           // Break Even trigger (points)
input int      InpBreakEvenLock    = 5;             // Break Even lock profit (points)
input bool     InpUseTrailingStop  = true;          // Use Trailing Stop
input int      InpTrailingStart    = 200;           // Trailing start (points)
input int      InpTrailingStep     = 20;            // Trailing step (points)

//--- Global variables
CTrade  g_trade;
int     g_ichimokuHandle;
double  g_point;
datetime g_lastBarTime = 0;
string  g_symbol;
ENUM_TIMEFRAMES g_period;

//+------------------------------------------------------------------+
//| Expert initialization function                                   |
//+------------------------------------------------------------------+
int OnInit()
  {
   g_symbol = _Symbol;
   g_period = _Period;
   g_point  = _Point;
   //--- Set magic number and deviation for g_trade operations
   g_trade.SetExpertMagicNumber(InpMagicNumber);
   g_trade.SetDeviationInPoints(InpSlippage);

   //--- Create Ichimoku indicator handle
   g_ichimokuHandle = iIchimoku(g_symbol, g_period, InpTenkanSen, InpKijunSen, InpSenkouSpanB);
   if(g_ichimokuHandle == INVALID_HANDLE)
     {
      Print("Failed to create Ichimoku indicator handle. Error: ", GetLastError());
      return(INIT_FAILED);
     }

   //--- Initialize last bar time
   g_lastBarTime = iTime(g_symbol, g_period, 0);
   if(g_lastBarTime == 0)
      g_lastBarTime = TimeCurrent();

   Print("IchimokuKijunEA initialized successfully on ", g_symbol, " ", EnumToString(g_period));
   return(INIT_SUCCEEDED);
  }

//+------------------------------------------------------------------+
//| Expert deinitialization function                                 |
//+------------------------------------------------------------------+
void OnDeinit(const int reason)
  {
   //--- Release indicator handle
   if(g_ichimokuHandle != INVALID_HANDLE)
     {
      IndicatorRelease(g_ichimokuHandle);
      g_ichimokuHandle = INVALID_HANDLE;
     }

   Print("IchimokuKijunEA deinitialized. Reason: ", reason);
  }

//+------------------------------------------------------------------+
//| Expert tick function                                             |
//+------------------------------------------------------------------+
void OnTick()
  {
   //--- Check for new bar
   if(!IsNewBar())
      return;

   //--- Check max spread
   if(!CheckSpread())
      return;

   //--- Manage existing positions (Break Even & Trailing Stop)
   ManagePositions();

   //--- Check number of open positions for this magic number
   if(CountOpenPositions() >= InpMaxPositions)
      return;

   //--- Check for entry signals
   int signal = GetEntrySignal();
   if(signal == 0)
      return;

   //--- Execute g_trade
   OpenPosition(signal);
  }

//+------------------------------------------------------------------+
//| Check if new bar has formed                                      |
//+------------------------------------------------------------------+
bool IsNewBar()
  {
   datetime currentBarTime = iTime(g_symbol, g_period, 0);
   if(currentBarTime == 0)
      return(false);

   if(currentBarTime != g_lastBarTime)
     {
      g_lastBarTime = currentBarTime;
      return(true);
     }
   return(false);
  }

//+------------------------------------------------------------------+
//| Check if spread is within acceptable range                       |
//+------------------------------------------------------------------+
bool CheckSpread()
  {
   long spread = SymbolInfoInteger(g_symbol, SYMBOL_SPREAD);
   double spreadPoints = (double)spread * g_point / _Point;
   
   if(spreadPoints > InpMaxSpreadPoints)
     {
      Print("Spread too high: ", spreadPoints, " points. Max allowed: ", InpMaxSpreadPoints);
      return(false);
     }
   return(true);
  }

//+------------------------------------------------------------------+
//| Count open positions for this magic number                       |
//+------------------------------------------------------------------+
int CountOpenPositions()
  {
   int count = 0;
   for(int i = PositionsTotal() - 1; i >= 0; i--)
     {
      ulong ticket = PositionGetTicket(i);
      if(ticket > 0 && PositionSelectByTicket(ticket))
        {
         if(PositionGetString(POSITION_SYMBOL) == g_symbol &&
            PositionGetInteger(POSITION_MAGIC) == InpMagicNumber)
            count++;
        }
     }
   return(count);
  }

//+------------------------------------------------------------------+
//| Get entry signal based on Ichimoku Kijun-sen pullback             |
//| Returns: 1 = Buy, -1 = Sell, 0 = No signal                       |
//+------------------------------------------------------------------+
int GetEntrySignal()
  {
   //--- Get Ichimoku values
   double tenkanSen[], kijunSen[], senkouSpanA[], senkouSpanB[];
   ArraySetAsSeries(tenkanSen, true);
   ArraySetAsSeries(kijunSen, true);
   ArraySetAsSeries(senkouSpanA, true);
   ArraySetAsSeries(senkouSpanB, true);

   if(CopyBuffer(g_ichimokuHandle, 0, 0, 3, tenkanSen) < 3)
      return(0);
   if(CopyBuffer(g_ichimokuHandle, 1, 0, 3, kijunSen) < 3)
      return(0);
   if(CopyBuffer(g_ichimokuHandle, 2, 0, 3, senkouSpanA) < 3)
      return(0);
   if(CopyBuffer(g_ichimokuHandle, 3, 0, 3, senkouSpanB) < 3)
      return(0);

   //--- Validate indicator data
   if(tenkanSen[1] == 0 || kijunSen[1] == 0 || tenkanSen[2] == 0 || kijunSen[2] == 0)
      return(0);

   //--- Get current and previous bar data
   double open1 = iOpen(g_symbol, g_period, 1);
   double close1 = iClose(g_symbol, g_period, 1);
   double open2 = iOpen(g_symbol, g_period, 2);
   double close2 = iClose(g_symbol, g_period, 2);
   double high1 = iHigh(g_symbol, g_period, 1);
   double low1  = iLow(g_symbol, g_period, 1);

   if(open1 == 0 || close1 == 0 || open2 == 0 || close2 == 0 || high1 == 0 || low1 == 0)
      return(0);

   //--- BUY signal: Price pulls back to Kijun-sen then closes bullish
   //--- Previous bar touched Kijun-sen (pullback) and current bar closes above it
   bool buyCondition = (low1 <= kijunSen[1] + g_point) && // Price touched Kijun-sen
                       (close1 > kijunSen[1]) &&        // Current bar closes above Kijun-sen
                       (close2 > kijunSen[2]) &&        // Previous bar closed above Kijun-sen
                       (close1 > open1);                // Current bar is bullish

   //--- SELL signal: Price pulls back to Kijun-sen then closes bearish
   bool sellCondition = (high1 >= kijunSen[1] - g_point) && // Price touched Kijun-sen
                        (close1 < kijunSen[1]) &&         // Current bar closes below Kijun-sen
                        (close2 < kijunSen[2]) &&         // Previous bar closed below Kijun-sen
                        (close1 < open1);                 // Current bar is bearish

   if(buyCondition)
      return(1);
   else if(sellCondition)
      return(-1);

   return(0);
  }

//+------------------------------------------------------------------+
//| Open a position based on signal                                  |
//+------------------------------------------------------------------+
void OpenPosition(int signal)
  {
   //--- Prepare price and SL/TP
   double price = 0;
   double sl = 0;
   double tp = 0;
   double slPrice = InpStopLoss * g_point;
   double tpPrice = InpTakeProfit * g_point;

   if(signal == 1) // Buy
     {
      price = SymbolInfoDouble(g_symbol, SYMBOL_ASK);
      sl = price - slPrice;
      tp = price + tpPrice;
      
      if(g_trade.Buy(InpLotSize, g_symbol, price, sl, tp, "Ichimoku Kijun Pullback Buy"))
        {
         if(g_trade.ResultRetcode() == TRADE_RETCODE_DONE)
            Print("Buy order executed successfully. Price: ", price, " SL: ", sl, " TP: ", tp);
         else
            Print("Buy order failed. Error: ", g_trade.ResultRetcode(), " - ", g_trade.ResultRetcodeDescription());
        }
      else
         Print("Buy order execution error: ", GetLastError());
     }
   else if(signal == -1) // Sell
     {
      price = SymbolInfoDouble(g_symbol, SYMBOL_BID);
      sl = price + slPrice;
      tp = price - tpPrice;
      
      if(g_trade.Sell(InpLotSize, g_symbol, price, sl, tp, "Ichimoku Kijun Pullback Sell"))
        {
         if(g_trade.ResultRetcode() == TRADE_RETCODE_DONE)
            Print("Sell order executed successfully. Price: ", price, " SL: ", sl, " TP: ", tp);
         else
            Print("Sell order failed. Error: ", g_trade.ResultRetcode(), " - ", g_trade.ResultRetcodeDescription());
        }
      else
         Print("Sell order execution error: ", GetLastError());
     }
  }

//+------------------------------------------------------------------+
//| Manage positions (Break Even & Trailing Stop)                    |
//+------------------------------------------------------------------+
void ManagePositions()
  {
   for(int i = PositionsTotal() - 1; i >= 0; i--)
     {
      ulong ticket = PositionGetTicket(i);
      if(ticket > 0 && PositionSelectByTicket(ticket))
        {
         if(PositionGetString(POSITION_SYMBOL) == g_symbol &&
            PositionGetInteger(POSITION_MAGIC) == InpMagicNumber)
           {
            if(InpUseBreakEven)
               ApplyBreakEven(ticket);
            if(InpUseTrailingStop)
               ApplyTrailingStop(ticket);
           }
        }
     }
  }

//+------------------------------------------------------------------+
//| Apply Break Even logic                                           |
//+------------------------------------------------------------------+
void ApplyBreakEven(ulong ticket)
  {
   if(!PositionSelectByTicket(ticket))
      return;

   double positionOpenPrice = PositionGetDouble(POSITION_PRICE_OPEN);
   double currentSL = PositionGetDouble(POSITION_SL);
   double currentTP = PositionGetDouble(POSITION_TP);
   long positionType = PositionGetInteger(POSITION_TYPE);
   
   double triggerPoints = InpBreakEvenTrigger * g_point;
   double lockPoints = InpBreakEvenLock * g_point;

   //--- Check if Break Even already applied
   bool breakEvenApplied = false;
   
   if(positionType == POSITION_TYPE_BUY)
     {
      double currentPrice = SymbolInfoDouble(g_symbol, SYMBOL_BID);
      double breakEvenSL = positionOpenPrice + lockPoints;
      
      //--- Check if break even already applied
      if(MathAbs(currentSL - breakEvenSL) < g_point)
         breakEvenApplied = true;
      
      //--- Apply Break Even if price moved in profit direction
      if(!breakEvenApplied && (currentPrice - positionOpenPrice) >= triggerPoints)
        {
         if(g_trade.PositionModify(ticket, breakEvenSL, currentTP))
           {
            if(g_trade.ResultRetcode() == TRADE_RETCODE_DONE)
               Print("Break Even applied for Buy position. New SL: ", breakEvenSL);
           }
        }
     }
   else if(positionType == POSITION_TYPE_SELL)
     {
      double currentPrice = SymbolInfoDouble(g_symbol, SYMBOL_ASK);
      double breakEvenSL = positionOpenPrice - lockPoints;
      
      //--- Check if break even already applied
      if(MathAbs(currentSL - breakEvenSL) < g_point)
         breakEvenApplied = true;
      
      //--- Apply Break Even if price moved in profit direction
      if(!breakEvenApplied && (positionOpenPrice - currentPrice) >= triggerPoints)
        {
         if(g_trade.PositionModify(ticket, breakEvenSL, currentTP))
           {
            if(g_trade.ResultRetcode() == TRADE_RETCODE_DONE)
               Print("Break Even applied for Sell position. New SL: ", breakEvenSL);
           }
        }
     }
  }

//+------------------------------------------------------------------+
//| Apply Trailing Stop logic                                        |
//+------------------------------------------------------------------+
void ApplyTrailingStop(ulong ticket)
  {
   if(!PositionSelectByTicket(ticket))
      return;

   double positionOpenPrice = PositionGetDouble(POSITION_PRICE_OPEN);
   double currentSL = PositionGetDouble(POSITION_SL);
   double currentTP = PositionGetDouble(POSITION_TP);
   long positionType = PositionGetInteger(POSITION_TYPE);
   
   double trailingStartPoints = InpTrailingStart * g_point;
   double trailingStepPoints = InpTrailingStep * g_point;

   if(positionType == POSITION_TYPE_BUY)
     {
      double currentPrice = SymbolInfoDouble(g_symbol, SYMBOL_BID);
      double newSL = currentPrice - trailingStartPoints;
      
      //--- Check if trailing should be activated
      if((currentPrice - positionOpenPrice) >= trailingStartPoints)
        {
         //--- Check if new SL is better than current SL
         if(newSL > currentSL + trailingStepPoints || currentSL == 0)
           {
            if(g_trade.PositionModify(ticket, newSL, currentTP))
              {
               if(g_trade.ResultRetcode() == TRADE_RETCODE_DONE)
                  Print("Trailing Stop updated for Buy position. New SL: ", newSL);
              }
           }
        }
     }
   else if(positionType == POSITION_TYPE_SELL)
     {
      double currentPrice = SymbolInfoDouble(g_symbol, SYMBOL_ASK);
      double newSL = currentPrice + trailingStartPoints;
      
      //--- Check if trailing should be activated
      if((positionOpenPrice - currentPrice) >= trailingStartPoints)
        {
         //--- Check if new SL is better than current SL
         if(newSL < currentSL - trailingStepPoints || currentSL == 0)
           {
            if(g_trade.PositionModify(ticket, newSL, currentTP))
              {
               if(g_trade.ResultRetcode() == TRADE_RETCODE_DONE)
                  Print("Trailing Stop updated for Sell position. New SL: ", newSL);
              }
           }
        }
     }
  }
//+------------------------------------------------------------------+