//+------------------------------------------------------------------+
//|                                                  EA_Template.mq5 |
//|                                    Generated by Senior MQL5 Dev  |
//|                                        Strategy: EMA20/50 + ADX14 |
//+------------------------------------------------------------------+
#property copyright "Senior MQL5 Developer"
#property link      ""
#property version   "1.00"

#include <Trade\Trade.mqh>

//--- Input parameters
input group "=== General Settings ==="
input double InpLotSize       = 0.01;     // Lot size
input ulong  InpMagicNumber   = 123456;   // Magic Number
input int    InpSlippage      = 10;       // Slippage (points)

input group "=== Trade Parameters ==="
input int    InpStopLoss      = 300;      // Stop Loss (points)
input int    InpTakeProfit    = 600;      // Take Profit (points)

input group "=== Market Filters ==="
input int    InpMaxSpread     = 30;       // Maximum allowed spread (points)

input group "=== EMA / ADX Parameters ==="
input int    InpFastEMA       = 20;       // Fast EMA period
input int    InpSlowEMA       = 50;       // Slow EMA period
input int    InpADXPeriod     = 14;       // ADX period
input double InpMinADX        = 25.0;     // Minimum ADX level to allow trade

input group "=== Break Even / Trailing Stop ==="
input bool   InpUseBreakEven  = true;     // Use Break Even
input int    InpBreakEvenPts  = 150;      // Break Even trigger (points)
input bool   InpUseTrailing   = true;     // Use Trailing Stop
input int    InpTrailingPts   = 200;      // Trailing Stop distance (points)

//--- Global objects
CTrade trade;

//--- Indicator handles
int hFastEMA = INVALID_HANDLE;
int hSlowEMA = INVALID_HANDLE;
int hADX     = INVALID_HANDLE;

//--- Last bar time
datetime lastBarTime = 0;

//+------------------------------------------------------------------+
//| Expert initialization function                                   |
//+------------------------------------------------------------------+
int OnInit()
  {
   //--- Validate inputs
   if(InpLotSize <= 0)
     {
      Print("Invalid Lot Size");
      return(INIT_PARAMETERS_INCORRECT);
     }
   if(InpFastEMA >= InpSlowEMA)
     {
      Print("Fast EMA period must be smaller than Slow EMA period");
      return(INIT_PARAMETERS_INCORRECT);
     }
   if(InpStopLoss <= 0 || InpTakeProfit <= 0)
     {
      Print("Stop Loss and Take Profit must be positive");
      return(INIT_PARAMETERS_INCORRECT);
     }

   //--- Setup trade object
   trade.SetExpertMagicNumber(InpMagicNumber);
   trade.SetDeviationInPoints(InpSlippage);
   trade.SetAsyncMode(false);

   //--- Create indicator handles
   hFastEMA = iMA(_Symbol, _Period, InpFastEMA, 0, MODE_EMA, PRICE_CLOSE);
   hSlowEMA = iMA(_Symbol, _Period, InpSlowEMA, 0, MODE_EMA, PRICE_CLOSE);
   hADX     = iADX(_Symbol, _Period, InpADXPeriod);

   if(hFastEMA == INVALID_HANDLE || hSlowEMA == INVALID_HANDLE || hADX == INVALID_HANDLE)
     {
      Print("Failed to create indicator handles");
      return(INIT_FAILED);
     }

   Print("EA initialized successfully on ", _Symbol, " / ", EnumToString(_Period));
   return(INIT_SUCCEEDED);
  }

//+------------------------------------------------------------------+
//| Expert deinitialization function                                 |
//+------------------------------------------------------------------+
void OnDeinit(const int reason)
  {
   //--- Release indicator handles
   if(hFastEMA != INVALID_HANDLE)
      IndicatorRelease(hFastEMA);
   if(hSlowEMA != INVALID_HANDLE)
      IndicatorRelease(hSlowEMA);
   if(hADX != INVALID_HANDLE)
      IndicatorRelease(hADX);

   Print("EA deinitialized, reason: ", reason);
  }

//+------------------------------------------------------------------+
//| Expert tick function                                             |
//+------------------------------------------------------------------+
void OnTick()
  {
   //--- Check for new bar
   if(!IsNewBar())
      return;

   //--- Check spread filter
   if(!CheckSpread())
      return;

   //--- Check if there is already an open position for this EA
   if(CountOpenPositions() > 0)
      return;

   //--- Get current indicator values (bar 1 = closed bar)
   double fastEMA[];
   double slowEMA[];
   double adxBuffer[], adxPlusDI[], adxMinusDI[];

   ArraySetAsSeries(fastEMA, true);
   ArraySetAsSeries(slowEMA, true);
   ArraySetAsSeries(adxBuffer, true);
   ArraySetAsSeries(adxPlusDI, true);
   ArraySetAsSeries(adxMinusDI, true);

   if(CopyBuffer(hFastEMA, 0, 1, 3, fastEMA) < 3)
     {
      Print("Failed to copy Fast EMA buffer");
      return;
     }
   if(CopyBuffer(hSlowEMA, 0, 1, 3, slowEMA) < 3)
     {
      Print("Failed to copy Slow EMA buffer");
      return;
     }
   if(CopyBuffer(hADX, 0, 1, 3, adxBuffer) < 3)
     {
      Print("Failed to copy ADX main buffer");
      return;
     }
   if(CopyBuffer(hADX, 1, 1, 3, adxPlusDI) < 3)
     {
      Print("Failed to copy ADX +DI buffer");
      return;
     }
   if(CopyBuffer(hADX, 2, 1, 3, adxMinusDI) < 3)
     {
      Print("Failed to copy ADX -DI buffer");
      return;
     }

   double fastEMA_1 = fastEMA[0];    // closed bar value
   double slowEMA_1 = slowEMA[0];    // closed bar value
   double fastEMA_2 = fastEMA[1];    // previous bar value
   double slowEMA_2 = slowEMA[1];    // previous bar value
   double adx_1     = adxBuffer[0];  // closed bar ADX
   double adx_2     = adxBuffer[1];  // previous bar ADX
   double plusDI_1  = adxPlusDI[0];
   double minusDI_1 = adxMinusDI[0];

   //--- Check ADX threshold: ADX above threshold on current OR previous bar (crossing above)
   bool adxStrong = (adx_1 >= InpMinADX || adx_2 >= InpMinADX);
   if(!adxStrong)
      return;

   //--- Buy signal: Fast EMA crosses above Slow EMA, ADX strong, +DI > -DI
   bool emaCrossUp = (fastEMA_2 <= slowEMA_2 && fastEMA_1 > slowEMA_1);
   if(emaCrossUp && plusDI_1 > minusDI_1)
     {
      ExecuteBuy();
      return;
     }

   //--- Sell signal: Fast EMA crosses below Slow EMA, ADX strong, -DI > +DI
   bool emaCrossDown = (fastEMA_2 >= slowEMA_2 && fastEMA_1 < slowEMA_1);
   if(emaCrossDown && minusDI_1 > plusDI_1)
     {
      ExecuteSell();
     }
  }

//+------------------------------------------------------------------+
//| Check if a new bar has appeared                                  |
//+------------------------------------------------------------------+
bool IsNewBar()
  {
   datetime currentBarTime = iTime(_Symbol, _Period, 0);
   if(currentBarTime != lastBarTime)
     {
      lastBarTime = currentBarTime;
      return(true);
     }
   return(false);
  }

//+------------------------------------------------------------------+
//| Check spread filter                                              |
//+------------------------------------------------------------------+
bool CheckSpread()
  {
   long currentSpread = SymbolInfoInteger(_Symbol, SYMBOL_SPREAD);
   if(currentSpread > InpMaxSpread)
     {
      // Spread too high, skip trading
      return(false);
     }
   return(true);
  }

//+------------------------------------------------------------------+
//| Count open positions for this EA's magic number                  |
//+------------------------------------------------------------------+
int CountOpenPositions()
  {
   int count = 0;
   for(int i = PositionsTotal() - 1; i >= 0; i--)
     {
      ulong ticket = PositionGetTicket(i);
      if(ticket == 0)
         continue;
      if(PositionGetString(POSITION_SYMBOL) != _Symbol)
         continue;
      if(PositionGetInteger(POSITION_MAGIC) != InpMagicNumber)
         continue;
      count++;
     }
   return(count);
  }

//+------------------------------------------------------------------+
//| Execute Buy order                                                |
//+------------------------------------------------------------------+
void ExecuteBuy()
  {
   double price = SymbolInfoDouble(_Symbol, SYMBOL_ASK);
   double sl    = NormalizeDouble(price - InpStopLoss * _Point, _Digits);
   double tp    = NormalizeDouble(price + InpTakeProfit * _Point, _Digits);

   trade.Buy(InpLotSize, _Symbol, price, sl, tp, "EMA20/50 + ADX14 Buy");

   if(trade.ResultRetcode() != TRADE_RETCODE_DONE)
     {
      Print("Buy order failed. Retcode: ", trade.ResultRetcode(), " - ", trade.ResultRetcodeDescription());
     }
  }

//+------------------------------------------------------------------+
//| Execute Sell order                                               |
//+------------------------------------------------------------------+
void ExecuteSell()
  {
   double price = SymbolInfoDouble(_Symbol, SYMBOL_BID);
   double sl    = NormalizeDouble(price + InpStopLoss * _Point, _Digits);
   double tp    = NormalizeDouble(price - InpTakeProfit * _Point, _Digits);

   trade.Sell(InpLotSize, _Symbol, price, sl, tp, "EMA20/50 + ADX14 Sell");

   if(trade.ResultRetcode() != TRADE_RETCODE_DONE)
     {
      Print("Sell order failed. Retcode: ", trade.ResultRetcode(), " - ", trade.ResultRetcodeDescription());
     }
  }

//+------------------------------------------------------------------+
//| Manage open positions: Break Even and Trailing Stop              |
//+------------------------------------------------------------------+
void ManageOpenPositions()
  {
   for(int i = PositionsTotal() - 1; i >= 0; i--)
     {
      ulong ticket = PositionGetTicket(i);
      if(ticket == 0)
         continue;
      if(PositionGetString(POSITION_SYMBOL) != _Symbol)
         continue;
      if(PositionGetInteger(POSITION_MAGIC) != InpMagicNumber)
         continue;

      long posType = PositionGetInteger(POSITION_TYPE);
      double currentPrice = (posType == POSITION_TYPE_BUY) ? SymbolInfoDouble(_Symbol, SYMBOL_BID) : SymbolInfoDouble(_Symbol, SYMBOL_ASK);
      double entryPrice   = PositionGetDouble(POSITION_PRICE_OPEN);
      double currentSL    = PositionGetDouble(POSITION_SL);
      double currentTP    = PositionGetDouble(POSITION_TP);
      double pointsProfit = (posType == POSITION_TYPE_BUY) ? (currentPrice - entryPrice) / _Point : (entryPrice - currentPrice) / _Point;

      //--- Break Even
      if(InpUseBreakEven && pointsProfit >= InpBreakEvenPts)
        {
         double newSL = entryPrice;
         if(posType == POSITION_TYPE_BUY && (currentSL < newSL || currentSL == 0))
           {
            if(trade.PositionModify(ticket, newSL, currentTP))
               Print("Break Even triggered for Buy #", ticket);
           }
         if(posType == POSITION_TYPE_SELL && (currentSL > newSL || currentSL == 0))
           {
            if(trade.PositionModify(ticket, newSL, currentTP))
               Print("Break Even triggered for Sell #", ticket);
           }
        }

      //--- Trailing Stop (only if break even already triggered or SL distance condition met)
      if(InpUseTrailing && pointsProfit >= InpTrailingPts)
        {
         double newSL = 0;
         if(posType == POSITION_TYPE_BUY)
           {
            newSL = currentPrice - InpTrailingPts * _Point;
            if(newSL > currentSL && newSL >= entryPrice)
              {
               if(trade.PositionModify(ticket, newSL, currentTP))
                  Print("Trailing Stop updated for Buy #", ticket);
              }
           }
         else if(posType == POSITION_TYPE_SELL)
           {
            newSL = currentPrice + InpTrailingPts * _Point;
            if((newSL < currentSL || currentSL == 0) && newSL <= entryPrice)
              {
               if(trade.PositionModify(ticket, newSL, currentTP))
                  Print("Trailing Stop updated for Sell #", ticket);
              }
           }
        }
     }
  }

//+------------------------------------------------------------------+
//| Timer function (used to manage positions every second)           |
//+------------------------------------------------------------------+
void OnTimer()
  {
   ManageOpenPositions();
  }
//+------------------------------------------------------------------+