
//+------------------------------------------------------------------+
//|                                                    BreakoutEA.mq5 |
//|                                      Generated by Senior MQL5 Dev |
//+------------------------------------------------------------------+
#property copyright "Senior MQL5 Developer"
#property link      ""
#property version   "1.00"
#property description "Breakout strategy based on 15-bar high/low with close near extreme."
#property description "Includes SL, TP, Break Even, and Trailing Stop management."

#include <Trade\Trade.mqh>

//--- Input parameters
input group "=== Trade Settings ==="
input double InpLotSize       = 0.01;       // Lot Size
input int    InpStopLoss      = 300;        // Stop Loss (points)
input int    InpTakeProfit    = 600;        // Take Profit (points)
input ulong  InpMagicNumber   = 202501;     // Magic Number
input int    InpSlippage      = 10;         // Slippage / Deviation (points)
input int    InpMaxSpread     = 30;         // Maximum Spread Allowed (points)

input group "=== Trade Management ==="
input bool   InpUseBreakEven  = true;       // Use Break Even
input int    InpBreakEvenPips = 150;        // Break Even Trigger (points)
input int    InpBreakEvenLock = 0;          // Break Even Lock Profit (points, 0 = BE)
input bool   InpUseTrailing   = true;       // Use Trailing Stop
input int    InpTrailingStart = 200;        // Trailing Start (points)
input int    InpTrailingStep  = 50;         // Trailing Step (points)

//--- Global variables
CTrade  trade;
MqlRates rates[];
datetime lastBarTime = 0;
int      barsCount   = 15; // Number of bars for breakout

//+------------------------------------------------------------------+
//| Expert initialization function                                   |
//+------------------------------------------------------------------+
int OnInit()
{
   // Set magic number and deviation for CTrade
   trade.SetExpertMagicNumber(InpMagicNumber);
   trade.SetDeviationInPoints(InpSlippage);
   trade.SetTypeFillingBySymbol(_Symbol);

   // Validate inputs
   if(InpLotSize <= 0)
   {
      Print("Invalid Lot Size. EA stopped.");
      return(INIT_PARAMETERS_INCORRECT);
   }
   if(InpStopLoss <= 0 || InpTakeProfit <= 0)
   {
      Print("Invalid SL/TP. EA stopped.");
      return(INIT_PARAMETERS_INCORRECT);
   }
   if(InpBreakEvenPips <= 0 || InpTrailingStart <= 0)
   {
      Print("Invalid BE/Trailing parameters. EA stopped.");
      return(INIT_PARAMETERS_INCORRECT);
   }

   Print("BreakoutEA initialized successfully. Magic: ", InpMagicNumber);
   return(INIT_SUCCEEDED);
}

//+------------------------------------------------------------------+
//| Expert deinitialization function                                 |
//+------------------------------------------------------------------+
void OnDeinit(const int reason)
{
   Print("BreakoutEA deinitialized. Reason: ", reason);
}

//+------------------------------------------------------------------+
//| Expert tick function                                             |
//+------------------------------------------------------------------+
void OnTick()
{
   //--- Check for new bar
   if(!IsNewBar())
      return;

   //--- Check maximum spread
   if(!CheckSpread())
      return;

   //--- Count open positions for this EA
   int positions = CountOpenPositions();
   if(positions >= 1)
   {
      // Manage existing positions (BE & Trailing)
      ManageOpenPositions();
      return;
   }

   //--- Look for trade signals
   int signal = GetBreakoutSignal();
   if(signal == 1) // Buy signal
   {
      OpenBuy();
   }
   else if(signal == -1) // Sell signal
   {
      OpenSell();
   }
}

//+------------------------------------------------------------------+
//| Check if a new bar has formed                                    |
//+------------------------------------------------------------------+
bool IsNewBar()
{
   datetime currentBarTime = iTime(_Symbol, PERIOD_CURRENT, 0);
   if(currentBarTime != lastBarTime)
   {
      lastBarTime = currentBarTime;
      return true;
   }
   return false;
}

//+------------------------------------------------------------------+
//| Check if current spread is acceptable                            |
//+------------------------------------------------------------------+
bool CheckSpread()
{
   double ask = SymbolInfoDouble(_Symbol, SYMBOL_ASK);
   double bid = SymbolInfoDouble(_Symbol, SYMBOL_BID);
   double spread = (ask - bid) / _Point;
   
   if(spread > InpMaxSpread)
   {
      Print("Spread too high: ", spread, " points. Max allowed: ", InpMaxSpread);
      return false;
   }
   return true;
}

//+------------------------------------------------------------------+
//| Count open positions for this EA's magic number                  |
//+------------------------------------------------------------------+
int CountOpenPositions()
{
   int count = 0;
   for(int i = PositionsTotal() - 1; i >= 0; i--)
   {
      ulong ticket = PositionGetTicket(i);
      if(ticket > 0)
      {
         if(PositionGetString(POSITION_SYMBOL) == _Symbol &&
            PositionGetInteger(POSITION_MAGIC) == InpMagicNumber)
         {
            count++;
         }
      }
   }
   return count;
}

//+------------------------------------------------------------------+
//| Get breakout signal based on 15-bar high/low                     |
//+------------------------------------------------------------------+
int GetBreakoutSignal()
{
   // Copy required bars (16 bars: 15 previous + 1 current signal bar)
   if(CopyRates(_Symbol, PERIOD_CURRENT, 1, barsCount + 1, rates) != barsCount + 1)
   {
      Print("Failed to copy rates. Error: ", GetLastError());
      return 0;
   }

   // Calculate high and low of previous 15 bars (indices 1 to 15)
   double highest = rates[1].high;
   double lowest  = rates[1].low;
   double highestClose = rates[1].close;
   double lowestClose  = rates[1].close;

   for(int i = 2; i <= barsCount; i++)
   {
      if(rates[i].high > highest)
         highest = rates[i].high;
      if(rates[i].low < lowest)
         lowest = rates[i].low;
      // Track close of the bar with highest high and lowest low
      if(rates[i].high >= highest)
         highestClose = rates[i].close;
      if(rates[i].low <= lowest)
         lowestClose = rates[i].close;
   }

   // Current bar (index 0) breaks above highest high or below lowest low
   double currentClose = rates[0].close;
   double currentHigh  = rates[0].high;
   double currentLow   = rates[0].low;

   // Buy signal: current bar breaks above 15-bar high and closes near its high
   if(currentHigh > highest && currentLow <= highest)
   {
      // Check if close is near the bar's extreme (within 25% of bar range from high)
      double barRange = currentHigh - currentLow;
      double closeDistanceFromHigh = currentHigh - currentClose;
      
      if(barRange > 0 && closeDistanceFromHigh <= barRange * 0.25)
      {
         Print("Buy Signal: Break above 15-bar high at ", highest);
         return 1;
      }
   }

   // Sell signal: current bar breaks below 15-bar low and closes near its low
   if(currentLow < lowest && currentHigh >= lowest)
   {
      // Check if close is near the bar's extreme (within 25% of bar range from low)
      double barRange = currentHigh - currentLow;
      double closeDistanceFromLow = currentClose - currentLow;
      
      if(barRange > 0 && closeDistanceFromLow <= barRange * 0.25)
      {
         Print("Sell Signal: Break below 15-bar low at ", lowest);
         return -1;
      }
   }

   return 0;
}

//+------------------------------------------------------------------+
//| Open Buy position                                                |
//+------------------------------------------------------------------+
void OpenBuy()
{
   double price = SymbolInfoDouble(_Symbol, SYMBOL_ASK);
   double sl = price - InpStopLoss * _Point;
   double tp = price + InpTakeProfit * _Point;

   // Normalize prices
   sl = NormalizeDouble(sl, _Digits);
   tp = NormalizeDouble(tp, _Digits);

   if(trade.Buy(InpLotSize, _Symbol, price, sl, tp, "Breakout EA Buy"))
   {
      Print("Buy order opened successfully. Ticket: ", trade.ResultOrder());
   }
   else
   {
      Print("Failed to open Buy order. Error: ", trade.ResultRetcode(), " - ", trade.ResultRetcodeDescription());
   }
}

//+------------------------------------------------------------------+
//| Open Sell position                                               |
//+------------------------------------------------------------------+
void OpenSell()
{
   double price = SymbolInfoDouble(_Symbol, SYMBOL_BID);
   double sl = price + InpStopLoss * _Point;
   double tp = price - InpTakeProfit * _Point;

   // Normalize prices
   sl = NormalizeDouble(sl, _Digits);
   tp = NormalizeDouble(tp, _Digits);

   if(trade.Sell(InpLotSize, _Symbol, price, sl, tp, "Breakout EA Sell"))
   {
      Print("Sell order opened successfully. Ticket: ", trade.ResultOrder());
   }
   else
   {
      Print("Failed to open Sell order. Error: ", trade.ResultRetcode(), " - ", trade.ResultRetcodeDescription());
   }
}

//+------------------------------------------------------------------+
//| Manage open positions (Break Even & Trailing Stop)               |
//+------------------------------------------------------------------+
void ManageOpenPositions()
{
   for(int i = PositionsTotal() - 1; i >= 0; i--)
   {
      ulong ticket = PositionGetTicket(i);
      if(ticket > 0)
      {
         if(PositionGetString(POSITION_SYMBOL) == _Symbol &&
            PositionGetInteger(POSITION_MAGIC) == InpMagicNumber)
         {
            double currentSL = PositionGetDouble(POSITION_SL);
            double currentTP = PositionGetDouble(POSITION_TP);
            double entryPrice = PositionGetDouble(POSITION_PRICE_OPEN);
            long positionType = PositionGetInteger(POSITION_TYPE);
            
            double currentPrice;
            if(positionType == POSITION_TYPE_BUY)
               currentPrice = SymbolInfoDouble(_Symbol, SYMBOL_BID);
            else if(positionType == POSITION_TYPE_SELL)
               currentPrice = SymbolInfoDouble(_Symbol, SYMBOL_ASK);
            else
               continue;

            //--- Break Even Logic
            if(InpUseBreakEven)
            {
               double bePrice;
               if(positionType == POSITION_TYPE_BUY)
               {
                  double profitPoints = (currentPrice - entryPrice) / _Point;
                  if(profitPoints >= InpBreakEvenPips)
                  {
                     bePrice = entryPrice + InpBreakEvenLock * _Point;
                     bePrice = NormalizeDouble(bePrice, _Digits);
                     
                     if(currentSL < bePrice || currentSL == 0)
                     {
                        if(trade.PositionModify(ticket, bePrice, currentTP))
                           Print("Break Even set for Buy #", ticket, " at ", bePrice);
                        else
                           Print("Failed to set BE for Buy #", ticket, ". Error: ", trade.ResultRetcode());
                     }
                  }
               }
               else if(positionType == POSITION_TYPE_SELL)
               {
                  double profitPoints = (entryPrice - currentPrice) / _Point;
                  if(profitPoints >= InpBreakEvenPips)
                  {
                     bePrice = entryPrice - InpBreakEvenLock * _Point;
                     bePrice = NormalizeDouble(bePrice, _Digits);
                     
                     if(currentSL > bePrice || currentSL == 0)
                     {
                        if(trade.PositionModify(ticket, bePrice, currentTP))
                           Print("Break Even set for Sell #", ticket, " at ", bePrice);
                        else
                           Print("Failed to set BE for Sell #", ticket, ". Error: ", trade.ResultRetcode());
                     }
                  }
               }
            }

            //--- Trailing Stop Logic
            if(InpUseTrailing)
            {
               if(positionType == POSITION_TYPE_BUY)
               {
                  double trailSL = currentPrice - InpTrailingStart * _Point;
                  trailSL = NormalizeDouble(trailSL, _Digits);
                  
                  // Check if trailing should be activated
                  if(trailSL > entryPrice && trailSL > currentSL)
                  {
                     // Apply trailing step
                     if(currentSL == 0 || trailSL - currentSL >= InpTrailingStep * _Point)
                     {
                        if(trade.PositionModify(ticket, trailSL, currentTP))
                           Print("Trailing Stop updated for Buy #", ticket, " to ", trailSL);
                        else
                           Print("Failed to update trailing for Buy #", ticket, ". Error: ", trade.ResultRetcode());
                     }
                  }
               }
               else if(positionType == POSITION_TYPE_SELL)
               {
                  double trailSL = currentPrice + InpTrailingStart * _Point;
                  trailSL = NormalizeDouble(trailSL, _Digits);
                  
                  // Check if trailing should be activated
                  if(trailSL < entryPrice && trailSL < currentSL)
                  {
                     // Apply trailing step
                     if(currentSL == 0 || currentSL - trailSL >= InpTrailingStep * _Point)
                     {
                        if(trade.PositionModify(ticket, trailSL, currentTP))
                           Print("Trailing Stop updated for Sell #", ticket, " to ", trailSL);
                        else
                           Print("Failed to update trailing for Sell #", ticket, ". Error: ", trade.ResultRetcode());
                     }
                  }
               }
            }
         }
      }
   }
}
//+------------------------------------------------------------------+